/**
 *
 *  AuditLogs.cc
 *  DO NOT EDIT. This file is generated by drogon_ctl
 *
 */

#include "AuditLogs.h"
#include <drogon/utils/Utilities.h>
#include <codecvt>
#include <string>

using namespace drogon;
using namespace drogon::orm;
using namespace drogon_model::UELocalDB::core;

const std::string AuditLogs::Cols::_id = "\"id\"";
const std::string AuditLogs::Cols::_audit_key = "\"audit_key\"";
const std::string AuditLogs::Cols::_tx_id = "\"tx_id\"";
const std::string AuditLogs::Cols::_project_id = "\"project_id\"";
const std::string AuditLogs::Cols::_user_id = "\"user_id\"";
const std::string AuditLogs::Cols::_session_id = "\"session_id\"";
const std::string AuditLogs::Cols::_object_type = "\"object_type\"";
const std::string AuditLogs::Cols::_object_id = "\"object_id\"";
const std::string AuditLogs::Cols::_action = "\"action\"";
const std::string AuditLogs::Cols::_result_code = "\"result_code\"";
const std::string AuditLogs::Cols::_before_json = "\"before_json\"";
const std::string AuditLogs::Cols::_after_json = "\"after_json\"";
const std::string AuditLogs::Cols::_detail_json = "\"detail_json\"";
const std::string AuditLogs::Cols::_created_at = "\"created_at\"";
const std::string AuditLogs::primaryKeyName = "id";
const bool AuditLogs::hasPrimaryKey = true;
const std::string AuditLogs::tableName = "core.\"audit_logs\"";

const std::vector<typename AuditLogs::MetaData> AuditLogs::metaData_={
{"id","int64_t","bigint",8,1,1,1},
{"audit_key","std::string","character varying",128,0,0,0},
{"tx_id","int64_t","bigint",8,0,0,0},
{"project_id","int64_t","bigint",8,0,0,0},
{"user_id","int64_t","bigint",8,0,0,0},
{"session_id","int64_t","bigint",8,0,0,0},
{"object_type","std::string","character varying",128,0,0,0},
{"object_id","std::string","character varying",128,0,0,0},
{"action","std::string","character varying",64,0,0,1},
{"result_code","std::string","character varying",32,0,0,0},
{"before_json","std::string","jsonb",0,0,0,0},
{"after_json","std::string","jsonb",0,0,0,0},
{"detail_json","std::string","jsonb",0,0,0,0},
{"created_at","::trantor::Date","timestamp without time zone",0,0,0,1}
};
const std::string &AuditLogs::getColumnName(size_t index) noexcept(false)
{
    assert(index < metaData_.size());
    return metaData_[index].colName_;
}
AuditLogs::AuditLogs(const Row &r, const ssize_t indexOffset) noexcept
{
    if(indexOffset < 0)
    {
        if(!r["id"].isNull())
        {
            id_=std::make_shared<int64_t>(r["id"].as<int64_t>());
        }
        if(!r["audit_key"].isNull())
        {
            auditKey_=std::make_shared<std::string>(r["audit_key"].as<std::string>());
        }
        if(!r["tx_id"].isNull())
        {
            txId_=std::make_shared<int64_t>(r["tx_id"].as<int64_t>());
        }
        if(!r["project_id"].isNull())
        {
            projectId_=std::make_shared<int64_t>(r["project_id"].as<int64_t>());
        }
        if(!r["user_id"].isNull())
        {
            userId_=std::make_shared<int64_t>(r["user_id"].as<int64_t>());
        }
        if(!r["session_id"].isNull())
        {
            sessionId_=std::make_shared<int64_t>(r["session_id"].as<int64_t>());
        }
        if(!r["object_type"].isNull())
        {
            objectType_=std::make_shared<std::string>(r["object_type"].as<std::string>());
        }
        if(!r["object_id"].isNull())
        {
            objectId_=std::make_shared<std::string>(r["object_id"].as<std::string>());
        }
        if(!r["action"].isNull())
        {
            action_=std::make_shared<std::string>(r["action"].as<std::string>());
        }
        if(!r["result_code"].isNull())
        {
            resultCode_=std::make_shared<std::string>(r["result_code"].as<std::string>());
        }
        if(!r["before_json"].isNull())
        {
            beforeJson_=std::make_shared<std::string>(r["before_json"].as<std::string>());
        }
        if(!r["after_json"].isNull())
        {
            afterJson_=std::make_shared<std::string>(r["after_json"].as<std::string>());
        }
        if(!r["detail_json"].isNull())
        {
            detailJson_=std::make_shared<std::string>(r["detail_json"].as<std::string>());
        }
        if(!r["created_at"].isNull())
        {
            auto timeStr = r["created_at"].as<std::string>();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                createdAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
    else
    {
        size_t offset = (size_t)indexOffset;
        if(offset + 14 > r.size())
        {
            LOG_FATAL << "Invalid SQL result for this model";
            return;
        }
        size_t index;
        index = offset + 0;
        if(!r[index].isNull())
        {
            id_=std::make_shared<int64_t>(r[index].as<int64_t>());
        }
        index = offset + 1;
        if(!r[index].isNull())
        {
            auditKey_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 2;
        if(!r[index].isNull())
        {
            txId_=std::make_shared<int64_t>(r[index].as<int64_t>());
        }
        index = offset + 3;
        if(!r[index].isNull())
        {
            projectId_=std::make_shared<int64_t>(r[index].as<int64_t>());
        }
        index = offset + 4;
        if(!r[index].isNull())
        {
            userId_=std::make_shared<int64_t>(r[index].as<int64_t>());
        }
        index = offset + 5;
        if(!r[index].isNull())
        {
            sessionId_=std::make_shared<int64_t>(r[index].as<int64_t>());
        }
        index = offset + 6;
        if(!r[index].isNull())
        {
            objectType_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 7;
        if(!r[index].isNull())
        {
            objectId_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 8;
        if(!r[index].isNull())
        {
            action_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 9;
        if(!r[index].isNull())
        {
            resultCode_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 10;
        if(!r[index].isNull())
        {
            beforeJson_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 11;
        if(!r[index].isNull())
        {
            afterJson_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 12;
        if(!r[index].isNull())
        {
            detailJson_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 13;
        if(!r[index].isNull())
        {
            auto timeStr = r[index].as<std::string>();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                createdAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }

}

AuditLogs::AuditLogs(const Json::Value &pJson, const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 14)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        dirtyFlag_[0] = true;
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            id_=std::make_shared<int64_t>((int64_t)pJson[pMasqueradingVector[0]].asInt64());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        dirtyFlag_[1] = true;
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            auditKey_=std::make_shared<std::string>(pJson[pMasqueradingVector[1]].asString());
        }
    }
    if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
    {
        dirtyFlag_[2] = true;
        if(!pJson[pMasqueradingVector[2]].isNull())
        {
            txId_=std::make_shared<int64_t>((int64_t)pJson[pMasqueradingVector[2]].asInt64());
        }
    }
    if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
    {
        dirtyFlag_[3] = true;
        if(!pJson[pMasqueradingVector[3]].isNull())
        {
            projectId_=std::make_shared<int64_t>((int64_t)pJson[pMasqueradingVector[3]].asInt64());
        }
    }
    if(!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
    {
        dirtyFlag_[4] = true;
        if(!pJson[pMasqueradingVector[4]].isNull())
        {
            userId_=std::make_shared<int64_t>((int64_t)pJson[pMasqueradingVector[4]].asInt64());
        }
    }
    if(!pMasqueradingVector[5].empty() && pJson.isMember(pMasqueradingVector[5]))
    {
        dirtyFlag_[5] = true;
        if(!pJson[pMasqueradingVector[5]].isNull())
        {
            sessionId_=std::make_shared<int64_t>((int64_t)pJson[pMasqueradingVector[5]].asInt64());
        }
    }
    if(!pMasqueradingVector[6].empty() && pJson.isMember(pMasqueradingVector[6]))
    {
        dirtyFlag_[6] = true;
        if(!pJson[pMasqueradingVector[6]].isNull())
        {
            objectType_=std::make_shared<std::string>(pJson[pMasqueradingVector[6]].asString());
        }
    }
    if(!pMasqueradingVector[7].empty() && pJson.isMember(pMasqueradingVector[7]))
    {
        dirtyFlag_[7] = true;
        if(!pJson[pMasqueradingVector[7]].isNull())
        {
            objectId_=std::make_shared<std::string>(pJson[pMasqueradingVector[7]].asString());
        }
    }
    if(!pMasqueradingVector[8].empty() && pJson.isMember(pMasqueradingVector[8]))
    {
        dirtyFlag_[8] = true;
        if(!pJson[pMasqueradingVector[8]].isNull())
        {
            action_=std::make_shared<std::string>(pJson[pMasqueradingVector[8]].asString());
        }
    }
    if(!pMasqueradingVector[9].empty() && pJson.isMember(pMasqueradingVector[9]))
    {
        dirtyFlag_[9] = true;
        if(!pJson[pMasqueradingVector[9]].isNull())
        {
            resultCode_=std::make_shared<std::string>(pJson[pMasqueradingVector[9]].asString());
        }
    }
    if(!pMasqueradingVector[10].empty() && pJson.isMember(pMasqueradingVector[10]))
    {
        dirtyFlag_[10] = true;
        if(!pJson[pMasqueradingVector[10]].isNull())
        {
            beforeJson_=std::make_shared<std::string>(pJson[pMasqueradingVector[10]].asString());
        }
    }
    if(!pMasqueradingVector[11].empty() && pJson.isMember(pMasqueradingVector[11]))
    {
        dirtyFlag_[11] = true;
        if(!pJson[pMasqueradingVector[11]].isNull())
        {
            afterJson_=std::make_shared<std::string>(pJson[pMasqueradingVector[11]].asString());
        }
    }
    if(!pMasqueradingVector[12].empty() && pJson.isMember(pMasqueradingVector[12]))
    {
        dirtyFlag_[12] = true;
        if(!pJson[pMasqueradingVector[12]].isNull())
        {
            detailJson_=std::make_shared<std::string>(pJson[pMasqueradingVector[12]].asString());
        }
    }
    if(!pMasqueradingVector[13].empty() && pJson.isMember(pMasqueradingVector[13]))
    {
        dirtyFlag_[13] = true;
        if(!pJson[pMasqueradingVector[13]].isNull())
        {
            auto timeStr = pJson[pMasqueradingVector[13]].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                createdAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
}

AuditLogs::AuditLogs(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("id"))
    {
        dirtyFlag_[0]=true;
        if(!pJson["id"].isNull())
        {
            id_=std::make_shared<int64_t>((int64_t)pJson["id"].asInt64());
        }
    }
    if(pJson.isMember("audit_key"))
    {
        dirtyFlag_[1]=true;
        if(!pJson["audit_key"].isNull())
        {
            auditKey_=std::make_shared<std::string>(pJson["audit_key"].asString());
        }
    }
    if(pJson.isMember("tx_id"))
    {
        dirtyFlag_[2]=true;
        if(!pJson["tx_id"].isNull())
        {
            txId_=std::make_shared<int64_t>((int64_t)pJson["tx_id"].asInt64());
        }
    }
    if(pJson.isMember("project_id"))
    {
        dirtyFlag_[3]=true;
        if(!pJson["project_id"].isNull())
        {
            projectId_=std::make_shared<int64_t>((int64_t)pJson["project_id"].asInt64());
        }
    }
    if(pJson.isMember("user_id"))
    {
        dirtyFlag_[4]=true;
        if(!pJson["user_id"].isNull())
        {
            userId_=std::make_shared<int64_t>((int64_t)pJson["user_id"].asInt64());
        }
    }
    if(pJson.isMember("session_id"))
    {
        dirtyFlag_[5]=true;
        if(!pJson["session_id"].isNull())
        {
            sessionId_=std::make_shared<int64_t>((int64_t)pJson["session_id"].asInt64());
        }
    }
    if(pJson.isMember("object_type"))
    {
        dirtyFlag_[6]=true;
        if(!pJson["object_type"].isNull())
        {
            objectType_=std::make_shared<std::string>(pJson["object_type"].asString());
        }
    }
    if(pJson.isMember("object_id"))
    {
        dirtyFlag_[7]=true;
        if(!pJson["object_id"].isNull())
        {
            objectId_=std::make_shared<std::string>(pJson["object_id"].asString());
        }
    }
    if(pJson.isMember("action"))
    {
        dirtyFlag_[8]=true;
        if(!pJson["action"].isNull())
        {
            action_=std::make_shared<std::string>(pJson["action"].asString());
        }
    }
    if(pJson.isMember("result_code"))
    {
        dirtyFlag_[9]=true;
        if(!pJson["result_code"].isNull())
        {
            resultCode_=std::make_shared<std::string>(pJson["result_code"].asString());
        }
    }
    if(pJson.isMember("before_json"))
    {
        dirtyFlag_[10]=true;
        if(!pJson["before_json"].isNull())
        {
            beforeJson_=std::make_shared<std::string>(pJson["before_json"].asString());
        }
    }
    if(pJson.isMember("after_json"))
    {
        dirtyFlag_[11]=true;
        if(!pJson["after_json"].isNull())
        {
            afterJson_=std::make_shared<std::string>(pJson["after_json"].asString());
        }
    }
    if(pJson.isMember("detail_json"))
    {
        dirtyFlag_[12]=true;
        if(!pJson["detail_json"].isNull())
        {
            detailJson_=std::make_shared<std::string>(pJson["detail_json"].asString());
        }
    }
    if(pJson.isMember("created_at"))
    {
        dirtyFlag_[13]=true;
        if(!pJson["created_at"].isNull())
        {
            auto timeStr = pJson["created_at"].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                createdAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
}

void AuditLogs::updateByMasqueradedJson(const Json::Value &pJson,
                                            const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 14)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            id_=std::make_shared<int64_t>((int64_t)pJson[pMasqueradingVector[0]].asInt64());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        dirtyFlag_[1] = true;
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            auditKey_=std::make_shared<std::string>(pJson[pMasqueradingVector[1]].asString());
        }
    }
    if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
    {
        dirtyFlag_[2] = true;
        if(!pJson[pMasqueradingVector[2]].isNull())
        {
            txId_=std::make_shared<int64_t>((int64_t)pJson[pMasqueradingVector[2]].asInt64());
        }
    }
    if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
    {
        dirtyFlag_[3] = true;
        if(!pJson[pMasqueradingVector[3]].isNull())
        {
            projectId_=std::make_shared<int64_t>((int64_t)pJson[pMasqueradingVector[3]].asInt64());
        }
    }
    if(!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
    {
        dirtyFlag_[4] = true;
        if(!pJson[pMasqueradingVector[4]].isNull())
        {
            userId_=std::make_shared<int64_t>((int64_t)pJson[pMasqueradingVector[4]].asInt64());
        }
    }
    if(!pMasqueradingVector[5].empty() && pJson.isMember(pMasqueradingVector[5]))
    {
        dirtyFlag_[5] = true;
        if(!pJson[pMasqueradingVector[5]].isNull())
        {
            sessionId_=std::make_shared<int64_t>((int64_t)pJson[pMasqueradingVector[5]].asInt64());
        }
    }
    if(!pMasqueradingVector[6].empty() && pJson.isMember(pMasqueradingVector[6]))
    {
        dirtyFlag_[6] = true;
        if(!pJson[pMasqueradingVector[6]].isNull())
        {
            objectType_=std::make_shared<std::string>(pJson[pMasqueradingVector[6]].asString());
        }
    }
    if(!pMasqueradingVector[7].empty() && pJson.isMember(pMasqueradingVector[7]))
    {
        dirtyFlag_[7] = true;
        if(!pJson[pMasqueradingVector[7]].isNull())
        {
            objectId_=std::make_shared<std::string>(pJson[pMasqueradingVector[7]].asString());
        }
    }
    if(!pMasqueradingVector[8].empty() && pJson.isMember(pMasqueradingVector[8]))
    {
        dirtyFlag_[8] = true;
        if(!pJson[pMasqueradingVector[8]].isNull())
        {
            action_=std::make_shared<std::string>(pJson[pMasqueradingVector[8]].asString());
        }
    }
    if(!pMasqueradingVector[9].empty() && pJson.isMember(pMasqueradingVector[9]))
    {
        dirtyFlag_[9] = true;
        if(!pJson[pMasqueradingVector[9]].isNull())
        {
            resultCode_=std::make_shared<std::string>(pJson[pMasqueradingVector[9]].asString());
        }
    }
    if(!pMasqueradingVector[10].empty() && pJson.isMember(pMasqueradingVector[10]))
    {
        dirtyFlag_[10] = true;
        if(!pJson[pMasqueradingVector[10]].isNull())
        {
            beforeJson_=std::make_shared<std::string>(pJson[pMasqueradingVector[10]].asString());
        }
    }
    if(!pMasqueradingVector[11].empty() && pJson.isMember(pMasqueradingVector[11]))
    {
        dirtyFlag_[11] = true;
        if(!pJson[pMasqueradingVector[11]].isNull())
        {
            afterJson_=std::make_shared<std::string>(pJson[pMasqueradingVector[11]].asString());
        }
    }
    if(!pMasqueradingVector[12].empty() && pJson.isMember(pMasqueradingVector[12]))
    {
        dirtyFlag_[12] = true;
        if(!pJson[pMasqueradingVector[12]].isNull())
        {
            detailJson_=std::make_shared<std::string>(pJson[pMasqueradingVector[12]].asString());
        }
    }
    if(!pMasqueradingVector[13].empty() && pJson.isMember(pMasqueradingVector[13]))
    {
        dirtyFlag_[13] = true;
        if(!pJson[pMasqueradingVector[13]].isNull())
        {
            auto timeStr = pJson[pMasqueradingVector[13]].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                createdAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
}

void AuditLogs::updateByJson(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("id"))
    {
        if(!pJson["id"].isNull())
        {
            id_=std::make_shared<int64_t>((int64_t)pJson["id"].asInt64());
        }
    }
    if(pJson.isMember("audit_key"))
    {
        dirtyFlag_[1] = true;
        if(!pJson["audit_key"].isNull())
        {
            auditKey_=std::make_shared<std::string>(pJson["audit_key"].asString());
        }
    }
    if(pJson.isMember("tx_id"))
    {
        dirtyFlag_[2] = true;
        if(!pJson["tx_id"].isNull())
        {
            txId_=std::make_shared<int64_t>((int64_t)pJson["tx_id"].asInt64());
        }
    }
    if(pJson.isMember("project_id"))
    {
        dirtyFlag_[3] = true;
        if(!pJson["project_id"].isNull())
        {
            projectId_=std::make_shared<int64_t>((int64_t)pJson["project_id"].asInt64());
        }
    }
    if(pJson.isMember("user_id"))
    {
        dirtyFlag_[4] = true;
        if(!pJson["user_id"].isNull())
        {
            userId_=std::make_shared<int64_t>((int64_t)pJson["user_id"].asInt64());
        }
    }
    if(pJson.isMember("session_id"))
    {
        dirtyFlag_[5] = true;
        if(!pJson["session_id"].isNull())
        {
            sessionId_=std::make_shared<int64_t>((int64_t)pJson["session_id"].asInt64());
        }
    }
    if(pJson.isMember("object_type"))
    {
        dirtyFlag_[6] = true;
        if(!pJson["object_type"].isNull())
        {
            objectType_=std::make_shared<std::string>(pJson["object_type"].asString());
        }
    }
    if(pJson.isMember("object_id"))
    {
        dirtyFlag_[7] = true;
        if(!pJson["object_id"].isNull())
        {
            objectId_=std::make_shared<std::string>(pJson["object_id"].asString());
        }
    }
    if(pJson.isMember("action"))
    {
        dirtyFlag_[8] = true;
        if(!pJson["action"].isNull())
        {
            action_=std::make_shared<std::string>(pJson["action"].asString());
        }
    }
    if(pJson.isMember("result_code"))
    {
        dirtyFlag_[9] = true;
        if(!pJson["result_code"].isNull())
        {
            resultCode_=std::make_shared<std::string>(pJson["result_code"].asString());
        }
    }
    if(pJson.isMember("before_json"))
    {
        dirtyFlag_[10] = true;
        if(!pJson["before_json"].isNull())
        {
            beforeJson_=std::make_shared<std::string>(pJson["before_json"].asString());
        }
    }
    if(pJson.isMember("after_json"))
    {
        dirtyFlag_[11] = true;
        if(!pJson["after_json"].isNull())
        {
            afterJson_=std::make_shared<std::string>(pJson["after_json"].asString());
        }
    }
    if(pJson.isMember("detail_json"))
    {
        dirtyFlag_[12] = true;
        if(!pJson["detail_json"].isNull())
        {
            detailJson_=std::make_shared<std::string>(pJson["detail_json"].asString());
        }
    }
    if(pJson.isMember("created_at"))
    {
        dirtyFlag_[13] = true;
        if(!pJson["created_at"].isNull())
        {
            auto timeStr = pJson["created_at"].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                createdAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
}

const int64_t &AuditLogs::getValueOfId() const noexcept
{
    static const int64_t defaultValue = int64_t();
    if(id_)
        return *id_;
    return defaultValue;
}
const std::shared_ptr<int64_t> &AuditLogs::getId() const noexcept
{
    return id_;
}
void AuditLogs::setId(const int64_t &pId) noexcept
{
    id_ = std::make_shared<int64_t>(pId);
    dirtyFlag_[0] = true;
}
const typename AuditLogs::PrimaryKeyType & AuditLogs::getPrimaryKey() const
{
    assert(id_);
    return *id_;
}

const std::string &AuditLogs::getValueOfAuditKey() const noexcept
{
    static const std::string defaultValue = std::string();
    if(auditKey_)
        return *auditKey_;
    return defaultValue;
}
const std::shared_ptr<std::string> &AuditLogs::getAuditKey() const noexcept
{
    return auditKey_;
}
void AuditLogs::setAuditKey(const std::string &pAuditKey) noexcept
{
    auditKey_ = std::make_shared<std::string>(pAuditKey);
    dirtyFlag_[1] = true;
}
void AuditLogs::setAuditKey(std::string &&pAuditKey) noexcept
{
    auditKey_ = std::make_shared<std::string>(std::move(pAuditKey));
    dirtyFlag_[1] = true;
}
void AuditLogs::setAuditKeyToNull() noexcept
{
    auditKey_.reset();
    dirtyFlag_[1] = true;
}

const int64_t &AuditLogs::getValueOfTxId() const noexcept
{
    static const int64_t defaultValue = int64_t();
    if(txId_)
        return *txId_;
    return defaultValue;
}
const std::shared_ptr<int64_t> &AuditLogs::getTxId() const noexcept
{
    return txId_;
}
void AuditLogs::setTxId(const int64_t &pTxId) noexcept
{
    txId_ = std::make_shared<int64_t>(pTxId);
    dirtyFlag_[2] = true;
}
void AuditLogs::setTxIdToNull() noexcept
{
    txId_.reset();
    dirtyFlag_[2] = true;
}

const int64_t &AuditLogs::getValueOfProjectId() const noexcept
{
    static const int64_t defaultValue = int64_t();
    if(projectId_)
        return *projectId_;
    return defaultValue;
}
const std::shared_ptr<int64_t> &AuditLogs::getProjectId() const noexcept
{
    return projectId_;
}
void AuditLogs::setProjectId(const int64_t &pProjectId) noexcept
{
    projectId_ = std::make_shared<int64_t>(pProjectId);
    dirtyFlag_[3] = true;
}
void AuditLogs::setProjectIdToNull() noexcept
{
    projectId_.reset();
    dirtyFlag_[3] = true;
}

const int64_t &AuditLogs::getValueOfUserId() const noexcept
{
    static const int64_t defaultValue = int64_t();
    if(userId_)
        return *userId_;
    return defaultValue;
}
const std::shared_ptr<int64_t> &AuditLogs::getUserId() const noexcept
{
    return userId_;
}
void AuditLogs::setUserId(const int64_t &pUserId) noexcept
{
    userId_ = std::make_shared<int64_t>(pUserId);
    dirtyFlag_[4] = true;
}
void AuditLogs::setUserIdToNull() noexcept
{
    userId_.reset();
    dirtyFlag_[4] = true;
}

const int64_t &AuditLogs::getValueOfSessionId() const noexcept
{
    static const int64_t defaultValue = int64_t();
    if(sessionId_)
        return *sessionId_;
    return defaultValue;
}
const std::shared_ptr<int64_t> &AuditLogs::getSessionId() const noexcept
{
    return sessionId_;
}
void AuditLogs::setSessionId(const int64_t &pSessionId) noexcept
{
    sessionId_ = std::make_shared<int64_t>(pSessionId);
    dirtyFlag_[5] = true;
}
void AuditLogs::setSessionIdToNull() noexcept
{
    sessionId_.reset();
    dirtyFlag_[5] = true;
}

const std::string &AuditLogs::getValueOfObjectType() const noexcept
{
    static const std::string defaultValue = std::string();
    if(objectType_)
        return *objectType_;
    return defaultValue;
}
const std::shared_ptr<std::string> &AuditLogs::getObjectType() const noexcept
{
    return objectType_;
}
void AuditLogs::setObjectType(const std::string &pObjectType) noexcept
{
    objectType_ = std::make_shared<std::string>(pObjectType);
    dirtyFlag_[6] = true;
}
void AuditLogs::setObjectType(std::string &&pObjectType) noexcept
{
    objectType_ = std::make_shared<std::string>(std::move(pObjectType));
    dirtyFlag_[6] = true;
}
void AuditLogs::setObjectTypeToNull() noexcept
{
    objectType_.reset();
    dirtyFlag_[6] = true;
}

const std::string &AuditLogs::getValueOfObjectId() const noexcept
{
    static const std::string defaultValue = std::string();
    if(objectId_)
        return *objectId_;
    return defaultValue;
}
const std::shared_ptr<std::string> &AuditLogs::getObjectId() const noexcept
{
    return objectId_;
}
void AuditLogs::setObjectId(const std::string &pObjectId) noexcept
{
    objectId_ = std::make_shared<std::string>(pObjectId);
    dirtyFlag_[7] = true;
}
void AuditLogs::setObjectId(std::string &&pObjectId) noexcept
{
    objectId_ = std::make_shared<std::string>(std::move(pObjectId));
    dirtyFlag_[7] = true;
}
void AuditLogs::setObjectIdToNull() noexcept
{
    objectId_.reset();
    dirtyFlag_[7] = true;
}

const std::string &AuditLogs::getValueOfAction() const noexcept
{
    static const std::string defaultValue = std::string();
    if(action_)
        return *action_;
    return defaultValue;
}
const std::shared_ptr<std::string> &AuditLogs::getAction() const noexcept
{
    return action_;
}
void AuditLogs::setAction(const std::string &pAction) noexcept
{
    action_ = std::make_shared<std::string>(pAction);
    dirtyFlag_[8] = true;
}
void AuditLogs::setAction(std::string &&pAction) noexcept
{
    action_ = std::make_shared<std::string>(std::move(pAction));
    dirtyFlag_[8] = true;
}

const std::string &AuditLogs::getValueOfResultCode() const noexcept
{
    static const std::string defaultValue = std::string();
    if(resultCode_)
        return *resultCode_;
    return defaultValue;
}
const std::shared_ptr<std::string> &AuditLogs::getResultCode() const noexcept
{
    return resultCode_;
}
void AuditLogs::setResultCode(const std::string &pResultCode) noexcept
{
    resultCode_ = std::make_shared<std::string>(pResultCode);
    dirtyFlag_[9] = true;
}
void AuditLogs::setResultCode(std::string &&pResultCode) noexcept
{
    resultCode_ = std::make_shared<std::string>(std::move(pResultCode));
    dirtyFlag_[9] = true;
}
void AuditLogs::setResultCodeToNull() noexcept
{
    resultCode_.reset();
    dirtyFlag_[9] = true;
}

const std::string &AuditLogs::getValueOfBeforeJson() const noexcept
{
    static const std::string defaultValue = std::string();
    if(beforeJson_)
        return *beforeJson_;
    return defaultValue;
}
const std::shared_ptr<std::string> &AuditLogs::getBeforeJson() const noexcept
{
    return beforeJson_;
}
void AuditLogs::setBeforeJson(const std::string &pBeforeJson) noexcept
{
    beforeJson_ = std::make_shared<std::string>(pBeforeJson);
    dirtyFlag_[10] = true;
}
void AuditLogs::setBeforeJson(std::string &&pBeforeJson) noexcept
{
    beforeJson_ = std::make_shared<std::string>(std::move(pBeforeJson));
    dirtyFlag_[10] = true;
}
void AuditLogs::setBeforeJsonToNull() noexcept
{
    beforeJson_.reset();
    dirtyFlag_[10] = true;
}

const std::string &AuditLogs::getValueOfAfterJson() const noexcept
{
    static const std::string defaultValue = std::string();
    if(afterJson_)
        return *afterJson_;
    return defaultValue;
}
const std::shared_ptr<std::string> &AuditLogs::getAfterJson() const noexcept
{
    return afterJson_;
}
void AuditLogs::setAfterJson(const std::string &pAfterJson) noexcept
{
    afterJson_ = std::make_shared<std::string>(pAfterJson);
    dirtyFlag_[11] = true;
}
void AuditLogs::setAfterJson(std::string &&pAfterJson) noexcept
{
    afterJson_ = std::make_shared<std::string>(std::move(pAfterJson));
    dirtyFlag_[11] = true;
}
void AuditLogs::setAfterJsonToNull() noexcept
{
    afterJson_.reset();
    dirtyFlag_[11] = true;
}

const std::string &AuditLogs::getValueOfDetailJson() const noexcept
{
    static const std::string defaultValue = std::string();
    if(detailJson_)
        return *detailJson_;
    return defaultValue;
}
const std::shared_ptr<std::string> &AuditLogs::getDetailJson() const noexcept
{
    return detailJson_;
}
void AuditLogs::setDetailJson(const std::string &pDetailJson) noexcept
{
    detailJson_ = std::make_shared<std::string>(pDetailJson);
    dirtyFlag_[12] = true;
}
void AuditLogs::setDetailJson(std::string &&pDetailJson) noexcept
{
    detailJson_ = std::make_shared<std::string>(std::move(pDetailJson));
    dirtyFlag_[12] = true;
}
void AuditLogs::setDetailJsonToNull() noexcept
{
    detailJson_.reset();
    dirtyFlag_[12] = true;
}

const ::trantor::Date &AuditLogs::getValueOfCreatedAt() const noexcept
{
    static const ::trantor::Date defaultValue = ::trantor::Date();
    if(createdAt_)
        return *createdAt_;
    return defaultValue;
}
const std::shared_ptr<::trantor::Date> &AuditLogs::getCreatedAt() const noexcept
{
    return createdAt_;
}
void AuditLogs::setCreatedAt(const ::trantor::Date &pCreatedAt) noexcept
{
    createdAt_ = std::make_shared<::trantor::Date>(pCreatedAt);
    dirtyFlag_[13] = true;
}

void AuditLogs::updateId(const uint64_t id)
{
}

const std::vector<std::string> &AuditLogs::insertColumns() noexcept
{
    static const std::vector<std::string> inCols={
        "audit_key",
        "tx_id",
        "project_id",
        "user_id",
        "session_id",
        "object_type",
        "object_id",
        "action",
        "result_code",
        "before_json",
        "after_json",
        "detail_json",
        "created_at"
    };
    return inCols;
}

void AuditLogs::outputArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[1])
    {
        if(getAuditKey())
        {
            binder << getValueOfAuditKey();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[2])
    {
        if(getTxId())
        {
            binder << getValueOfTxId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[3])
    {
        if(getProjectId())
        {
            binder << getValueOfProjectId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[4])
    {
        if(getUserId())
        {
            binder << getValueOfUserId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[5])
    {
        if(getSessionId())
        {
            binder << getValueOfSessionId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[6])
    {
        if(getObjectType())
        {
            binder << getValueOfObjectType();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[7])
    {
        if(getObjectId())
        {
            binder << getValueOfObjectId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[8])
    {
        if(getAction())
        {
            binder << getValueOfAction();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[9])
    {
        if(getResultCode())
        {
            binder << getValueOfResultCode();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[10])
    {
        if(getBeforeJson())
        {
            binder << getValueOfBeforeJson();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[11])
    {
        if(getAfterJson())
        {
            binder << getValueOfAfterJson();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[12])
    {
        if(getDetailJson())
        {
            binder << getValueOfDetailJson();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[13])
    {
        if(getCreatedAt())
        {
            binder << getValueOfCreatedAt();
        }
        else
        {
            binder << nullptr;
        }
    }
}

const std::vector<std::string> AuditLogs::updateColumns() const
{
    std::vector<std::string> ret;
    if(dirtyFlag_[1])
    {
        ret.push_back(getColumnName(1));
    }
    if(dirtyFlag_[2])
    {
        ret.push_back(getColumnName(2));
    }
    if(dirtyFlag_[3])
    {
        ret.push_back(getColumnName(3));
    }
    if(dirtyFlag_[4])
    {
        ret.push_back(getColumnName(4));
    }
    if(dirtyFlag_[5])
    {
        ret.push_back(getColumnName(5));
    }
    if(dirtyFlag_[6])
    {
        ret.push_back(getColumnName(6));
    }
    if(dirtyFlag_[7])
    {
        ret.push_back(getColumnName(7));
    }
    if(dirtyFlag_[8])
    {
        ret.push_back(getColumnName(8));
    }
    if(dirtyFlag_[9])
    {
        ret.push_back(getColumnName(9));
    }
    if(dirtyFlag_[10])
    {
        ret.push_back(getColumnName(10));
    }
    if(dirtyFlag_[11])
    {
        ret.push_back(getColumnName(11));
    }
    if(dirtyFlag_[12])
    {
        ret.push_back(getColumnName(12));
    }
    if(dirtyFlag_[13])
    {
        ret.push_back(getColumnName(13));
    }
    return ret;
}

void AuditLogs::updateArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[1])
    {
        if(getAuditKey())
        {
            binder << getValueOfAuditKey();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[2])
    {
        if(getTxId())
        {
            binder << getValueOfTxId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[3])
    {
        if(getProjectId())
        {
            binder << getValueOfProjectId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[4])
    {
        if(getUserId())
        {
            binder << getValueOfUserId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[5])
    {
        if(getSessionId())
        {
            binder << getValueOfSessionId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[6])
    {
        if(getObjectType())
        {
            binder << getValueOfObjectType();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[7])
    {
        if(getObjectId())
        {
            binder << getValueOfObjectId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[8])
    {
        if(getAction())
        {
            binder << getValueOfAction();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[9])
    {
        if(getResultCode())
        {
            binder << getValueOfResultCode();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[10])
    {
        if(getBeforeJson())
        {
            binder << getValueOfBeforeJson();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[11])
    {
        if(getAfterJson())
        {
            binder << getValueOfAfterJson();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[12])
    {
        if(getDetailJson())
        {
            binder << getValueOfDetailJson();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[13])
    {
        if(getCreatedAt())
        {
            binder << getValueOfCreatedAt();
        }
        else
        {
            binder << nullptr;
        }
    }
}
Json::Value AuditLogs::toJson() const
{
    Json::Value ret;
    if(getId())
    {
        ret["id"]=(Json::Int64)getValueOfId();
    }
    else
    {
        ret["id"]=Json::Value();
    }
    if(getAuditKey())
    {
        ret["audit_key"]=getValueOfAuditKey();
    }
    else
    {
        ret["audit_key"]=Json::Value();
    }
    if(getTxId())
    {
        ret["tx_id"]=(Json::Int64)getValueOfTxId();
    }
    else
    {
        ret["tx_id"]=Json::Value();
    }
    if(getProjectId())
    {
        ret["project_id"]=(Json::Int64)getValueOfProjectId();
    }
    else
    {
        ret["project_id"]=Json::Value();
    }
    if(getUserId())
    {
        ret["user_id"]=(Json::Int64)getValueOfUserId();
    }
    else
    {
        ret["user_id"]=Json::Value();
    }
    if(getSessionId())
    {
        ret["session_id"]=(Json::Int64)getValueOfSessionId();
    }
    else
    {
        ret["session_id"]=Json::Value();
    }
    if(getObjectType())
    {
        ret["object_type"]=getValueOfObjectType();
    }
    else
    {
        ret["object_type"]=Json::Value();
    }
    if(getObjectId())
    {
        ret["object_id"]=getValueOfObjectId();
    }
    else
    {
        ret["object_id"]=Json::Value();
    }
    if(getAction())
    {
        ret["action"]=getValueOfAction();
    }
    else
    {
        ret["action"]=Json::Value();
    }
    if(getResultCode())
    {
        ret["result_code"]=getValueOfResultCode();
    }
    else
    {
        ret["result_code"]=Json::Value();
    }
    if(getBeforeJson())
    {
        ret["before_json"]=getValueOfBeforeJson();
    }
    else
    {
        ret["before_json"]=Json::Value();
    }
    if(getAfterJson())
    {
        ret["after_json"]=getValueOfAfterJson();
    }
    else
    {
        ret["after_json"]=Json::Value();
    }
    if(getDetailJson())
    {
        ret["detail_json"]=getValueOfDetailJson();
    }
    else
    {
        ret["detail_json"]=Json::Value();
    }
    if(getCreatedAt())
    {
        ret["created_at"]=getCreatedAt()->toDbStringLocal();
    }
    else
    {
        ret["created_at"]=Json::Value();
    }
    return ret;
}

std::string AuditLogs::toString() const
{
    return toJson().toStyledString();
}

Json::Value AuditLogs::toMasqueradedJson(
    const std::vector<std::string> &pMasqueradingVector) const
{
    Json::Value ret;
    if(pMasqueradingVector.size() == 14)
    {
        if(!pMasqueradingVector[0].empty())
        {
            if(getId())
            {
                ret[pMasqueradingVector[0]]=(Json::Int64)getValueOfId();
            }
            else
            {
                ret[pMasqueradingVector[0]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[1].empty())
        {
            if(getAuditKey())
            {
                ret[pMasqueradingVector[1]]=getValueOfAuditKey();
            }
            else
            {
                ret[pMasqueradingVector[1]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[2].empty())
        {
            if(getTxId())
            {
                ret[pMasqueradingVector[2]]=(Json::Int64)getValueOfTxId();
            }
            else
            {
                ret[pMasqueradingVector[2]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[3].empty())
        {
            if(getProjectId())
            {
                ret[pMasqueradingVector[3]]=(Json::Int64)getValueOfProjectId();
            }
            else
            {
                ret[pMasqueradingVector[3]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[4].empty())
        {
            if(getUserId())
            {
                ret[pMasqueradingVector[4]]=(Json::Int64)getValueOfUserId();
            }
            else
            {
                ret[pMasqueradingVector[4]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[5].empty())
        {
            if(getSessionId())
            {
                ret[pMasqueradingVector[5]]=(Json::Int64)getValueOfSessionId();
            }
            else
            {
                ret[pMasqueradingVector[5]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[6].empty())
        {
            if(getObjectType())
            {
                ret[pMasqueradingVector[6]]=getValueOfObjectType();
            }
            else
            {
                ret[pMasqueradingVector[6]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[7].empty())
        {
            if(getObjectId())
            {
                ret[pMasqueradingVector[7]]=getValueOfObjectId();
            }
            else
            {
                ret[pMasqueradingVector[7]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[8].empty())
        {
            if(getAction())
            {
                ret[pMasqueradingVector[8]]=getValueOfAction();
            }
            else
            {
                ret[pMasqueradingVector[8]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[9].empty())
        {
            if(getResultCode())
            {
                ret[pMasqueradingVector[9]]=getValueOfResultCode();
            }
            else
            {
                ret[pMasqueradingVector[9]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[10].empty())
        {
            if(getBeforeJson())
            {
                ret[pMasqueradingVector[10]]=getValueOfBeforeJson();
            }
            else
            {
                ret[pMasqueradingVector[10]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[11].empty())
        {
            if(getAfterJson())
            {
                ret[pMasqueradingVector[11]]=getValueOfAfterJson();
            }
            else
            {
                ret[pMasqueradingVector[11]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[12].empty())
        {
            if(getDetailJson())
            {
                ret[pMasqueradingVector[12]]=getValueOfDetailJson();
            }
            else
            {
                ret[pMasqueradingVector[12]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[13].empty())
        {
            if(getCreatedAt())
            {
                ret[pMasqueradingVector[13]]=getCreatedAt()->toDbStringLocal();
            }
            else
            {
                ret[pMasqueradingVector[13]]=Json::Value();
            }
        }
        return ret;
    }
    LOG_ERROR << "Masquerade failed";
    if(getId())
    {
        ret["id"]=(Json::Int64)getValueOfId();
    }
    else
    {
        ret["id"]=Json::Value();
    }
    if(getAuditKey())
    {
        ret["audit_key"]=getValueOfAuditKey();
    }
    else
    {
        ret["audit_key"]=Json::Value();
    }
    if(getTxId())
    {
        ret["tx_id"]=(Json::Int64)getValueOfTxId();
    }
    else
    {
        ret["tx_id"]=Json::Value();
    }
    if(getProjectId())
    {
        ret["project_id"]=(Json::Int64)getValueOfProjectId();
    }
    else
    {
        ret["project_id"]=Json::Value();
    }
    if(getUserId())
    {
        ret["user_id"]=(Json::Int64)getValueOfUserId();
    }
    else
    {
        ret["user_id"]=Json::Value();
    }
    if(getSessionId())
    {
        ret["session_id"]=(Json::Int64)getValueOfSessionId();
    }
    else
    {
        ret["session_id"]=Json::Value();
    }
    if(getObjectType())
    {
        ret["object_type"]=getValueOfObjectType();
    }
    else
    {
        ret["object_type"]=Json::Value();
    }
    if(getObjectId())
    {
        ret["object_id"]=getValueOfObjectId();
    }
    else
    {
        ret["object_id"]=Json::Value();
    }
    if(getAction())
    {
        ret["action"]=getValueOfAction();
    }
    else
    {
        ret["action"]=Json::Value();
    }
    if(getResultCode())
    {
        ret["result_code"]=getValueOfResultCode();
    }
    else
    {
        ret["result_code"]=Json::Value();
    }
    if(getBeforeJson())
    {
        ret["before_json"]=getValueOfBeforeJson();
    }
    else
    {
        ret["before_json"]=Json::Value();
    }
    if(getAfterJson())
    {
        ret["after_json"]=getValueOfAfterJson();
    }
    else
    {
        ret["after_json"]=Json::Value();
    }
    if(getDetailJson())
    {
        ret["detail_json"]=getValueOfDetailJson();
    }
    else
    {
        ret["detail_json"]=Json::Value();
    }
    if(getCreatedAt())
    {
        ret["created_at"]=getCreatedAt()->toDbStringLocal();
    }
    else
    {
        ret["created_at"]=Json::Value();
    }
    return ret;
}

bool AuditLogs::validateJsonForCreation(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("id"))
    {
        if(!validJsonOfField(0, "id", pJson["id"], err, true))
            return false;
    }
    if(pJson.isMember("audit_key"))
    {
        if(!validJsonOfField(1, "audit_key", pJson["audit_key"], err, true))
            return false;
    }
    if(pJson.isMember("tx_id"))
    {
        if(!validJsonOfField(2, "tx_id", pJson["tx_id"], err, true))
            return false;
    }
    if(pJson.isMember("project_id"))
    {
        if(!validJsonOfField(3, "project_id", pJson["project_id"], err, true))
            return false;
    }
    if(pJson.isMember("user_id"))
    {
        if(!validJsonOfField(4, "user_id", pJson["user_id"], err, true))
            return false;
    }
    if(pJson.isMember("session_id"))
    {
        if(!validJsonOfField(5, "session_id", pJson["session_id"], err, true))
            return false;
    }
    if(pJson.isMember("object_type"))
    {
        if(!validJsonOfField(6, "object_type", pJson["object_type"], err, true))
            return false;
    }
    if(pJson.isMember("object_id"))
    {
        if(!validJsonOfField(7, "object_id", pJson["object_id"], err, true))
            return false;
    }
    if(pJson.isMember("action"))
    {
        if(!validJsonOfField(8, "action", pJson["action"], err, true))
            return false;
    }
    else
    {
        err="The action column cannot be null";
        return false;
    }
    if(pJson.isMember("result_code"))
    {
        if(!validJsonOfField(9, "result_code", pJson["result_code"], err, true))
            return false;
    }
    if(pJson.isMember("before_json"))
    {
        if(!validJsonOfField(10, "before_json", pJson["before_json"], err, true))
            return false;
    }
    if(pJson.isMember("after_json"))
    {
        if(!validJsonOfField(11, "after_json", pJson["after_json"], err, true))
            return false;
    }
    if(pJson.isMember("detail_json"))
    {
        if(!validJsonOfField(12, "detail_json", pJson["detail_json"], err, true))
            return false;
    }
    if(pJson.isMember("created_at"))
    {
        if(!validJsonOfField(13, "created_at", pJson["created_at"], err, true))
            return false;
    }
    return true;
}
bool AuditLogs::validateMasqueradedJsonForCreation(const Json::Value &pJson,
                                                   const std::vector<std::string> &pMasqueradingVector,
                                                   std::string &err)
{
    if(pMasqueradingVector.size() != 14)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty())
      {
          if(pJson.isMember(pMasqueradingVector[0]))
          {
              if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[1].empty())
      {
          if(pJson.isMember(pMasqueradingVector[1]))
          {
              if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[2].empty())
      {
          if(pJson.isMember(pMasqueradingVector[2]))
          {
              if(!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[3].empty())
      {
          if(pJson.isMember(pMasqueradingVector[3]))
          {
              if(!validJsonOfField(3, pMasqueradingVector[3], pJson[pMasqueradingVector[3]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[4].empty())
      {
          if(pJson.isMember(pMasqueradingVector[4]))
          {
              if(!validJsonOfField(4, pMasqueradingVector[4], pJson[pMasqueradingVector[4]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[5].empty())
      {
          if(pJson.isMember(pMasqueradingVector[5]))
          {
              if(!validJsonOfField(5, pMasqueradingVector[5], pJson[pMasqueradingVector[5]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[6].empty())
      {
          if(pJson.isMember(pMasqueradingVector[6]))
          {
              if(!validJsonOfField(6, pMasqueradingVector[6], pJson[pMasqueradingVector[6]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[7].empty())
      {
          if(pJson.isMember(pMasqueradingVector[7]))
          {
              if(!validJsonOfField(7, pMasqueradingVector[7], pJson[pMasqueradingVector[7]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[8].empty())
      {
          if(pJson.isMember(pMasqueradingVector[8]))
          {
              if(!validJsonOfField(8, pMasqueradingVector[8], pJson[pMasqueradingVector[8]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[8] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[9].empty())
      {
          if(pJson.isMember(pMasqueradingVector[9]))
          {
              if(!validJsonOfField(9, pMasqueradingVector[9], pJson[pMasqueradingVector[9]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[10].empty())
      {
          if(pJson.isMember(pMasqueradingVector[10]))
          {
              if(!validJsonOfField(10, pMasqueradingVector[10], pJson[pMasqueradingVector[10]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[11].empty())
      {
          if(pJson.isMember(pMasqueradingVector[11]))
          {
              if(!validJsonOfField(11, pMasqueradingVector[11], pJson[pMasqueradingVector[11]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[12].empty())
      {
          if(pJson.isMember(pMasqueradingVector[12]))
          {
              if(!validJsonOfField(12, pMasqueradingVector[12], pJson[pMasqueradingVector[12]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[13].empty())
      {
          if(pJson.isMember(pMasqueradingVector[13]))
          {
              if(!validJsonOfField(13, pMasqueradingVector[13], pJson[pMasqueradingVector[13]], err, true))
                  return false;
          }
      }
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool AuditLogs::validateJsonForUpdate(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("id"))
    {
        if(!validJsonOfField(0, "id", pJson["id"], err, false))
            return false;
    }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
    if(pJson.isMember("audit_key"))
    {
        if(!validJsonOfField(1, "audit_key", pJson["audit_key"], err, false))
            return false;
    }
    if(pJson.isMember("tx_id"))
    {
        if(!validJsonOfField(2, "tx_id", pJson["tx_id"], err, false))
            return false;
    }
    if(pJson.isMember("project_id"))
    {
        if(!validJsonOfField(3, "project_id", pJson["project_id"], err, false))
            return false;
    }
    if(pJson.isMember("user_id"))
    {
        if(!validJsonOfField(4, "user_id", pJson["user_id"], err, false))
            return false;
    }
    if(pJson.isMember("session_id"))
    {
        if(!validJsonOfField(5, "session_id", pJson["session_id"], err, false))
            return false;
    }
    if(pJson.isMember("object_type"))
    {
        if(!validJsonOfField(6, "object_type", pJson["object_type"], err, false))
            return false;
    }
    if(pJson.isMember("object_id"))
    {
        if(!validJsonOfField(7, "object_id", pJson["object_id"], err, false))
            return false;
    }
    if(pJson.isMember("action"))
    {
        if(!validJsonOfField(8, "action", pJson["action"], err, false))
            return false;
    }
    if(pJson.isMember("result_code"))
    {
        if(!validJsonOfField(9, "result_code", pJson["result_code"], err, false))
            return false;
    }
    if(pJson.isMember("before_json"))
    {
        if(!validJsonOfField(10, "before_json", pJson["before_json"], err, false))
            return false;
    }
    if(pJson.isMember("after_json"))
    {
        if(!validJsonOfField(11, "after_json", pJson["after_json"], err, false))
            return false;
    }
    if(pJson.isMember("detail_json"))
    {
        if(!validJsonOfField(12, "detail_json", pJson["detail_json"], err, false))
            return false;
    }
    if(pJson.isMember("created_at"))
    {
        if(!validJsonOfField(13, "created_at", pJson["created_at"], err, false))
            return false;
    }
    return true;
}
bool AuditLogs::validateMasqueradedJsonForUpdate(const Json::Value &pJson,
                                                 const std::vector<std::string> &pMasqueradingVector,
                                                 std::string &err)
{
    if(pMasqueradingVector.size() != 14)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
      {
          if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, false))
              return false;
      }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
      if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
      {
          if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, false))
              return false;
      }
      if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
      {
          if(!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err, false))
              return false;
      }
      if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
      {
          if(!validJsonOfField(3, pMasqueradingVector[3], pJson[pMasqueradingVector[3]], err, false))
              return false;
      }
      if(!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
      {
          if(!validJsonOfField(4, pMasqueradingVector[4], pJson[pMasqueradingVector[4]], err, false))
              return false;
      }
      if(!pMasqueradingVector[5].empty() && pJson.isMember(pMasqueradingVector[5]))
      {
          if(!validJsonOfField(5, pMasqueradingVector[5], pJson[pMasqueradingVector[5]], err, false))
              return false;
      }
      if(!pMasqueradingVector[6].empty() && pJson.isMember(pMasqueradingVector[6]))
      {
          if(!validJsonOfField(6, pMasqueradingVector[6], pJson[pMasqueradingVector[6]], err, false))
              return false;
      }
      if(!pMasqueradingVector[7].empty() && pJson.isMember(pMasqueradingVector[7]))
      {
          if(!validJsonOfField(7, pMasqueradingVector[7], pJson[pMasqueradingVector[7]], err, false))
              return false;
      }
      if(!pMasqueradingVector[8].empty() && pJson.isMember(pMasqueradingVector[8]))
      {
          if(!validJsonOfField(8, pMasqueradingVector[8], pJson[pMasqueradingVector[8]], err, false))
              return false;
      }
      if(!pMasqueradingVector[9].empty() && pJson.isMember(pMasqueradingVector[9]))
      {
          if(!validJsonOfField(9, pMasqueradingVector[9], pJson[pMasqueradingVector[9]], err, false))
              return false;
      }
      if(!pMasqueradingVector[10].empty() && pJson.isMember(pMasqueradingVector[10]))
      {
          if(!validJsonOfField(10, pMasqueradingVector[10], pJson[pMasqueradingVector[10]], err, false))
              return false;
      }
      if(!pMasqueradingVector[11].empty() && pJson.isMember(pMasqueradingVector[11]))
      {
          if(!validJsonOfField(11, pMasqueradingVector[11], pJson[pMasqueradingVector[11]], err, false))
              return false;
      }
      if(!pMasqueradingVector[12].empty() && pJson.isMember(pMasqueradingVector[12]))
      {
          if(!validJsonOfField(12, pMasqueradingVector[12], pJson[pMasqueradingVector[12]], err, false))
              return false;
      }
      if(!pMasqueradingVector[13].empty() && pJson.isMember(pMasqueradingVector[13]))
      {
          if(!validJsonOfField(13, pMasqueradingVector[13], pJson[pMasqueradingVector[13]], err, false))
              return false;
      }
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool AuditLogs::validJsonOfField(size_t index,
                                 const std::string &fieldName,
                                 const Json::Value &pJson,
                                 std::string &err,
                                 bool isForCreation)
{
    switch(index)
    {
        case 0:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(isForCreation)
            {
                err="The automatic primary key cannot be set";
                return false;
            }
            if(!pJson.isInt64())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 1:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            if(pJson.isString() && std::wstring_convert<std::codecvt_utf8_utf16<wchar_t>, wchar_t>{}
                .from_bytes(pJson.asCString()).size() > 128)
            {
                err="String length exceeds limit for the " +
                    fieldName +
                    " field (the maximum value is 128)";
                return false;
            }
            break;
        case 2:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isInt64())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 3:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isInt64())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 4:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isInt64())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 5:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isInt64())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 6:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            if(pJson.isString() && std::wstring_convert<std::codecvt_utf8_utf16<wchar_t>, wchar_t>{}
                .from_bytes(pJson.asCString()).size() > 128)
            {
                err="String length exceeds limit for the " +
                    fieldName +
                    " field (the maximum value is 128)";
                return false;
            }
            break;
        case 7:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            if(pJson.isString() && std::wstring_convert<std::codecvt_utf8_utf16<wchar_t>, wchar_t>{}
                .from_bytes(pJson.asCString()).size() > 128)
            {
                err="String length exceeds limit for the " +
                    fieldName +
                    " field (the maximum value is 128)";
                return false;
            }
            break;
        case 8:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            if(pJson.isString() && std::wstring_convert<std::codecvt_utf8_utf16<wchar_t>, wchar_t>{}
                .from_bytes(pJson.asCString()).size() > 64)
            {
                err="String length exceeds limit for the " +
                    fieldName +
                    " field (the maximum value is 64)";
                return false;
            }
            break;
        case 9:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            if(pJson.isString() && std::wstring_convert<std::codecvt_utf8_utf16<wchar_t>, wchar_t>{}
                .from_bytes(pJson.asCString()).size() > 32)
            {
                err="String length exceeds limit for the " +
                    fieldName +
                    " field (the maximum value is 32)";
                return false;
            }
            break;
        case 10:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 11:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 12:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 13:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        default:
            err="Internal error in the server";
            return false;
    }
    return true;
}
