/**
 *
 *  ProjectDatabases.cc
 *  DO NOT EDIT. This file is generated by drogon_ctl
 *
 */

#include "ProjectDatabases.h"
#include "Projects.h"
#include <drogon/utils/Utilities.h>
#include <codecvt>
#include <string>

using namespace drogon;
using namespace drogon::orm;
using namespace drogon_model::UELocalDB::core;

const std::string ProjectDatabases::Cols::_id = "\"id\"";
const std::string ProjectDatabases::Cols::_project_id = "\"project_id\"";
const std::string ProjectDatabases::Cols::_template_kind = "\"template_kind\"";
const std::string ProjectDatabases::Cols::_scope_type = "\"scope_type\"";
const std::string ProjectDatabases::Cols::_source_name = "\"source_name\"";
const std::string ProjectDatabases::Cols::_source_path = "\"source_path\"";
const std::string ProjectDatabases::Cols::_db_version = "\"db_version\"";
const std::string ProjectDatabases::Cols::_is_enabled = "\"is_enabled\"";
const std::string ProjectDatabases::Cols::_created_at = "\"created_at\"";
const std::string ProjectDatabases::Cols::_updated_at = "\"updated_at\"";
const std::string ProjectDatabases::primaryKeyName = "id";
const bool ProjectDatabases::hasPrimaryKey = true;
const std::string ProjectDatabases::tableName = "core.\"project_databases\"";

const std::vector<typename ProjectDatabases::MetaData> ProjectDatabases::metaData_={
{"id","int64_t","bigint",8,1,1,1},
{"project_id","int64_t","bigint",8,0,0,0},
{"template_kind","std::string","character varying",64,0,0,1},
{"scope_type","std::string","character varying",16,0,0,1},
{"source_name","std::string","character varying",256,0,0,0},
{"source_path","std::string","text",0,0,0,0},
{"db_version","std::string","character varying",64,0,0,0},
{"is_enabled","bool","boolean",1,0,0,1},
{"created_at","::trantor::Date","timestamp without time zone",0,0,0,1},
{"updated_at","::trantor::Date","timestamp without time zone",0,0,0,1}
};
const std::string &ProjectDatabases::getColumnName(size_t index) noexcept(false)
{
    assert(index < metaData_.size());
    return metaData_[index].colName_;
}
ProjectDatabases::ProjectDatabases(const Row &r, const ssize_t indexOffset) noexcept
{
    if(indexOffset < 0)
    {
        if(!r["id"].isNull())
        {
            id_=std::make_shared<int64_t>(r["id"].as<int64_t>());
        }
        if(!r["project_id"].isNull())
        {
            projectId_=std::make_shared<int64_t>(r["project_id"].as<int64_t>());
        }
        if(!r["template_kind"].isNull())
        {
            templateKind_=std::make_shared<std::string>(r["template_kind"].as<std::string>());
        }
        if(!r["scope_type"].isNull())
        {
            scopeType_=std::make_shared<std::string>(r["scope_type"].as<std::string>());
        }
        if(!r["source_name"].isNull())
        {
            sourceName_=std::make_shared<std::string>(r["source_name"].as<std::string>());
        }
        if(!r["source_path"].isNull())
        {
            sourcePath_=std::make_shared<std::string>(r["source_path"].as<std::string>());
        }
        if(!r["db_version"].isNull())
        {
            dbVersion_=std::make_shared<std::string>(r["db_version"].as<std::string>());
        }
        if(!r["is_enabled"].isNull())
        {
            isEnabled_=std::make_shared<bool>(r["is_enabled"].as<bool>());
        }
        if(!r["created_at"].isNull())
        {
            auto timeStr = r["created_at"].as<std::string>();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                createdAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
        if(!r["updated_at"].isNull())
        {
            auto timeStr = r["updated_at"].as<std::string>();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                updatedAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
    else
    {
        size_t offset = (size_t)indexOffset;
        if(offset + 10 > r.size())
        {
            LOG_FATAL << "Invalid SQL result for this model";
            return;
        }
        size_t index;
        index = offset + 0;
        if(!r[index].isNull())
        {
            id_=std::make_shared<int64_t>(r[index].as<int64_t>());
        }
        index = offset + 1;
        if(!r[index].isNull())
        {
            projectId_=std::make_shared<int64_t>(r[index].as<int64_t>());
        }
        index = offset + 2;
        if(!r[index].isNull())
        {
            templateKind_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 3;
        if(!r[index].isNull())
        {
            scopeType_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 4;
        if(!r[index].isNull())
        {
            sourceName_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 5;
        if(!r[index].isNull())
        {
            sourcePath_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 6;
        if(!r[index].isNull())
        {
            dbVersion_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 7;
        if(!r[index].isNull())
        {
            isEnabled_=std::make_shared<bool>(r[index].as<bool>());
        }
        index = offset + 8;
        if(!r[index].isNull())
        {
            auto timeStr = r[index].as<std::string>();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                createdAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
        index = offset + 9;
        if(!r[index].isNull())
        {
            auto timeStr = r[index].as<std::string>();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                updatedAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }

}

ProjectDatabases::ProjectDatabases(const Json::Value &pJson, const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 10)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        dirtyFlag_[0] = true;
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            id_=std::make_shared<int64_t>((int64_t)pJson[pMasqueradingVector[0]].asInt64());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        dirtyFlag_[1] = true;
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            projectId_=std::make_shared<int64_t>((int64_t)pJson[pMasqueradingVector[1]].asInt64());
        }
    }
    if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
    {
        dirtyFlag_[2] = true;
        if(!pJson[pMasqueradingVector[2]].isNull())
        {
            templateKind_=std::make_shared<std::string>(pJson[pMasqueradingVector[2]].asString());
        }
    }
    if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
    {
        dirtyFlag_[3] = true;
        if(!pJson[pMasqueradingVector[3]].isNull())
        {
            scopeType_=std::make_shared<std::string>(pJson[pMasqueradingVector[3]].asString());
        }
    }
    if(!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
    {
        dirtyFlag_[4] = true;
        if(!pJson[pMasqueradingVector[4]].isNull())
        {
            sourceName_=std::make_shared<std::string>(pJson[pMasqueradingVector[4]].asString());
        }
    }
    if(!pMasqueradingVector[5].empty() && pJson.isMember(pMasqueradingVector[5]))
    {
        dirtyFlag_[5] = true;
        if(!pJson[pMasqueradingVector[5]].isNull())
        {
            sourcePath_=std::make_shared<std::string>(pJson[pMasqueradingVector[5]].asString());
        }
    }
    if(!pMasqueradingVector[6].empty() && pJson.isMember(pMasqueradingVector[6]))
    {
        dirtyFlag_[6] = true;
        if(!pJson[pMasqueradingVector[6]].isNull())
        {
            dbVersion_=std::make_shared<std::string>(pJson[pMasqueradingVector[6]].asString());
        }
    }
    if(!pMasqueradingVector[7].empty() && pJson.isMember(pMasqueradingVector[7]))
    {
        dirtyFlag_[7] = true;
        if(!pJson[pMasqueradingVector[7]].isNull())
        {
            isEnabled_=std::make_shared<bool>(pJson[pMasqueradingVector[7]].asBool());
        }
    }
    if(!pMasqueradingVector[8].empty() && pJson.isMember(pMasqueradingVector[8]))
    {
        dirtyFlag_[8] = true;
        if(!pJson[pMasqueradingVector[8]].isNull())
        {
            auto timeStr = pJson[pMasqueradingVector[8]].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                createdAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
    if(!pMasqueradingVector[9].empty() && pJson.isMember(pMasqueradingVector[9]))
    {
        dirtyFlag_[9] = true;
        if(!pJson[pMasqueradingVector[9]].isNull())
        {
            auto timeStr = pJson[pMasqueradingVector[9]].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                updatedAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
}

ProjectDatabases::ProjectDatabases(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("id"))
    {
        dirtyFlag_[0]=true;
        if(!pJson["id"].isNull())
        {
            id_=std::make_shared<int64_t>((int64_t)pJson["id"].asInt64());
        }
    }
    if(pJson.isMember("project_id"))
    {
        dirtyFlag_[1]=true;
        if(!pJson["project_id"].isNull())
        {
            projectId_=std::make_shared<int64_t>((int64_t)pJson["project_id"].asInt64());
        }
    }
    if(pJson.isMember("template_kind"))
    {
        dirtyFlag_[2]=true;
        if(!pJson["template_kind"].isNull())
        {
            templateKind_=std::make_shared<std::string>(pJson["template_kind"].asString());
        }
    }
    if(pJson.isMember("scope_type"))
    {
        dirtyFlag_[3]=true;
        if(!pJson["scope_type"].isNull())
        {
            scopeType_=std::make_shared<std::string>(pJson["scope_type"].asString());
        }
    }
    if(pJson.isMember("source_name"))
    {
        dirtyFlag_[4]=true;
        if(!pJson["source_name"].isNull())
        {
            sourceName_=std::make_shared<std::string>(pJson["source_name"].asString());
        }
    }
    if(pJson.isMember("source_path"))
    {
        dirtyFlag_[5]=true;
        if(!pJson["source_path"].isNull())
        {
            sourcePath_=std::make_shared<std::string>(pJson["source_path"].asString());
        }
    }
    if(pJson.isMember("db_version"))
    {
        dirtyFlag_[6]=true;
        if(!pJson["db_version"].isNull())
        {
            dbVersion_=std::make_shared<std::string>(pJson["db_version"].asString());
        }
    }
    if(pJson.isMember("is_enabled"))
    {
        dirtyFlag_[7]=true;
        if(!pJson["is_enabled"].isNull())
        {
            isEnabled_=std::make_shared<bool>(pJson["is_enabled"].asBool());
        }
    }
    if(pJson.isMember("created_at"))
    {
        dirtyFlag_[8]=true;
        if(!pJson["created_at"].isNull())
        {
            auto timeStr = pJson["created_at"].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                createdAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
    if(pJson.isMember("updated_at"))
    {
        dirtyFlag_[9]=true;
        if(!pJson["updated_at"].isNull())
        {
            auto timeStr = pJson["updated_at"].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                updatedAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
}

void ProjectDatabases::updateByMasqueradedJson(const Json::Value &pJson,
                                            const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 10)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            id_=std::make_shared<int64_t>((int64_t)pJson[pMasqueradingVector[0]].asInt64());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        dirtyFlag_[1] = true;
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            projectId_=std::make_shared<int64_t>((int64_t)pJson[pMasqueradingVector[1]].asInt64());
        }
    }
    if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
    {
        dirtyFlag_[2] = true;
        if(!pJson[pMasqueradingVector[2]].isNull())
        {
            templateKind_=std::make_shared<std::string>(pJson[pMasqueradingVector[2]].asString());
        }
    }
    if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
    {
        dirtyFlag_[3] = true;
        if(!pJson[pMasqueradingVector[3]].isNull())
        {
            scopeType_=std::make_shared<std::string>(pJson[pMasqueradingVector[3]].asString());
        }
    }
    if(!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
    {
        dirtyFlag_[4] = true;
        if(!pJson[pMasqueradingVector[4]].isNull())
        {
            sourceName_=std::make_shared<std::string>(pJson[pMasqueradingVector[4]].asString());
        }
    }
    if(!pMasqueradingVector[5].empty() && pJson.isMember(pMasqueradingVector[5]))
    {
        dirtyFlag_[5] = true;
        if(!pJson[pMasqueradingVector[5]].isNull())
        {
            sourcePath_=std::make_shared<std::string>(pJson[pMasqueradingVector[5]].asString());
        }
    }
    if(!pMasqueradingVector[6].empty() && pJson.isMember(pMasqueradingVector[6]))
    {
        dirtyFlag_[6] = true;
        if(!pJson[pMasqueradingVector[6]].isNull())
        {
            dbVersion_=std::make_shared<std::string>(pJson[pMasqueradingVector[6]].asString());
        }
    }
    if(!pMasqueradingVector[7].empty() && pJson.isMember(pMasqueradingVector[7]))
    {
        dirtyFlag_[7] = true;
        if(!pJson[pMasqueradingVector[7]].isNull())
        {
            isEnabled_=std::make_shared<bool>(pJson[pMasqueradingVector[7]].asBool());
        }
    }
    if(!pMasqueradingVector[8].empty() && pJson.isMember(pMasqueradingVector[8]))
    {
        dirtyFlag_[8] = true;
        if(!pJson[pMasqueradingVector[8]].isNull())
        {
            auto timeStr = pJson[pMasqueradingVector[8]].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                createdAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
    if(!pMasqueradingVector[9].empty() && pJson.isMember(pMasqueradingVector[9]))
    {
        dirtyFlag_[9] = true;
        if(!pJson[pMasqueradingVector[9]].isNull())
        {
            auto timeStr = pJson[pMasqueradingVector[9]].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                updatedAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
}

void ProjectDatabases::updateByJson(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("id"))
    {
        if(!pJson["id"].isNull())
        {
            id_=std::make_shared<int64_t>((int64_t)pJson["id"].asInt64());
        }
    }
    if(pJson.isMember("project_id"))
    {
        dirtyFlag_[1] = true;
        if(!pJson["project_id"].isNull())
        {
            projectId_=std::make_shared<int64_t>((int64_t)pJson["project_id"].asInt64());
        }
    }
    if(pJson.isMember("template_kind"))
    {
        dirtyFlag_[2] = true;
        if(!pJson["template_kind"].isNull())
        {
            templateKind_=std::make_shared<std::string>(pJson["template_kind"].asString());
        }
    }
    if(pJson.isMember("scope_type"))
    {
        dirtyFlag_[3] = true;
        if(!pJson["scope_type"].isNull())
        {
            scopeType_=std::make_shared<std::string>(pJson["scope_type"].asString());
        }
    }
    if(pJson.isMember("source_name"))
    {
        dirtyFlag_[4] = true;
        if(!pJson["source_name"].isNull())
        {
            sourceName_=std::make_shared<std::string>(pJson["source_name"].asString());
        }
    }
    if(pJson.isMember("source_path"))
    {
        dirtyFlag_[5] = true;
        if(!pJson["source_path"].isNull())
        {
            sourcePath_=std::make_shared<std::string>(pJson["source_path"].asString());
        }
    }
    if(pJson.isMember("db_version"))
    {
        dirtyFlag_[6] = true;
        if(!pJson["db_version"].isNull())
        {
            dbVersion_=std::make_shared<std::string>(pJson["db_version"].asString());
        }
    }
    if(pJson.isMember("is_enabled"))
    {
        dirtyFlag_[7] = true;
        if(!pJson["is_enabled"].isNull())
        {
            isEnabled_=std::make_shared<bool>(pJson["is_enabled"].asBool());
        }
    }
    if(pJson.isMember("created_at"))
    {
        dirtyFlag_[8] = true;
        if(!pJson["created_at"].isNull())
        {
            auto timeStr = pJson["created_at"].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                createdAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
    if(pJson.isMember("updated_at"))
    {
        dirtyFlag_[9] = true;
        if(!pJson["updated_at"].isNull())
        {
            auto timeStr = pJson["updated_at"].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                updatedAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
}

const int64_t &ProjectDatabases::getValueOfId() const noexcept
{
    static const int64_t defaultValue = int64_t();
    if(id_)
        return *id_;
    return defaultValue;
}
const std::shared_ptr<int64_t> &ProjectDatabases::getId() const noexcept
{
    return id_;
}
void ProjectDatabases::setId(const int64_t &pId) noexcept
{
    id_ = std::make_shared<int64_t>(pId);
    dirtyFlag_[0] = true;
}
const typename ProjectDatabases::PrimaryKeyType & ProjectDatabases::getPrimaryKey() const
{
    assert(id_);
    return *id_;
}

const int64_t &ProjectDatabases::getValueOfProjectId() const noexcept
{
    static const int64_t defaultValue = int64_t();
    if(projectId_)
        return *projectId_;
    return defaultValue;
}
const std::shared_ptr<int64_t> &ProjectDatabases::getProjectId() const noexcept
{
    return projectId_;
}
void ProjectDatabases::setProjectId(const int64_t &pProjectId) noexcept
{
    projectId_ = std::make_shared<int64_t>(pProjectId);
    dirtyFlag_[1] = true;
}
void ProjectDatabases::setProjectIdToNull() noexcept
{
    projectId_.reset();
    dirtyFlag_[1] = true;
}

const std::string &ProjectDatabases::getValueOfTemplateKind() const noexcept
{
    static const std::string defaultValue = std::string();
    if(templateKind_)
        return *templateKind_;
    return defaultValue;
}
const std::shared_ptr<std::string> &ProjectDatabases::getTemplateKind() const noexcept
{
    return templateKind_;
}
void ProjectDatabases::setTemplateKind(const std::string &pTemplateKind) noexcept
{
    templateKind_ = std::make_shared<std::string>(pTemplateKind);
    dirtyFlag_[2] = true;
}
void ProjectDatabases::setTemplateKind(std::string &&pTemplateKind) noexcept
{
    templateKind_ = std::make_shared<std::string>(std::move(pTemplateKind));
    dirtyFlag_[2] = true;
}

const std::string &ProjectDatabases::getValueOfScopeType() const noexcept
{
    static const std::string defaultValue = std::string();
    if(scopeType_)
        return *scopeType_;
    return defaultValue;
}
const std::shared_ptr<std::string> &ProjectDatabases::getScopeType() const noexcept
{
    return scopeType_;
}
void ProjectDatabases::setScopeType(const std::string &pScopeType) noexcept
{
    scopeType_ = std::make_shared<std::string>(pScopeType);
    dirtyFlag_[3] = true;
}
void ProjectDatabases::setScopeType(std::string &&pScopeType) noexcept
{
    scopeType_ = std::make_shared<std::string>(std::move(pScopeType));
    dirtyFlag_[3] = true;
}

const std::string &ProjectDatabases::getValueOfSourceName() const noexcept
{
    static const std::string defaultValue = std::string();
    if(sourceName_)
        return *sourceName_;
    return defaultValue;
}
const std::shared_ptr<std::string> &ProjectDatabases::getSourceName() const noexcept
{
    return sourceName_;
}
void ProjectDatabases::setSourceName(const std::string &pSourceName) noexcept
{
    sourceName_ = std::make_shared<std::string>(pSourceName);
    dirtyFlag_[4] = true;
}
void ProjectDatabases::setSourceName(std::string &&pSourceName) noexcept
{
    sourceName_ = std::make_shared<std::string>(std::move(pSourceName));
    dirtyFlag_[4] = true;
}
void ProjectDatabases::setSourceNameToNull() noexcept
{
    sourceName_.reset();
    dirtyFlag_[4] = true;
}

const std::string &ProjectDatabases::getValueOfSourcePath() const noexcept
{
    static const std::string defaultValue = std::string();
    if(sourcePath_)
        return *sourcePath_;
    return defaultValue;
}
const std::shared_ptr<std::string> &ProjectDatabases::getSourcePath() const noexcept
{
    return sourcePath_;
}
void ProjectDatabases::setSourcePath(const std::string &pSourcePath) noexcept
{
    sourcePath_ = std::make_shared<std::string>(pSourcePath);
    dirtyFlag_[5] = true;
}
void ProjectDatabases::setSourcePath(std::string &&pSourcePath) noexcept
{
    sourcePath_ = std::make_shared<std::string>(std::move(pSourcePath));
    dirtyFlag_[5] = true;
}
void ProjectDatabases::setSourcePathToNull() noexcept
{
    sourcePath_.reset();
    dirtyFlag_[5] = true;
}

const std::string &ProjectDatabases::getValueOfDbVersion() const noexcept
{
    static const std::string defaultValue = std::string();
    if(dbVersion_)
        return *dbVersion_;
    return defaultValue;
}
const std::shared_ptr<std::string> &ProjectDatabases::getDbVersion() const noexcept
{
    return dbVersion_;
}
void ProjectDatabases::setDbVersion(const std::string &pDbVersion) noexcept
{
    dbVersion_ = std::make_shared<std::string>(pDbVersion);
    dirtyFlag_[6] = true;
}
void ProjectDatabases::setDbVersion(std::string &&pDbVersion) noexcept
{
    dbVersion_ = std::make_shared<std::string>(std::move(pDbVersion));
    dirtyFlag_[6] = true;
}
void ProjectDatabases::setDbVersionToNull() noexcept
{
    dbVersion_.reset();
    dirtyFlag_[6] = true;
}

const bool &ProjectDatabases::getValueOfIsEnabled() const noexcept
{
    static const bool defaultValue = bool();
    if(isEnabled_)
        return *isEnabled_;
    return defaultValue;
}
const std::shared_ptr<bool> &ProjectDatabases::getIsEnabled() const noexcept
{
    return isEnabled_;
}
void ProjectDatabases::setIsEnabled(const bool &pIsEnabled) noexcept
{
    isEnabled_ = std::make_shared<bool>(pIsEnabled);
    dirtyFlag_[7] = true;
}

const ::trantor::Date &ProjectDatabases::getValueOfCreatedAt() const noexcept
{
    static const ::trantor::Date defaultValue = ::trantor::Date();
    if(createdAt_)
        return *createdAt_;
    return defaultValue;
}
const std::shared_ptr<::trantor::Date> &ProjectDatabases::getCreatedAt() const noexcept
{
    return createdAt_;
}
void ProjectDatabases::setCreatedAt(const ::trantor::Date &pCreatedAt) noexcept
{
    createdAt_ = std::make_shared<::trantor::Date>(pCreatedAt);
    dirtyFlag_[8] = true;
}

const ::trantor::Date &ProjectDatabases::getValueOfUpdatedAt() const noexcept
{
    static const ::trantor::Date defaultValue = ::trantor::Date();
    if(updatedAt_)
        return *updatedAt_;
    return defaultValue;
}
const std::shared_ptr<::trantor::Date> &ProjectDatabases::getUpdatedAt() const noexcept
{
    return updatedAt_;
}
void ProjectDatabases::setUpdatedAt(const ::trantor::Date &pUpdatedAt) noexcept
{
    updatedAt_ = std::make_shared<::trantor::Date>(pUpdatedAt);
    dirtyFlag_[9] = true;
}

void ProjectDatabases::updateId(const uint64_t id)
{
}

const std::vector<std::string> &ProjectDatabases::insertColumns() noexcept
{
    static const std::vector<std::string> inCols={
        "project_id",
        "template_kind",
        "scope_type",
        "source_name",
        "source_path",
        "db_version",
        "is_enabled",
        "created_at",
        "updated_at"
    };
    return inCols;
}

void ProjectDatabases::outputArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[1])
    {
        if(getProjectId())
        {
            binder << getValueOfProjectId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[2])
    {
        if(getTemplateKind())
        {
            binder << getValueOfTemplateKind();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[3])
    {
        if(getScopeType())
        {
            binder << getValueOfScopeType();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[4])
    {
        if(getSourceName())
        {
            binder << getValueOfSourceName();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[5])
    {
        if(getSourcePath())
        {
            binder << getValueOfSourcePath();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[6])
    {
        if(getDbVersion())
        {
            binder << getValueOfDbVersion();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[7])
    {
        if(getIsEnabled())
        {
            binder << getValueOfIsEnabled();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[8])
    {
        if(getCreatedAt())
        {
            binder << getValueOfCreatedAt();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[9])
    {
        if(getUpdatedAt())
        {
            binder << getValueOfUpdatedAt();
        }
        else
        {
            binder << nullptr;
        }
    }
}

const std::vector<std::string> ProjectDatabases::updateColumns() const
{
    std::vector<std::string> ret;
    if(dirtyFlag_[1])
    {
        ret.push_back(getColumnName(1));
    }
    if(dirtyFlag_[2])
    {
        ret.push_back(getColumnName(2));
    }
    if(dirtyFlag_[3])
    {
        ret.push_back(getColumnName(3));
    }
    if(dirtyFlag_[4])
    {
        ret.push_back(getColumnName(4));
    }
    if(dirtyFlag_[5])
    {
        ret.push_back(getColumnName(5));
    }
    if(dirtyFlag_[6])
    {
        ret.push_back(getColumnName(6));
    }
    if(dirtyFlag_[7])
    {
        ret.push_back(getColumnName(7));
    }
    if(dirtyFlag_[8])
    {
        ret.push_back(getColumnName(8));
    }
    if(dirtyFlag_[9])
    {
        ret.push_back(getColumnName(9));
    }
    return ret;
}

void ProjectDatabases::updateArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[1])
    {
        if(getProjectId())
        {
            binder << getValueOfProjectId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[2])
    {
        if(getTemplateKind())
        {
            binder << getValueOfTemplateKind();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[3])
    {
        if(getScopeType())
        {
            binder << getValueOfScopeType();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[4])
    {
        if(getSourceName())
        {
            binder << getValueOfSourceName();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[5])
    {
        if(getSourcePath())
        {
            binder << getValueOfSourcePath();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[6])
    {
        if(getDbVersion())
        {
            binder << getValueOfDbVersion();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[7])
    {
        if(getIsEnabled())
        {
            binder << getValueOfIsEnabled();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[8])
    {
        if(getCreatedAt())
        {
            binder << getValueOfCreatedAt();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[9])
    {
        if(getUpdatedAt())
        {
            binder << getValueOfUpdatedAt();
        }
        else
        {
            binder << nullptr;
        }
    }
}
Json::Value ProjectDatabases::toJson() const
{
    Json::Value ret;
    if(getId())
    {
        ret["id"]=(Json::Int64)getValueOfId();
    }
    else
    {
        ret["id"]=Json::Value();
    }
    if(getProjectId())
    {
        ret["project_id"]=(Json::Int64)getValueOfProjectId();
    }
    else
    {
        ret["project_id"]=Json::Value();
    }
    if(getTemplateKind())
    {
        ret["template_kind"]=getValueOfTemplateKind();
    }
    else
    {
        ret["template_kind"]=Json::Value();
    }
    if(getScopeType())
    {
        ret["scope_type"]=getValueOfScopeType();
    }
    else
    {
        ret["scope_type"]=Json::Value();
    }
    if(getSourceName())
    {
        ret["source_name"]=getValueOfSourceName();
    }
    else
    {
        ret["source_name"]=Json::Value();
    }
    if(getSourcePath())
    {
        ret["source_path"]=getValueOfSourcePath();
    }
    else
    {
        ret["source_path"]=Json::Value();
    }
    if(getDbVersion())
    {
        ret["db_version"]=getValueOfDbVersion();
    }
    else
    {
        ret["db_version"]=Json::Value();
    }
    if(getIsEnabled())
    {
        ret["is_enabled"]=getValueOfIsEnabled();
    }
    else
    {
        ret["is_enabled"]=Json::Value();
    }
    if(getCreatedAt())
    {
        ret["created_at"]=getCreatedAt()->toDbStringLocal();
    }
    else
    {
        ret["created_at"]=Json::Value();
    }
    if(getUpdatedAt())
    {
        ret["updated_at"]=getUpdatedAt()->toDbStringLocal();
    }
    else
    {
        ret["updated_at"]=Json::Value();
    }
    return ret;
}

std::string ProjectDatabases::toString() const
{
    return toJson().toStyledString();
}

Json::Value ProjectDatabases::toMasqueradedJson(
    const std::vector<std::string> &pMasqueradingVector) const
{
    Json::Value ret;
    if(pMasqueradingVector.size() == 10)
    {
        if(!pMasqueradingVector[0].empty())
        {
            if(getId())
            {
                ret[pMasqueradingVector[0]]=(Json::Int64)getValueOfId();
            }
            else
            {
                ret[pMasqueradingVector[0]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[1].empty())
        {
            if(getProjectId())
            {
                ret[pMasqueradingVector[1]]=(Json::Int64)getValueOfProjectId();
            }
            else
            {
                ret[pMasqueradingVector[1]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[2].empty())
        {
            if(getTemplateKind())
            {
                ret[pMasqueradingVector[2]]=getValueOfTemplateKind();
            }
            else
            {
                ret[pMasqueradingVector[2]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[3].empty())
        {
            if(getScopeType())
            {
                ret[pMasqueradingVector[3]]=getValueOfScopeType();
            }
            else
            {
                ret[pMasqueradingVector[3]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[4].empty())
        {
            if(getSourceName())
            {
                ret[pMasqueradingVector[4]]=getValueOfSourceName();
            }
            else
            {
                ret[pMasqueradingVector[4]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[5].empty())
        {
            if(getSourcePath())
            {
                ret[pMasqueradingVector[5]]=getValueOfSourcePath();
            }
            else
            {
                ret[pMasqueradingVector[5]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[6].empty())
        {
            if(getDbVersion())
            {
                ret[pMasqueradingVector[6]]=getValueOfDbVersion();
            }
            else
            {
                ret[pMasqueradingVector[6]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[7].empty())
        {
            if(getIsEnabled())
            {
                ret[pMasqueradingVector[7]]=getValueOfIsEnabled();
            }
            else
            {
                ret[pMasqueradingVector[7]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[8].empty())
        {
            if(getCreatedAt())
            {
                ret[pMasqueradingVector[8]]=getCreatedAt()->toDbStringLocal();
            }
            else
            {
                ret[pMasqueradingVector[8]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[9].empty())
        {
            if(getUpdatedAt())
            {
                ret[pMasqueradingVector[9]]=getUpdatedAt()->toDbStringLocal();
            }
            else
            {
                ret[pMasqueradingVector[9]]=Json::Value();
            }
        }
        return ret;
    }
    LOG_ERROR << "Masquerade failed";
    if(getId())
    {
        ret["id"]=(Json::Int64)getValueOfId();
    }
    else
    {
        ret["id"]=Json::Value();
    }
    if(getProjectId())
    {
        ret["project_id"]=(Json::Int64)getValueOfProjectId();
    }
    else
    {
        ret["project_id"]=Json::Value();
    }
    if(getTemplateKind())
    {
        ret["template_kind"]=getValueOfTemplateKind();
    }
    else
    {
        ret["template_kind"]=Json::Value();
    }
    if(getScopeType())
    {
        ret["scope_type"]=getValueOfScopeType();
    }
    else
    {
        ret["scope_type"]=Json::Value();
    }
    if(getSourceName())
    {
        ret["source_name"]=getValueOfSourceName();
    }
    else
    {
        ret["source_name"]=Json::Value();
    }
    if(getSourcePath())
    {
        ret["source_path"]=getValueOfSourcePath();
    }
    else
    {
        ret["source_path"]=Json::Value();
    }
    if(getDbVersion())
    {
        ret["db_version"]=getValueOfDbVersion();
    }
    else
    {
        ret["db_version"]=Json::Value();
    }
    if(getIsEnabled())
    {
        ret["is_enabled"]=getValueOfIsEnabled();
    }
    else
    {
        ret["is_enabled"]=Json::Value();
    }
    if(getCreatedAt())
    {
        ret["created_at"]=getCreatedAt()->toDbStringLocal();
    }
    else
    {
        ret["created_at"]=Json::Value();
    }
    if(getUpdatedAt())
    {
        ret["updated_at"]=getUpdatedAt()->toDbStringLocal();
    }
    else
    {
        ret["updated_at"]=Json::Value();
    }
    return ret;
}

bool ProjectDatabases::validateJsonForCreation(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("id"))
    {
        if(!validJsonOfField(0, "id", pJson["id"], err, true))
            return false;
    }
    if(pJson.isMember("project_id"))
    {
        if(!validJsonOfField(1, "project_id", pJson["project_id"], err, true))
            return false;
    }
    if(pJson.isMember("template_kind"))
    {
        if(!validJsonOfField(2, "template_kind", pJson["template_kind"], err, true))
            return false;
    }
    else
    {
        err="The template_kind column cannot be null";
        return false;
    }
    if(pJson.isMember("scope_type"))
    {
        if(!validJsonOfField(3, "scope_type", pJson["scope_type"], err, true))
            return false;
    }
    else
    {
        err="The scope_type column cannot be null";
        return false;
    }
    if(pJson.isMember("source_name"))
    {
        if(!validJsonOfField(4, "source_name", pJson["source_name"], err, true))
            return false;
    }
    if(pJson.isMember("source_path"))
    {
        if(!validJsonOfField(5, "source_path", pJson["source_path"], err, true))
            return false;
    }
    if(pJson.isMember("db_version"))
    {
        if(!validJsonOfField(6, "db_version", pJson["db_version"], err, true))
            return false;
    }
    if(pJson.isMember("is_enabled"))
    {
        if(!validJsonOfField(7, "is_enabled", pJson["is_enabled"], err, true))
            return false;
    }
    if(pJson.isMember("created_at"))
    {
        if(!validJsonOfField(8, "created_at", pJson["created_at"], err, true))
            return false;
    }
    if(pJson.isMember("updated_at"))
    {
        if(!validJsonOfField(9, "updated_at", pJson["updated_at"], err, true))
            return false;
    }
    return true;
}
bool ProjectDatabases::validateMasqueradedJsonForCreation(const Json::Value &pJson,
                                                          const std::vector<std::string> &pMasqueradingVector,
                                                          std::string &err)
{
    if(pMasqueradingVector.size() != 10)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty())
      {
          if(pJson.isMember(pMasqueradingVector[0]))
          {
              if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[1].empty())
      {
          if(pJson.isMember(pMasqueradingVector[1]))
          {
              if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[2].empty())
      {
          if(pJson.isMember(pMasqueradingVector[2]))
          {
              if(!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[2] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[3].empty())
      {
          if(pJson.isMember(pMasqueradingVector[3]))
          {
              if(!validJsonOfField(3, pMasqueradingVector[3], pJson[pMasqueradingVector[3]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[3] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[4].empty())
      {
          if(pJson.isMember(pMasqueradingVector[4]))
          {
              if(!validJsonOfField(4, pMasqueradingVector[4], pJson[pMasqueradingVector[4]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[5].empty())
      {
          if(pJson.isMember(pMasqueradingVector[5]))
          {
              if(!validJsonOfField(5, pMasqueradingVector[5], pJson[pMasqueradingVector[5]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[6].empty())
      {
          if(pJson.isMember(pMasqueradingVector[6]))
          {
              if(!validJsonOfField(6, pMasqueradingVector[6], pJson[pMasqueradingVector[6]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[7].empty())
      {
          if(pJson.isMember(pMasqueradingVector[7]))
          {
              if(!validJsonOfField(7, pMasqueradingVector[7], pJson[pMasqueradingVector[7]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[8].empty())
      {
          if(pJson.isMember(pMasqueradingVector[8]))
          {
              if(!validJsonOfField(8, pMasqueradingVector[8], pJson[pMasqueradingVector[8]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[9].empty())
      {
          if(pJson.isMember(pMasqueradingVector[9]))
          {
              if(!validJsonOfField(9, pMasqueradingVector[9], pJson[pMasqueradingVector[9]], err, true))
                  return false;
          }
      }
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool ProjectDatabases::validateJsonForUpdate(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("id"))
    {
        if(!validJsonOfField(0, "id", pJson["id"], err, false))
            return false;
    }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
    if(pJson.isMember("project_id"))
    {
        if(!validJsonOfField(1, "project_id", pJson["project_id"], err, false))
            return false;
    }
    if(pJson.isMember("template_kind"))
    {
        if(!validJsonOfField(2, "template_kind", pJson["template_kind"], err, false))
            return false;
    }
    if(pJson.isMember("scope_type"))
    {
        if(!validJsonOfField(3, "scope_type", pJson["scope_type"], err, false))
            return false;
    }
    if(pJson.isMember("source_name"))
    {
        if(!validJsonOfField(4, "source_name", pJson["source_name"], err, false))
            return false;
    }
    if(pJson.isMember("source_path"))
    {
        if(!validJsonOfField(5, "source_path", pJson["source_path"], err, false))
            return false;
    }
    if(pJson.isMember("db_version"))
    {
        if(!validJsonOfField(6, "db_version", pJson["db_version"], err, false))
            return false;
    }
    if(pJson.isMember("is_enabled"))
    {
        if(!validJsonOfField(7, "is_enabled", pJson["is_enabled"], err, false))
            return false;
    }
    if(pJson.isMember("created_at"))
    {
        if(!validJsonOfField(8, "created_at", pJson["created_at"], err, false))
            return false;
    }
    if(pJson.isMember("updated_at"))
    {
        if(!validJsonOfField(9, "updated_at", pJson["updated_at"], err, false))
            return false;
    }
    return true;
}
bool ProjectDatabases::validateMasqueradedJsonForUpdate(const Json::Value &pJson,
                                                        const std::vector<std::string> &pMasqueradingVector,
                                                        std::string &err)
{
    if(pMasqueradingVector.size() != 10)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
      {
          if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, false))
              return false;
      }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
      if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
      {
          if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, false))
              return false;
      }
      if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
      {
          if(!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err, false))
              return false;
      }
      if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
      {
          if(!validJsonOfField(3, pMasqueradingVector[3], pJson[pMasqueradingVector[3]], err, false))
              return false;
      }
      if(!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
      {
          if(!validJsonOfField(4, pMasqueradingVector[4], pJson[pMasqueradingVector[4]], err, false))
              return false;
      }
      if(!pMasqueradingVector[5].empty() && pJson.isMember(pMasqueradingVector[5]))
      {
          if(!validJsonOfField(5, pMasqueradingVector[5], pJson[pMasqueradingVector[5]], err, false))
              return false;
      }
      if(!pMasqueradingVector[6].empty() && pJson.isMember(pMasqueradingVector[6]))
      {
          if(!validJsonOfField(6, pMasqueradingVector[6], pJson[pMasqueradingVector[6]], err, false))
              return false;
      }
      if(!pMasqueradingVector[7].empty() && pJson.isMember(pMasqueradingVector[7]))
      {
          if(!validJsonOfField(7, pMasqueradingVector[7], pJson[pMasqueradingVector[7]], err, false))
              return false;
      }
      if(!pMasqueradingVector[8].empty() && pJson.isMember(pMasqueradingVector[8]))
      {
          if(!validJsonOfField(8, pMasqueradingVector[8], pJson[pMasqueradingVector[8]], err, false))
              return false;
      }
      if(!pMasqueradingVector[9].empty() && pJson.isMember(pMasqueradingVector[9]))
      {
          if(!validJsonOfField(9, pMasqueradingVector[9], pJson[pMasqueradingVector[9]], err, false))
              return false;
      }
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool ProjectDatabases::validJsonOfField(size_t index,
                                        const std::string &fieldName,
                                        const Json::Value &pJson,
                                        std::string &err,
                                        bool isForCreation)
{
    switch(index)
    {
        case 0:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(isForCreation)
            {
                err="The automatic primary key cannot be set";
                return false;
            }
            if(!pJson.isInt64())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 1:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isInt64())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 2:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            if(pJson.isString() && std::wstring_convert<std::codecvt_utf8_utf16<wchar_t>, wchar_t>{}
                .from_bytes(pJson.asCString()).size() > 64)
            {
                err="String length exceeds limit for the " +
                    fieldName +
                    " field (the maximum value is 64)";
                return false;
            }
            break;
        case 3:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            if(pJson.isString() && std::wstring_convert<std::codecvt_utf8_utf16<wchar_t>, wchar_t>{}
                .from_bytes(pJson.asCString()).size() > 16)
            {
                err="String length exceeds limit for the " +
                    fieldName +
                    " field (the maximum value is 16)";
                return false;
            }
            break;
        case 4:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            if(pJson.isString() && std::wstring_convert<std::codecvt_utf8_utf16<wchar_t>, wchar_t>{}
                .from_bytes(pJson.asCString()).size() > 256)
            {
                err="String length exceeds limit for the " +
                    fieldName +
                    " field (the maximum value is 256)";
                return false;
            }
            break;
        case 5:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 6:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            if(pJson.isString() && std::wstring_convert<std::codecvt_utf8_utf16<wchar_t>, wchar_t>{}
                .from_bytes(pJson.asCString()).size() > 64)
            {
                err="String length exceeds limit for the " +
                    fieldName +
                    " field (the maximum value is 64)";
                return false;
            }
            break;
        case 7:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isBool())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 8:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 9:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        default:
            err="Internal error in the server";
            return false;
    }
    return true;
}
Projects ProjectDatabases::getProject(const DbClientPtr &clientPtr) const {
    static const std::string sql = "select * from projects where id = $1";
    Result r(nullptr);
    {
        auto binder = *clientPtr << sql;
        binder << *projectId_ << Mode::Blocking >>
            [&r](const Result &result) { r = result; };
        binder.exec();
    }
    if (r.size() == 0)
    {
        throw UnexpectedRows("0 rows found");
    }
    else if (r.size() > 1)
    {
        throw UnexpectedRows("Found more than one row");
    }
    return Projects(r[0]);
}

void ProjectDatabases::getProject(const DbClientPtr &clientPtr,
                                  const std::function<void(Projects)> &rcb,
                                  const ExceptionCallback &ecb) const
{
    static const std::string sql = "select * from projects where id = $1";
    *clientPtr << sql
               << *projectId_
               >> [rcb = std::move(rcb), ecb](const Result &r){
                    if (r.size() == 0)
                    {
                        ecb(UnexpectedRows("0 rows found"));
                    }
                    else if (r.size() > 1)
                    {
                        ecb(UnexpectedRows("Found more than one row"));
                    }
                    else
                    {
                        rcb(Projects(r[0]));
                    }
               }
               >> ecb;
}
