/**
 *
 *  ProjectDatabases.h
 *  DO NOT EDIT. This file is generated by drogon_ctl
 *
 */

#pragma once
#include <drogon/orm/Result.h>
#include <drogon/orm/Row.h>
#include <drogon/orm/Field.h>
#include <drogon/orm/SqlBinder.h>
#include <drogon/orm/Mapper.h>
#include <drogon/orm/BaseBuilder.h>
#ifdef __cpp_impl_coroutine
#include <drogon/orm/CoroMapper.h>
#endif
#include <trantor/utils/Date.h>
#include <trantor/utils/Logger.h>
#include <json/json.h>
#include <string>
#include <string_view>
#include <memory>
#include <vector>
#include <tuple>
#include <stdint.h>
#include <iostream>

namespace drogon
{
namespace orm
{
class DbClient;
using DbClientPtr = std::shared_ptr<DbClient>;
}
}
namespace drogon_model
{
namespace UELocalDB
{
namespace core
{
class Projects;

class ProjectDatabases
{
  public:
    struct Cols
    {
        static const std::string _id;
        static const std::string _project_id;
        static const std::string _template_kind;
        static const std::string _scope_type;
        static const std::string _source_name;
        static const std::string _source_path;
        static const std::string _db_version;
        static const std::string _is_enabled;
        static const std::string _created_at;
        static const std::string _updated_at;
    };

    static const int primaryKeyNumber;
    static const std::string tableName;
    static const bool hasPrimaryKey;
    static const std::string primaryKeyName;
    using PrimaryKeyType = int64_t;
    const PrimaryKeyType &getPrimaryKey() const;

    /**
     * @brief constructor
     * @param r One row of records in the SQL query result.
     * @param indexOffset Set the offset to -1 to access all columns by column names,
     * otherwise access all columns by offsets.
     * @note If the SQL is not a style of 'select * from table_name ...' (select all
     * columns by an asterisk), please set the offset to -1.
     */
    explicit ProjectDatabases(const drogon::orm::Row &r, const ssize_t indexOffset = 0) noexcept;

    /**
     * @brief constructor
     * @param pJson The json object to construct a new instance.
     */
    explicit ProjectDatabases(const Json::Value &pJson) noexcept(false);

    /**
     * @brief constructor
     * @param pJson The json object to construct a new instance.
     * @param pMasqueradingVector The aliases of table columns.
     */
    ProjectDatabases(const Json::Value &pJson, const std::vector<std::string> &pMasqueradingVector) noexcept(false);

    ProjectDatabases() = default;

    void updateByJson(const Json::Value &pJson) noexcept(false);
    void updateByMasqueradedJson(const Json::Value &pJson,
                                 const std::vector<std::string> &pMasqueradingVector) noexcept(false);
    static bool validateJsonForCreation(const Json::Value &pJson, std::string &err);
    static bool validateMasqueradedJsonForCreation(const Json::Value &,
                                                const std::vector<std::string> &pMasqueradingVector,
                                                    std::string &err);
    static bool validateJsonForUpdate(const Json::Value &pJson, std::string &err);
    static bool validateMasqueradedJsonForUpdate(const Json::Value &,
                                          const std::vector<std::string> &pMasqueradingVector,
                                          std::string &err);
    static bool validJsonOfField(size_t index,
                          const std::string &fieldName,
                          const Json::Value &pJson,
                          std::string &err,
                          bool isForCreation);

    /**  For column id  */
    ///Get the value of the column id, returns the default value if the column is null
    const int64_t &getValueOfId() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<int64_t> &getId() const noexcept;
    ///Set the value of the column id
    void setId(const int64_t &pId) noexcept;

    /**  For column project_id  */
    ///Get the value of the column project_id, returns the default value if the column is null
    const int64_t &getValueOfProjectId() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<int64_t> &getProjectId() const noexcept;
    ///Set the value of the column project_id
    void setProjectId(const int64_t &pProjectId) noexcept;
    void setProjectIdToNull() noexcept;

    /**  For column template_kind  */
    ///Get the value of the column template_kind, returns the default value if the column is null
    const std::string &getValueOfTemplateKind() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getTemplateKind() const noexcept;
    ///Set the value of the column template_kind
    void setTemplateKind(const std::string &pTemplateKind) noexcept;
    void setTemplateKind(std::string &&pTemplateKind) noexcept;

    /**  For column scope_type  */
    ///Get the value of the column scope_type, returns the default value if the column is null
    const std::string &getValueOfScopeType() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getScopeType() const noexcept;
    ///Set the value of the column scope_type
    void setScopeType(const std::string &pScopeType) noexcept;
    void setScopeType(std::string &&pScopeType) noexcept;

    /**  For column source_name  */
    ///Get the value of the column source_name, returns the default value if the column is null
    const std::string &getValueOfSourceName() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getSourceName() const noexcept;
    ///Set the value of the column source_name
    void setSourceName(const std::string &pSourceName) noexcept;
    void setSourceName(std::string &&pSourceName) noexcept;
    void setSourceNameToNull() noexcept;

    /**  For column source_path  */
    ///Get the value of the column source_path, returns the default value if the column is null
    const std::string &getValueOfSourcePath() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getSourcePath() const noexcept;
    ///Set the value of the column source_path
    void setSourcePath(const std::string &pSourcePath) noexcept;
    void setSourcePath(std::string &&pSourcePath) noexcept;
    void setSourcePathToNull() noexcept;

    /**  For column db_version  */
    ///Get the value of the column db_version, returns the default value if the column is null
    const std::string &getValueOfDbVersion() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getDbVersion() const noexcept;
    ///Set the value of the column db_version
    void setDbVersion(const std::string &pDbVersion) noexcept;
    void setDbVersion(std::string &&pDbVersion) noexcept;
    void setDbVersionToNull() noexcept;

    /**  For column is_enabled  */
    ///Get the value of the column is_enabled, returns the default value if the column is null
    const bool &getValueOfIsEnabled() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<bool> &getIsEnabled() const noexcept;
    ///Set the value of the column is_enabled
    void setIsEnabled(const bool &pIsEnabled) noexcept;

    /**  For column created_at  */
    ///Get the value of the column created_at, returns the default value if the column is null
    const ::trantor::Date &getValueOfCreatedAt() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<::trantor::Date> &getCreatedAt() const noexcept;
    ///Set the value of the column created_at
    void setCreatedAt(const ::trantor::Date &pCreatedAt) noexcept;

    /**  For column updated_at  */
    ///Get the value of the column updated_at, returns the default value if the column is null
    const ::trantor::Date &getValueOfUpdatedAt() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<::trantor::Date> &getUpdatedAt() const noexcept;
    ///Set the value of the column updated_at
    void setUpdatedAt(const ::trantor::Date &pUpdatedAt) noexcept;


    static size_t getColumnNumber() noexcept {  return 10;  }
    static const std::string &getColumnName(size_t index) noexcept(false);

    Json::Value toJson() const;
    std::string toString() const;
    Json::Value toMasqueradedJson(const std::vector<std::string> &pMasqueradingVector) const;
    /// Relationship interfaces
    Projects getProject(const drogon::orm::DbClientPtr &clientPtr) const;
    void getProject(const drogon::orm::DbClientPtr &clientPtr,
                    const std::function<void(Projects)> &rcb,
                    const drogon::orm::ExceptionCallback &ecb) const;
  private:
    friend drogon::orm::Mapper<ProjectDatabases>;
    friend drogon::orm::BaseBuilder<ProjectDatabases, true, true>;
    friend drogon::orm::BaseBuilder<ProjectDatabases, true, false>;
    friend drogon::orm::BaseBuilder<ProjectDatabases, false, true>;
    friend drogon::orm::BaseBuilder<ProjectDatabases, false, false>;
#ifdef __cpp_impl_coroutine
    friend drogon::orm::CoroMapper<ProjectDatabases>;
#endif
    static const std::vector<std::string> &insertColumns() noexcept;
    void outputArgs(drogon::orm::internal::SqlBinder &binder) const;
    const std::vector<std::string> updateColumns() const;
    void updateArgs(drogon::orm::internal::SqlBinder &binder) const;
    ///For mysql or sqlite3
    void updateId(const uint64_t id);
    std::shared_ptr<int64_t> id_;
    std::shared_ptr<int64_t> projectId_;
    std::shared_ptr<std::string> templateKind_;
    std::shared_ptr<std::string> scopeType_;
    std::shared_ptr<std::string> sourceName_;
    std::shared_ptr<std::string> sourcePath_;
    std::shared_ptr<std::string> dbVersion_;
    std::shared_ptr<bool> isEnabled_;
    std::shared_ptr<::trantor::Date> createdAt_;
    std::shared_ptr<::trantor::Date> updatedAt_;
    struct MetaData
    {
        const std::string colName_;
        const std::string colType_;
        const std::string colDatabaseType_;
        const ssize_t colLength_;
        const bool isAutoVal_;
        const bool isPrimaryKey_;
        const bool notNull_;
    };
    static const std::vector<MetaData> metaData_;
    bool dirtyFlag_[10]={ false };
  public:
    static const std::string &sqlForFindingByPrimaryKey()
    {
        static const std::string sql="select * from " + tableName + " where id = $1";
        return sql;
    }

    static const std::string &sqlForDeletingByPrimaryKey()
    {
        static const std::string sql="delete from " + tableName + " where id = $1";
        return sql;
    }
    std::string sqlForInserting(bool &needSelection) const
    {
        std::string sql="insert into " + tableName + " (";
        size_t parametersCount = 0;
        needSelection = false;
            sql += "id,";
            ++parametersCount;
        if(dirtyFlag_[1])
        {
            sql += "project_id,";
            ++parametersCount;
        }
        if(dirtyFlag_[2])
        {
            sql += "template_kind,";
            ++parametersCount;
        }
        if(dirtyFlag_[3])
        {
            sql += "scope_type,";
            ++parametersCount;
        }
        if(dirtyFlag_[4])
        {
            sql += "source_name,";
            ++parametersCount;
        }
        if(dirtyFlag_[5])
        {
            sql += "source_path,";
            ++parametersCount;
        }
        if(dirtyFlag_[6])
        {
            sql += "db_version,";
            ++parametersCount;
        }
        sql += "is_enabled,";
        ++parametersCount;
        if(!dirtyFlag_[7])
        {
            needSelection=true;
        }
        sql += "created_at,";
        ++parametersCount;
        if(!dirtyFlag_[8])
        {
            needSelection=true;
        }
        sql += "updated_at,";
        ++parametersCount;
        if(!dirtyFlag_[9])
        {
            needSelection=true;
        }
        needSelection=true;
        if(parametersCount > 0)
        {
            sql[sql.length()-1]=')';
            sql += " values (";
        }
        else
            sql += ") values (";

        int placeholder=1;
        char placeholderStr[64];
        size_t n=0;
        sql +="default,";
        if(dirtyFlag_[1])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[2])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[3])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[4])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[5])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[6])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[7])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        else
        {
            sql +="default,";
        }
        if(dirtyFlag_[8])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        else
        {
            sql +="default,";
        }
        if(dirtyFlag_[9])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        else
        {
            sql +="default,";
        }
        if(parametersCount > 0)
        {
            sql.resize(sql.length() - 1);
        }
        if(needSelection)
        {
            sql.append(") returning *");
        }
        else
        {
            sql.append(1, ')');
        }
        LOG_TRACE << sql;
        return sql;
    }
};
} // namespace core
} // namespace UELocalDB
} // namespace drogon_model
