/**
 *
 *  MfaChannels.cc
 *  DO NOT EDIT. This file is generated by drogon_ctl
 *
 */

#include "MfaChannels.h"
#include "MfaRecords.h"
#include <drogon/utils/Utilities.h>
#include <codecvt>
#include <string>

using namespace drogon;
using namespace drogon::orm;
using namespace drogon_model::UEAdminAPI;

const std::string MfaChannels::Cols::_id = "\"id\"";
const std::string MfaChannels::Cols::_channel_name = "\"channel_name\"";
const std::string MfaChannels::primaryKeyName = "id";
const bool MfaChannels::hasPrimaryKey = true;
const std::string MfaChannels::tableName = "\"mfa_channels\"";

const std::vector<typename MfaChannels::MetaData> MfaChannels::metaData_={
{"id","int32_t","integer",4,1,1,1},
{"channel_name","std::string","character varying",30,0,0,1}
};
const std::string &MfaChannels::getColumnName(size_t index) noexcept(false)
{
    assert(index < metaData_.size());
    return metaData_[index].colName_;
}
MfaChannels::MfaChannels(const Row &r, const ssize_t indexOffset) noexcept
{
    if(indexOffset < 0)
    {
        if(!r["id"].isNull())
        {
            id_=std::make_shared<int32_t>(r["id"].as<int32_t>());
        }
        if(!r["channel_name"].isNull())
        {
            channelName_=std::make_shared<std::string>(r["channel_name"].as<std::string>());
        }
    }
    else
    {
        size_t offset = (size_t)indexOffset;
        if(offset + 2 > r.size())
        {
            LOG_FATAL << "Invalid SQL result for this model";
            return;
        }
        size_t index;
        index = offset + 0;
        if(!r[index].isNull())
        {
            id_=std::make_shared<int32_t>(r[index].as<int32_t>());
        }
        index = offset + 1;
        if(!r[index].isNull())
        {
            channelName_=std::make_shared<std::string>(r[index].as<std::string>());
        }
    }

}

MfaChannels::MfaChannels(const Json::Value &pJson, const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 2)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        dirtyFlag_[0] = true;
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            id_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[0]].asInt64());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        dirtyFlag_[1] = true;
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            channelName_=std::make_shared<std::string>(pJson[pMasqueradingVector[1]].asString());
        }
    }
}

MfaChannels::MfaChannels(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("id"))
    {
        dirtyFlag_[0]=true;
        if(!pJson["id"].isNull())
        {
            id_=std::make_shared<int32_t>((int32_t)pJson["id"].asInt64());
        }
    }
    if(pJson.isMember("channel_name"))
    {
        dirtyFlag_[1]=true;
        if(!pJson["channel_name"].isNull())
        {
            channelName_=std::make_shared<std::string>(pJson["channel_name"].asString());
        }
    }
}

void MfaChannels::updateByMasqueradedJson(const Json::Value &pJson,
                                            const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 2)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            id_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[0]].asInt64());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        dirtyFlag_[1] = true;
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            channelName_=std::make_shared<std::string>(pJson[pMasqueradingVector[1]].asString());
        }
    }
}

void MfaChannels::updateByJson(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("id"))
    {
        if(!pJson["id"].isNull())
        {
            id_=std::make_shared<int32_t>((int32_t)pJson["id"].asInt64());
        }
    }
    if(pJson.isMember("channel_name"))
    {
        dirtyFlag_[1] = true;
        if(!pJson["channel_name"].isNull())
        {
            channelName_=std::make_shared<std::string>(pJson["channel_name"].asString());
        }
    }
}

const int32_t &MfaChannels::getValueOfId() const noexcept
{
    static const int32_t defaultValue = int32_t();
    if(id_)
        return *id_;
    return defaultValue;
}
const std::shared_ptr<int32_t> &MfaChannels::getId() const noexcept
{
    return id_;
}
void MfaChannels::setId(const int32_t &pId) noexcept
{
    id_ = std::make_shared<int32_t>(pId);
    dirtyFlag_[0] = true;
}
const typename MfaChannels::PrimaryKeyType & MfaChannels::getPrimaryKey() const
{
    assert(id_);
    return *id_;
}

const std::string &MfaChannels::getValueOfChannelName() const noexcept
{
    static const std::string defaultValue = std::string();
    if(channelName_)
        return *channelName_;
    return defaultValue;
}
const std::shared_ptr<std::string> &MfaChannels::getChannelName() const noexcept
{
    return channelName_;
}
void MfaChannels::setChannelName(const std::string &pChannelName) noexcept
{
    channelName_ = std::make_shared<std::string>(pChannelName);
    dirtyFlag_[1] = true;
}
void MfaChannels::setChannelName(std::string &&pChannelName) noexcept
{
    channelName_ = std::make_shared<std::string>(std::move(pChannelName));
    dirtyFlag_[1] = true;
}

void MfaChannels::updateId(const uint64_t id)
{
}

const std::vector<std::string> &MfaChannels::insertColumns() noexcept
{
    static const std::vector<std::string> inCols={
        "channel_name"
    };
    return inCols;
}

void MfaChannels::outputArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[1])
    {
        if(getChannelName())
        {
            binder << getValueOfChannelName();
        }
        else
        {
            binder << nullptr;
        }
    }
}

const std::vector<std::string> MfaChannels::updateColumns() const
{
    std::vector<std::string> ret;
    if(dirtyFlag_[1])
    {
        ret.push_back(getColumnName(1));
    }
    return ret;
}

void MfaChannels::updateArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[1])
    {
        if(getChannelName())
        {
            binder << getValueOfChannelName();
        }
        else
        {
            binder << nullptr;
        }
    }
}
Json::Value MfaChannels::toJson() const
{
    Json::Value ret;
    if(getId())
    {
        ret["id"]=getValueOfId();
    }
    else
    {
        ret["id"]=Json::Value();
    }
    if(getChannelName())
    {
        ret["channel_name"]=getValueOfChannelName();
    }
    else
    {
        ret["channel_name"]=Json::Value();
    }
    return ret;
}

std::string MfaChannels::toString() const
{
    return toJson().toStyledString();
}

Json::Value MfaChannels::toMasqueradedJson(
    const std::vector<std::string> &pMasqueradingVector) const
{
    Json::Value ret;
    if(pMasqueradingVector.size() == 2)
    {
        if(!pMasqueradingVector[0].empty())
        {
            if(getId())
            {
                ret[pMasqueradingVector[0]]=getValueOfId();
            }
            else
            {
                ret[pMasqueradingVector[0]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[1].empty())
        {
            if(getChannelName())
            {
                ret[pMasqueradingVector[1]]=getValueOfChannelName();
            }
            else
            {
                ret[pMasqueradingVector[1]]=Json::Value();
            }
        }
        return ret;
    }
    LOG_ERROR << "Masquerade failed";
    if(getId())
    {
        ret["id"]=getValueOfId();
    }
    else
    {
        ret["id"]=Json::Value();
    }
    if(getChannelName())
    {
        ret["channel_name"]=getValueOfChannelName();
    }
    else
    {
        ret["channel_name"]=Json::Value();
    }
    return ret;
}

bool MfaChannels::validateJsonForCreation(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("id"))
    {
        if(!validJsonOfField(0, "id", pJson["id"], err, true))
            return false;
    }
    if(pJson.isMember("channel_name"))
    {
        if(!validJsonOfField(1, "channel_name", pJson["channel_name"], err, true))
            return false;
    }
    else
    {
        err="The channel_name column cannot be null";
        return false;
    }
    return true;
}
bool MfaChannels::validateMasqueradedJsonForCreation(const Json::Value &pJson,
                                                     const std::vector<std::string> &pMasqueradingVector,
                                                     std::string &err)
{
    if(pMasqueradingVector.size() != 2)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty())
      {
          if(pJson.isMember(pMasqueradingVector[0]))
          {
              if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[1].empty())
      {
          if(pJson.isMember(pMasqueradingVector[1]))
          {
              if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[1] + " column cannot be null";
            return false;
        }
      }
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool MfaChannels::validateJsonForUpdate(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("id"))
    {
        if(!validJsonOfField(0, "id", pJson["id"], err, false))
            return false;
    }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
    if(pJson.isMember("channel_name"))
    {
        if(!validJsonOfField(1, "channel_name", pJson["channel_name"], err, false))
            return false;
    }
    return true;
}
bool MfaChannels::validateMasqueradedJsonForUpdate(const Json::Value &pJson,
                                                   const std::vector<std::string> &pMasqueradingVector,
                                                   std::string &err)
{
    if(pMasqueradingVector.size() != 2)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
      {
          if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, false))
              return false;
      }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
      if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
      {
          if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, false))
              return false;
      }
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool MfaChannels::validJsonOfField(size_t index,
                                   const std::string &fieldName,
                                   const Json::Value &pJson,
                                   std::string &err,
                                   bool isForCreation)
{
    switch(index)
    {
        case 0:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(isForCreation)
            {
                err="The automatic primary key cannot be set";
                return false;
            }
            if(!pJson.isInt())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 1:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            if(pJson.isString() && std::wstring_convert<std::codecvt_utf8_utf16<wchar_t>, wchar_t>{}
                .from_bytes(pJson.asCString()).size() > 30)
            {
                err="String length exceeds limit for the " +
                    fieldName +
                    " field (the maximum value is 30)";
                return false;
            }
            break;
        default:
            err="Internal error in the server";
            return false;
    }
    return true;
}
std::vector<MfaRecords> MfaChannels::getMfa_records(const DbClientPtr &clientPtr) const {
    static const std::string sql = "select * from mfa_records where mfa_channel_id = $1";
    Result r(nullptr);
    {
        auto binder = *clientPtr << sql;
        binder << *id_ << Mode::Blocking >>
            [&r](const Result &result) { r = result; };
        binder.exec();
    }
    std::vector<MfaRecords> ret;
    ret.reserve(r.size());
    for (auto const &row : r)
    {
        ret.emplace_back(MfaRecords(row));
    }
    return ret;
}

void MfaChannels::getMfa_records(const DbClientPtr &clientPtr,
                                 const std::function<void(std::vector<MfaRecords>)> &rcb,
                                 const ExceptionCallback &ecb) const
{
    static const std::string sql = "select * from mfa_records where mfa_channel_id = $1";
    *clientPtr << sql
               << *id_
               >> [rcb = std::move(rcb)](const Result &r){
                   std::vector<MfaRecords> ret;
                   ret.reserve(r.size());
                   for (auto const &row : r)
                   {
                       ret.emplace_back(MfaRecords(row));
                   }
                   rcb(ret);
               }
               >> ecb;
}
