/**
 *
 *  MfaRecords.h
 *  DO NOT EDIT. This file is generated by drogon_ctl
 *
 */

#pragma once
#include <drogon/orm/Result.h>
#include <drogon/orm/Row.h>
#include <drogon/orm/Field.h>
#include <drogon/orm/SqlBinder.h>
#include <drogon/orm/Mapper.h>
#include <drogon/orm/BaseBuilder.h>
#ifdef __cpp_impl_coroutine
#include <drogon/orm/CoroMapper.h>
#endif
#include <trantor/utils/Date.h>
#include <trantor/utils/Logger.h>
#include <json/json.h>
#include <string>
#include <string_view>
#include <memory>
#include <vector>
#include <tuple>
#include <stdint.h>
#include <iostream>

namespace drogon
{
namespace orm
{
class DbClient;
using DbClientPtr = std::shared_ptr<DbClient>;
}
}
namespace drogon_model
{
namespace UEAdminAPI
{
class MfaChannels;

class MfaRecords
{
  public:
    struct Cols
    {
        static const std::string _id;
        static const std::string _mfa_code;
        static const std::string _mfa_target;
        static const std::string _mfa_channel_id;
        static const std::string _mfa_type;
        static const std::string _expire_at;
    };

    static const int primaryKeyNumber;
    static const std::string tableName;
    static const bool hasPrimaryKey;
    static const std::string primaryKeyName;
    using PrimaryKeyType = int32_t;
    const PrimaryKeyType &getPrimaryKey() const;

    /**
     * @brief constructor
     * @param r One row of records in the SQL query result.
     * @param indexOffset Set the offset to -1 to access all columns by column names,
     * otherwise access all columns by offsets.
     * @note If the SQL is not a style of 'select * from table_name ...' (select all
     * columns by an asterisk), please set the offset to -1.
     */
    explicit MfaRecords(const drogon::orm::Row &r, const ssize_t indexOffset = 0) noexcept;

    /**
     * @brief constructor
     * @param pJson The json object to construct a new instance.
     */
    explicit MfaRecords(const Json::Value &pJson) noexcept(false);

    /**
     * @brief constructor
     * @param pJson The json object to construct a new instance.
     * @param pMasqueradingVector The aliases of table columns.
     */
    MfaRecords(const Json::Value &pJson, const std::vector<std::string> &pMasqueradingVector) noexcept(false);

    MfaRecords() = default;

    void updateByJson(const Json::Value &pJson) noexcept(false);
    void updateByMasqueradedJson(const Json::Value &pJson,
                                 const std::vector<std::string> &pMasqueradingVector) noexcept(false);
    static bool validateJsonForCreation(const Json::Value &pJson, std::string &err);
    static bool validateMasqueradedJsonForCreation(const Json::Value &,
                                                const std::vector<std::string> &pMasqueradingVector,
                                                    std::string &err);
    static bool validateJsonForUpdate(const Json::Value &pJson, std::string &err);
    static bool validateMasqueradedJsonForUpdate(const Json::Value &,
                                          const std::vector<std::string> &pMasqueradingVector,
                                          std::string &err);
    static bool validJsonOfField(size_t index,
                          const std::string &fieldName,
                          const Json::Value &pJson,
                          std::string &err,
                          bool isForCreation);

    /**  For column id  */
    ///Get the value of the column id, returns the default value if the column is null
    const int32_t &getValueOfId() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<int32_t> &getId() const noexcept;
    ///Set the value of the column id
    void setId(const int32_t &pId) noexcept;

    /**  For column mfa_code  */
    ///Get the value of the column mfa_code, returns the default value if the column is null
    const std::string &getValueOfMfaCode() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getMfaCode() const noexcept;
    ///Set the value of the column mfa_code
    void setMfaCode(const std::string &pMfaCode) noexcept;
    void setMfaCode(std::string &&pMfaCode) noexcept;

    /**  For column mfa_target  */
    ///Get the value of the column mfa_target, returns the default value if the column is null
    const std::string &getValueOfMfaTarget() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getMfaTarget() const noexcept;
    ///Set the value of the column mfa_target
    void setMfaTarget(const std::string &pMfaTarget) noexcept;
    void setMfaTarget(std::string &&pMfaTarget) noexcept;

    /**  For column mfa_channel_id  */
    ///Get the value of the column mfa_channel_id, returns the default value if the column is null
    const int32_t &getValueOfMfaChannelId() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<int32_t> &getMfaChannelId() const noexcept;
    ///Set the value of the column mfa_channel_id
    void setMfaChannelId(const int32_t &pMfaChannelId) noexcept;

    /**  For column mfa_type  */
    ///Get the value of the column mfa_type, returns the default value if the column is null
    const int32_t &getValueOfMfaType() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<int32_t> &getMfaType() const noexcept;
    ///Set the value of the column mfa_type
    void setMfaType(const int32_t &pMfaType) noexcept;

    /**  For column expire_at  */
    ///Get the value of the column expire_at, returns the default value if the column is null
    const ::trantor::Date &getValueOfExpireAt() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<::trantor::Date> &getExpireAt() const noexcept;
    ///Set the value of the column expire_at
    void setExpireAt(const ::trantor::Date &pExpireAt) noexcept;


    static size_t getColumnNumber() noexcept {  return 6;  }
    static const std::string &getColumnName(size_t index) noexcept(false);

    Json::Value toJson() const;
    Json::Value toMasqueradedJson(const std::vector<std::string> &pMasqueradingVector) const;
    /// Relationship interfaces
    MfaChannels getMfa_channels(const drogon::orm::DbClientPtr &clientPtr) const;
    void getMfa_channels(const drogon::orm::DbClientPtr &clientPtr,
                         const std::function<void(MfaChannels)> &rcb,
                         const drogon::orm::ExceptionCallback &ecb) const;
  private:
    friend drogon::orm::Mapper<MfaRecords>;
    friend drogon::orm::BaseBuilder<MfaRecords, true, true>;
    friend drogon::orm::BaseBuilder<MfaRecords, true, false>;
    friend drogon::orm::BaseBuilder<MfaRecords, false, true>;
    friend drogon::orm::BaseBuilder<MfaRecords, false, false>;
#ifdef __cpp_impl_coroutine
    friend drogon::orm::CoroMapper<MfaRecords>;
#endif
    static const std::vector<std::string> &insertColumns() noexcept;
    void outputArgs(drogon::orm::internal::SqlBinder &binder) const;
    const std::vector<std::string> updateColumns() const;
    void updateArgs(drogon::orm::internal::SqlBinder &binder) const;
    ///For mysql or sqlite3
    void updateId(const uint64_t id);
    std::shared_ptr<int32_t> id_;
    std::shared_ptr<std::string> mfaCode_;
    std::shared_ptr<std::string> mfaTarget_;
    std::shared_ptr<int32_t> mfaChannelId_;
    std::shared_ptr<int32_t> mfaType_;
    std::shared_ptr<::trantor::Date> expireAt_;
    struct MetaData
    {
        const std::string colName_;
        const std::string colType_;
        const std::string colDatabaseType_;
        const ssize_t colLength_;
        const bool isAutoVal_;
        const bool isPrimaryKey_;
        const bool notNull_;
    };
    static const std::vector<MetaData> metaData_;
    bool dirtyFlag_[6]={ false };
  public:
    static const std::string &sqlForFindingByPrimaryKey()
    {
        static const std::string sql="select * from " + tableName + " where id = $1";
        return sql;
    }

    static const std::string &sqlForDeletingByPrimaryKey()
    {
        static const std::string sql="delete from " + tableName + " where id = $1";
        return sql;
    }
    std::string sqlForInserting(bool &needSelection) const
    {
        std::string sql="insert into " + tableName + " (";
        size_t parametersCount = 0;
        needSelection = false;
            sql += "id,";
            ++parametersCount;
        if(dirtyFlag_[1])
        {
            sql += "mfa_code,";
            ++parametersCount;
        }
        if(dirtyFlag_[2])
        {
            sql += "mfa_target,";
            ++parametersCount;
        }
        if(dirtyFlag_[3])
        {
            sql += "mfa_channel_id,";
            ++parametersCount;
        }
        if(dirtyFlag_[4])
        {
            sql += "mfa_type,";
            ++parametersCount;
        }
        if(dirtyFlag_[5])
        {
            sql += "expire_at,";
            ++parametersCount;
        }
        needSelection=true;
        if(parametersCount > 0)
        {
            sql[sql.length()-1]=')';
            sql += " values (";
        }
        else
            sql += ") values (";

        int placeholder=1;
        char placeholderStr[64];
        size_t n=0;
        sql +="default,";
        if(dirtyFlag_[1])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[2])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[3])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[4])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[5])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(parametersCount > 0)
        {
            sql.resize(sql.length() - 1);
        }
        if(needSelection)
        {
            sql.append(") returning *");
        }
        else
        {
            sql.append(1, ')');
        }
        LOG_TRACE << sql;
        return sql;
    }
};
} // namespace UEAdminAPI
} // namespace drogon_model
