/**
 *
 *  MfaRecords.cc
 *  DO NOT EDIT. This file is generated by drogon_ctl
 *
 */

#include "MfaRecords.h"
#include "MfaChannels.h"
#include <drogon/utils/Utilities.h>
#include <string>

using namespace drogon;
using namespace drogon::orm;
using namespace drogon_model::UEAdminAPI;

const std::string MfaRecords::Cols::_id = "\"id\"";
const std::string MfaRecords::Cols::_mfa_code = "\"mfa_code\"";
const std::string MfaRecords::Cols::_mfa_target = "\"mfa_target\"";
const std::string MfaRecords::Cols::_mfa_channel_id = "\"mfa_channel_id\"";
const std::string MfaRecords::Cols::_mfa_type = "\"mfa_type\"";
const std::string MfaRecords::Cols::_expire_at = "\"expire_at\"";
const std::string MfaRecords::primaryKeyName = "id";
const bool MfaRecords::hasPrimaryKey = true;
const std::string MfaRecords::tableName = "\"mfa_records\"";

const std::vector<typename MfaRecords::MetaData> MfaRecords::metaData_={
{"id","int32_t","integer",4,1,1,1},
{"mfa_code","std::string","character varying",6,0,0,1},
{"mfa_target","std::string","character varying",255,0,0,1},
{"mfa_channel_id","int32_t","integer",4,0,0,1},
{"mfa_type","int32_t","integer",4,0,0,1},
{"expire_at","::trantor::Date","timestamp with time zone",0,0,0,1}
};
const std::string &MfaRecords::getColumnName(size_t index) noexcept(false)
{
    assert(index < metaData_.size());
    return metaData_[index].colName_;
}
MfaRecords::MfaRecords(const Row &r, const ssize_t indexOffset) noexcept
{
    if(indexOffset < 0)
    {
        if(!r["id"].isNull())
        {
            id_=std::make_shared<int32_t>(r["id"].as<int32_t>());
        }
        if(!r["mfa_code"].isNull())
        {
            mfaCode_=std::make_shared<std::string>(r["mfa_code"].as<std::string>());
        }
        if(!r["mfa_target"].isNull())
        {
            mfaTarget_=std::make_shared<std::string>(r["mfa_target"].as<std::string>());
        }
        if(!r["mfa_channel_id"].isNull())
        {
            mfaChannelId_=std::make_shared<int32_t>(r["mfa_channel_id"].as<int32_t>());
        }
        if(!r["mfa_type"].isNull())
        {
            mfaType_=std::make_shared<int32_t>(r["mfa_type"].as<int32_t>());
        }
        if(!r["expire_at"].isNull())
        {
            auto timeStr = r["expire_at"].as<std::string>();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                expireAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
    else
    {
        size_t offset = (size_t)indexOffset;
        if(offset + 6 > r.size())
        {
            LOG_FATAL << "Invalid SQL result for this model";
            return;
        }
        size_t index;
        index = offset + 0;
        if(!r[index].isNull())
        {
            id_=std::make_shared<int32_t>(r[index].as<int32_t>());
        }
        index = offset + 1;
        if(!r[index].isNull())
        {
            mfaCode_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 2;
        if(!r[index].isNull())
        {
            mfaTarget_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 3;
        if(!r[index].isNull())
        {
            mfaChannelId_=std::make_shared<int32_t>(r[index].as<int32_t>());
        }
        index = offset + 4;
        if(!r[index].isNull())
        {
            mfaType_=std::make_shared<int32_t>(r[index].as<int32_t>());
        }
        index = offset + 5;
        if(!r[index].isNull())
        {
            auto timeStr = r[index].as<std::string>();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                expireAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }

}

MfaRecords::MfaRecords(const Json::Value &pJson, const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 6)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        dirtyFlag_[0] = true;
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            id_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[0]].asInt64());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        dirtyFlag_[1] = true;
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            mfaCode_=std::make_shared<std::string>(pJson[pMasqueradingVector[1]].asString());
        }
    }
    if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
    {
        dirtyFlag_[2] = true;
        if(!pJson[pMasqueradingVector[2]].isNull())
        {
            mfaTarget_=std::make_shared<std::string>(pJson[pMasqueradingVector[2]].asString());
        }
    }
    if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
    {
        dirtyFlag_[3] = true;
        if(!pJson[pMasqueradingVector[3]].isNull())
        {
            mfaChannelId_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[3]].asInt64());
        }
    }
    if(!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
    {
        dirtyFlag_[4] = true;
        if(!pJson[pMasqueradingVector[4]].isNull())
        {
            mfaType_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[4]].asInt64());
        }
    }
    if(!pMasqueradingVector[5].empty() && pJson.isMember(pMasqueradingVector[5]))
    {
        dirtyFlag_[5] = true;
        if(!pJson[pMasqueradingVector[5]].isNull())
        {
            auto timeStr = pJson[pMasqueradingVector[5]].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                expireAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
}

MfaRecords::MfaRecords(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("id"))
    {
        dirtyFlag_[0]=true;
        if(!pJson["id"].isNull())
        {
            id_=std::make_shared<int32_t>((int32_t)pJson["id"].asInt64());
        }
    }
    if(pJson.isMember("mfa_code"))
    {
        dirtyFlag_[1]=true;
        if(!pJson["mfa_code"].isNull())
        {
            mfaCode_=std::make_shared<std::string>(pJson["mfa_code"].asString());
        }
    }
    if(pJson.isMember("mfa_target"))
    {
        dirtyFlag_[2]=true;
        if(!pJson["mfa_target"].isNull())
        {
            mfaTarget_=std::make_shared<std::string>(pJson["mfa_target"].asString());
        }
    }
    if(pJson.isMember("mfa_channel_id"))
    {
        dirtyFlag_[3]=true;
        if(!pJson["mfa_channel_id"].isNull())
        {
            mfaChannelId_=std::make_shared<int32_t>((int32_t)pJson["mfa_channel_id"].asInt64());
        }
    }
    if(pJson.isMember("mfa_type"))
    {
        dirtyFlag_[4]=true;
        if(!pJson["mfa_type"].isNull())
        {
            mfaType_=std::make_shared<int32_t>((int32_t)pJson["mfa_type"].asInt64());
        }
    }
    if(pJson.isMember("expire_at"))
    {
        dirtyFlag_[5]=true;
        if(!pJson["expire_at"].isNull())
        {
            auto timeStr = pJson["expire_at"].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                expireAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
}

void MfaRecords::updateByMasqueradedJson(const Json::Value &pJson,
                                            const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 6)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            id_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[0]].asInt64());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        dirtyFlag_[1] = true;
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            mfaCode_=std::make_shared<std::string>(pJson[pMasqueradingVector[1]].asString());
        }
    }
    if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
    {
        dirtyFlag_[2] = true;
        if(!pJson[pMasqueradingVector[2]].isNull())
        {
            mfaTarget_=std::make_shared<std::string>(pJson[pMasqueradingVector[2]].asString());
        }
    }
    if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
    {
        dirtyFlag_[3] = true;
        if(!pJson[pMasqueradingVector[3]].isNull())
        {
            mfaChannelId_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[3]].asInt64());
        }
    }
    if(!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
    {
        dirtyFlag_[4] = true;
        if(!pJson[pMasqueradingVector[4]].isNull())
        {
            mfaType_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[4]].asInt64());
        }
    }
    if(!pMasqueradingVector[5].empty() && pJson.isMember(pMasqueradingVector[5]))
    {
        dirtyFlag_[5] = true;
        if(!pJson[pMasqueradingVector[5]].isNull())
        {
            auto timeStr = pJson[pMasqueradingVector[5]].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                expireAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
}

void MfaRecords::updateByJson(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("id"))
    {
        if(!pJson["id"].isNull())
        {
            id_=std::make_shared<int32_t>((int32_t)pJson["id"].asInt64());
        }
    }
    if(pJson.isMember("mfa_code"))
    {
        dirtyFlag_[1] = true;
        if(!pJson["mfa_code"].isNull())
        {
            mfaCode_=std::make_shared<std::string>(pJson["mfa_code"].asString());
        }
    }
    if(pJson.isMember("mfa_target"))
    {
        dirtyFlag_[2] = true;
        if(!pJson["mfa_target"].isNull())
        {
            mfaTarget_=std::make_shared<std::string>(pJson["mfa_target"].asString());
        }
    }
    if(pJson.isMember("mfa_channel_id"))
    {
        dirtyFlag_[3] = true;
        if(!pJson["mfa_channel_id"].isNull())
        {
            mfaChannelId_=std::make_shared<int32_t>((int32_t)pJson["mfa_channel_id"].asInt64());
        }
    }
    if(pJson.isMember("mfa_type"))
    {
        dirtyFlag_[4] = true;
        if(!pJson["mfa_type"].isNull())
        {
            mfaType_=std::make_shared<int32_t>((int32_t)pJson["mfa_type"].asInt64());
        }
    }
    if(pJson.isMember("expire_at"))
    {
        dirtyFlag_[5] = true;
        if(!pJson["expire_at"].isNull())
        {
            auto timeStr = pJson["expire_at"].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                expireAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
}

const int32_t &MfaRecords::getValueOfId() const noexcept
{
    static const int32_t defaultValue = int32_t();
    if(id_)
        return *id_;
    return defaultValue;
}
const std::shared_ptr<int32_t> &MfaRecords::getId() const noexcept
{
    return id_;
}
void MfaRecords::setId(const int32_t &pId) noexcept
{
    id_ = std::make_shared<int32_t>(pId);
    dirtyFlag_[0] = true;
}
const typename MfaRecords::PrimaryKeyType & MfaRecords::getPrimaryKey() const
{
    assert(id_);
    return *id_;
}

const std::string &MfaRecords::getValueOfMfaCode() const noexcept
{
    static const std::string defaultValue = std::string();
    if(mfaCode_)
        return *mfaCode_;
    return defaultValue;
}
const std::shared_ptr<std::string> &MfaRecords::getMfaCode() const noexcept
{
    return mfaCode_;
}
void MfaRecords::setMfaCode(const std::string &pMfaCode) noexcept
{
    mfaCode_ = std::make_shared<std::string>(pMfaCode);
    dirtyFlag_[1] = true;
}
void MfaRecords::setMfaCode(std::string &&pMfaCode) noexcept
{
    mfaCode_ = std::make_shared<std::string>(std::move(pMfaCode));
    dirtyFlag_[1] = true;
}

const std::string &MfaRecords::getValueOfMfaTarget() const noexcept
{
    static const std::string defaultValue = std::string();
    if(mfaTarget_)
        return *mfaTarget_;
    return defaultValue;
}
const std::shared_ptr<std::string> &MfaRecords::getMfaTarget() const noexcept
{
    return mfaTarget_;
}
void MfaRecords::setMfaTarget(const std::string &pMfaTarget) noexcept
{
    mfaTarget_ = std::make_shared<std::string>(pMfaTarget);
    dirtyFlag_[2] = true;
}
void MfaRecords::setMfaTarget(std::string &&pMfaTarget) noexcept
{
    mfaTarget_ = std::make_shared<std::string>(std::move(pMfaTarget));
    dirtyFlag_[2] = true;
}

const int32_t &MfaRecords::getValueOfMfaChannelId() const noexcept
{
    static const int32_t defaultValue = int32_t();
    if(mfaChannelId_)
        return *mfaChannelId_;
    return defaultValue;
}
const std::shared_ptr<int32_t> &MfaRecords::getMfaChannelId() const noexcept
{
    return mfaChannelId_;
}
void MfaRecords::setMfaChannelId(const int32_t &pMfaChannelId) noexcept
{
    mfaChannelId_ = std::make_shared<int32_t>(pMfaChannelId);
    dirtyFlag_[3] = true;
}

const int32_t &MfaRecords::getValueOfMfaType() const noexcept
{
    static const int32_t defaultValue = int32_t();
    if(mfaType_)
        return *mfaType_;
    return defaultValue;
}
const std::shared_ptr<int32_t> &MfaRecords::getMfaType() const noexcept
{
    return mfaType_;
}
void MfaRecords::setMfaType(const int32_t &pMfaType) noexcept
{
    mfaType_ = std::make_shared<int32_t>(pMfaType);
    dirtyFlag_[4] = true;
}

const ::trantor::Date &MfaRecords::getValueOfExpireAt() const noexcept
{
    static const ::trantor::Date defaultValue = ::trantor::Date();
    if(expireAt_)
        return *expireAt_;
    return defaultValue;
}
const std::shared_ptr<::trantor::Date> &MfaRecords::getExpireAt() const noexcept
{
    return expireAt_;
}
void MfaRecords::setExpireAt(const ::trantor::Date &pExpireAt) noexcept
{
    expireAt_ = std::make_shared<::trantor::Date>(pExpireAt);
    dirtyFlag_[5] = true;
}

void MfaRecords::updateId(const uint64_t id)
{
}

const std::vector<std::string> &MfaRecords::insertColumns() noexcept
{
    static const std::vector<std::string> inCols={
        "mfa_code",
        "mfa_target",
        "mfa_channel_id",
        "mfa_type",
        "expire_at"
    };
    return inCols;
}

void MfaRecords::outputArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[1])
    {
        if(getMfaCode())
        {
            binder << getValueOfMfaCode();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[2])
    {
        if(getMfaTarget())
        {
            binder << getValueOfMfaTarget();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[3])
    {
        if(getMfaChannelId())
        {
            binder << getValueOfMfaChannelId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[4])
    {
        if(getMfaType())
        {
            binder << getValueOfMfaType();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[5])
    {
        if(getExpireAt())
        {
            binder << getValueOfExpireAt();
        }
        else
        {
            binder << nullptr;
        }
    }
}

const std::vector<std::string> MfaRecords::updateColumns() const
{
    std::vector<std::string> ret;
    if(dirtyFlag_[1])
    {
        ret.push_back(getColumnName(1));
    }
    if(dirtyFlag_[2])
    {
        ret.push_back(getColumnName(2));
    }
    if(dirtyFlag_[3])
    {
        ret.push_back(getColumnName(3));
    }
    if(dirtyFlag_[4])
    {
        ret.push_back(getColumnName(4));
    }
    if(dirtyFlag_[5])
    {
        ret.push_back(getColumnName(5));
    }
    return ret;
}

void MfaRecords::updateArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[1])
    {
        if(getMfaCode())
        {
            binder << getValueOfMfaCode();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[2])
    {
        if(getMfaTarget())
        {
            binder << getValueOfMfaTarget();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[3])
    {
        if(getMfaChannelId())
        {
            binder << getValueOfMfaChannelId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[4])
    {
        if(getMfaType())
        {
            binder << getValueOfMfaType();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[5])
    {
        if(getExpireAt())
        {
            binder << getValueOfExpireAt();
        }
        else
        {
            binder << nullptr;
        }
    }
}
Json::Value MfaRecords::toJson() const
{
    Json::Value ret;
    if(getId())
    {
        ret["id"]=getValueOfId();
    }
    else
    {
        ret["id"]=Json::Value();
    }
    if(getMfaCode())
    {
        ret["mfa_code"]=getValueOfMfaCode();
    }
    else
    {
        ret["mfa_code"]=Json::Value();
    }
    if(getMfaTarget())
    {
        ret["mfa_target"]=getValueOfMfaTarget();
    }
    else
    {
        ret["mfa_target"]=Json::Value();
    }
    if(getMfaChannelId())
    {
        ret["mfa_channel_id"]=getValueOfMfaChannelId();
    }
    else
    {
        ret["mfa_channel_id"]=Json::Value();
    }
    if(getMfaType())
    {
        ret["mfa_type"]=getValueOfMfaType();
    }
    else
    {
        ret["mfa_type"]=Json::Value();
    }
    if(getExpireAt())
    {
        ret["expire_at"]=getExpireAt()->toDbStringLocal();
    }
    else
    {
        ret["expire_at"]=Json::Value();
    }
    return ret;
}

Json::Value MfaRecords::toMasqueradedJson(
    const std::vector<std::string> &pMasqueradingVector) const
{
    Json::Value ret;
    if(pMasqueradingVector.size() == 6)
    {
        if(!pMasqueradingVector[0].empty())
        {
            if(getId())
            {
                ret[pMasqueradingVector[0]]=getValueOfId();
            }
            else
            {
                ret[pMasqueradingVector[0]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[1].empty())
        {
            if(getMfaCode())
            {
                ret[pMasqueradingVector[1]]=getValueOfMfaCode();
            }
            else
            {
                ret[pMasqueradingVector[1]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[2].empty())
        {
            if(getMfaTarget())
            {
                ret[pMasqueradingVector[2]]=getValueOfMfaTarget();
            }
            else
            {
                ret[pMasqueradingVector[2]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[3].empty())
        {
            if(getMfaChannelId())
            {
                ret[pMasqueradingVector[3]]=getValueOfMfaChannelId();
            }
            else
            {
                ret[pMasqueradingVector[3]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[4].empty())
        {
            if(getMfaType())
            {
                ret[pMasqueradingVector[4]]=getValueOfMfaType();
            }
            else
            {
                ret[pMasqueradingVector[4]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[5].empty())
        {
            if(getExpireAt())
            {
                ret[pMasqueradingVector[5]]=getExpireAt()->toDbStringLocal();
            }
            else
            {
                ret[pMasqueradingVector[5]]=Json::Value();
            }
        }
        return ret;
    }
    LOG_ERROR << "Masquerade failed";
    if(getId())
    {
        ret["id"]=getValueOfId();
    }
    else
    {
        ret["id"]=Json::Value();
    }
    if(getMfaCode())
    {
        ret["mfa_code"]=getValueOfMfaCode();
    }
    else
    {
        ret["mfa_code"]=Json::Value();
    }
    if(getMfaTarget())
    {
        ret["mfa_target"]=getValueOfMfaTarget();
    }
    else
    {
        ret["mfa_target"]=Json::Value();
    }
    if(getMfaChannelId())
    {
        ret["mfa_channel_id"]=getValueOfMfaChannelId();
    }
    else
    {
        ret["mfa_channel_id"]=Json::Value();
    }
    if(getMfaType())
    {
        ret["mfa_type"]=getValueOfMfaType();
    }
    else
    {
        ret["mfa_type"]=Json::Value();
    }
    if(getExpireAt())
    {
        ret["expire_at"]=getExpireAt()->toDbStringLocal();
    }
    else
    {
        ret["expire_at"]=Json::Value();
    }
    return ret;
}

bool MfaRecords::validateJsonForCreation(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("id"))
    {
        if(!validJsonOfField(0, "id", pJson["id"], err, true))
            return false;
    }
    if(pJson.isMember("mfa_code"))
    {
        if(!validJsonOfField(1, "mfa_code", pJson["mfa_code"], err, true))
            return false;
    }
    else
    {
        err="The mfa_code column cannot be null";
        return false;
    }
    if(pJson.isMember("mfa_target"))
    {
        if(!validJsonOfField(2, "mfa_target", pJson["mfa_target"], err, true))
            return false;
    }
    else
    {
        err="The mfa_target column cannot be null";
        return false;
    }
    if(pJson.isMember("mfa_channel_id"))
    {
        if(!validJsonOfField(3, "mfa_channel_id", pJson["mfa_channel_id"], err, true))
            return false;
    }
    else
    {
        err="The mfa_channel_id column cannot be null";
        return false;
    }
    if(pJson.isMember("mfa_type"))
    {
        if(!validJsonOfField(4, "mfa_type", pJson["mfa_type"], err, true))
            return false;
    }
    else
    {
        err="The mfa_type column cannot be null";
        return false;
    }
    if(pJson.isMember("expire_at"))
    {
        if(!validJsonOfField(5, "expire_at", pJson["expire_at"], err, true))
            return false;
    }
    else
    {
        err="The expire_at column cannot be null";
        return false;
    }
    return true;
}
bool MfaRecords::validateMasqueradedJsonForCreation(const Json::Value &pJson,
                                                    const std::vector<std::string> &pMasqueradingVector,
                                                    std::string &err)
{
    if(pMasqueradingVector.size() != 6)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty())
      {
          if(pJson.isMember(pMasqueradingVector[0]))
          {
              if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[1].empty())
      {
          if(pJson.isMember(pMasqueradingVector[1]))
          {
              if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[1] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[2].empty())
      {
          if(pJson.isMember(pMasqueradingVector[2]))
          {
              if(!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[2] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[3].empty())
      {
          if(pJson.isMember(pMasqueradingVector[3]))
          {
              if(!validJsonOfField(3, pMasqueradingVector[3], pJson[pMasqueradingVector[3]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[3] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[4].empty())
      {
          if(pJson.isMember(pMasqueradingVector[4]))
          {
              if(!validJsonOfField(4, pMasqueradingVector[4], pJson[pMasqueradingVector[4]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[4] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[5].empty())
      {
          if(pJson.isMember(pMasqueradingVector[5]))
          {
              if(!validJsonOfField(5, pMasqueradingVector[5], pJson[pMasqueradingVector[5]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[5] + " column cannot be null";
            return false;
        }
      }
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool MfaRecords::validateJsonForUpdate(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("id"))
    {
        if(!validJsonOfField(0, "id", pJson["id"], err, false))
            return false;
    }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
    if(pJson.isMember("mfa_code"))
    {
        if(!validJsonOfField(1, "mfa_code", pJson["mfa_code"], err, false))
            return false;
    }
    if(pJson.isMember("mfa_target"))
    {
        if(!validJsonOfField(2, "mfa_target", pJson["mfa_target"], err, false))
            return false;
    }
    if(pJson.isMember("mfa_channel_id"))
    {
        if(!validJsonOfField(3, "mfa_channel_id", pJson["mfa_channel_id"], err, false))
            return false;
    }
    if(pJson.isMember("mfa_type"))
    {
        if(!validJsonOfField(4, "mfa_type", pJson["mfa_type"], err, false))
            return false;
    }
    if(pJson.isMember("expire_at"))
    {
        if(!validJsonOfField(5, "expire_at", pJson["expire_at"], err, false))
            return false;
    }
    return true;
}
bool MfaRecords::validateMasqueradedJsonForUpdate(const Json::Value &pJson,
                                                  const std::vector<std::string> &pMasqueradingVector,
                                                  std::string &err)
{
    if(pMasqueradingVector.size() != 6)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
      {
          if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, false))
              return false;
      }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
      if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
      {
          if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, false))
              return false;
      }
      if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
      {
          if(!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err, false))
              return false;
      }
      if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
      {
          if(!validJsonOfField(3, pMasqueradingVector[3], pJson[pMasqueradingVector[3]], err, false))
              return false;
      }
      if(!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
      {
          if(!validJsonOfField(4, pMasqueradingVector[4], pJson[pMasqueradingVector[4]], err, false))
              return false;
      }
      if(!pMasqueradingVector[5].empty() && pJson.isMember(pMasqueradingVector[5]))
      {
          if(!validJsonOfField(5, pMasqueradingVector[5], pJson[pMasqueradingVector[5]], err, false))
              return false;
      }
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool MfaRecords::validJsonOfField(size_t index,
                                  const std::string &fieldName,
                                  const Json::Value &pJson,
                                  std::string &err,
                                  bool isForCreation)
{
    switch(index)
    {
        case 0:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(isForCreation)
            {
                err="The automatic primary key cannot be set";
                return false;
            }
            if(!pJson.isInt())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 1:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            if(pJson.isString() && std::strlen(pJson.asCString()) > 6)
            {
                err="String length exceeds limit for the " +
                    fieldName +
                    " field (the maximum value is 6)";
                return false;
            }

            break;
        case 2:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            if(pJson.isString() && std::strlen(pJson.asCString()) > 255)
            {
                err="String length exceeds limit for the " +
                    fieldName +
                    " field (the maximum value is 255)";
                return false;
            }

            break;
        case 3:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isInt())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 4:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isInt())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 5:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        default:
            err="Internal error in the server";
            return false;
    }
    return true;
}
MfaChannels MfaRecords::getMfa_channels(const DbClientPtr &clientPtr) const {
    static const std::string sql = "select * from mfa_channels where Id = $1";
    Result r(nullptr);
    {
        auto binder = *clientPtr << sql;
        binder << *mfaChannelId_ << Mode::Blocking >>
            [&r](const Result &result) { r = result; };
        binder.exec();
    }
    if (r.size() == 0)
    {
        throw UnexpectedRows("0 rows found");
    }
    else if (r.size() > 1)
    {
        throw UnexpectedRows("Found more than one row");
    }
    return MfaChannels(r[0]);
}

void MfaRecords::getMfa_channels(const DbClientPtr &clientPtr,
                                 const std::function<void(MfaChannels)> &rcb,
                                 const ExceptionCallback &ecb) const
{
    static const std::string sql = "select * from mfa_channels where Id = $1";
    *clientPtr << sql
               << *mfaChannelId_
               >> [rcb = std::move(rcb), ecb](const Result &r){
                    if (r.size() == 0)
                    {
                        ecb(UnexpectedRows("0 rows found"));
                    }
                    else if (r.size() > 1)
                    {
                        ecb(UnexpectedRows("Found more than one row"));
                    }
                    else
                    {
                        rcb(MfaChannels(r[0]));
                    }
               }
               >> ecb;
}
