/**
 *
 *  ThirdPartyPlatforms.cc
 *  DO NOT EDIT. This file is generated by drogon_ctl
 *
 */

#include "ThirdPartyPlatforms.h"
#include "User.h"
#include "UserThirdPartyInfo.h"
#include <drogon/utils/Utilities.h>
#include <codecvt>
#include <string>

using namespace drogon;
using namespace drogon::orm;
using namespace drogon_model::UEAdminAPI;

const std::string ThirdPartyPlatforms::Cols::_id = "\"id\"";
const std::string ThirdPartyPlatforms::Cols::_platform_name = "\"platform_name\"";
const std::string ThirdPartyPlatforms::primaryKeyName = "id";
const bool ThirdPartyPlatforms::hasPrimaryKey = true;
const std::string ThirdPartyPlatforms::tableName = "\"third_party_platforms\"";

const std::vector<typename ThirdPartyPlatforms::MetaData> ThirdPartyPlatforms::metaData_={
{"id","int32_t","integer",4,1,1,1},
{"platform_name","std::string","character varying",20,0,0,1}
};
const std::string &ThirdPartyPlatforms::getColumnName(size_t index) noexcept(false)
{
    assert(index < metaData_.size());
    return metaData_[index].colName_;
}
ThirdPartyPlatforms::ThirdPartyPlatforms(const Row &r, const ssize_t indexOffset) noexcept
{
    if(indexOffset < 0)
    {
        if(!r["id"].isNull())
        {
            id_=std::make_shared<int32_t>(r["id"].as<int32_t>());
        }
        if(!r["platform_name"].isNull())
        {
            platformName_=std::make_shared<std::string>(r["platform_name"].as<std::string>());
        }
    }
    else
    {
        size_t offset = (size_t)indexOffset;
        if(offset + 2 > r.size())
        {
            LOG_FATAL << "Invalid SQL result for this model";
            return;
        }
        size_t index;
        index = offset + 0;
        if(!r[index].isNull())
        {
            id_=std::make_shared<int32_t>(r[index].as<int32_t>());
        }
        index = offset + 1;
        if(!r[index].isNull())
        {
            platformName_=std::make_shared<std::string>(r[index].as<std::string>());
        }
    }

}

ThirdPartyPlatforms::ThirdPartyPlatforms(const Json::Value &pJson, const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 2)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        dirtyFlag_[0] = true;
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            id_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[0]].asInt64());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        dirtyFlag_[1] = true;
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            platformName_=std::make_shared<std::string>(pJson[pMasqueradingVector[1]].asString());
        }
    }
}

ThirdPartyPlatforms::ThirdPartyPlatforms(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("id"))
    {
        dirtyFlag_[0]=true;
        if(!pJson["id"].isNull())
        {
            id_=std::make_shared<int32_t>((int32_t)pJson["id"].asInt64());
        }
    }
    if(pJson.isMember("platform_name"))
    {
        dirtyFlag_[1]=true;
        if(!pJson["platform_name"].isNull())
        {
            platformName_=std::make_shared<std::string>(pJson["platform_name"].asString());
        }
    }
}

void ThirdPartyPlatforms::updateByMasqueradedJson(const Json::Value &pJson,
                                            const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 2)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            id_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[0]].asInt64());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        dirtyFlag_[1] = true;
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            platformName_=std::make_shared<std::string>(pJson[pMasqueradingVector[1]].asString());
        }
    }
}

void ThirdPartyPlatforms::updateByJson(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("id"))
    {
        if(!pJson["id"].isNull())
        {
            id_=std::make_shared<int32_t>((int32_t)pJson["id"].asInt64());
        }
    }
    if(pJson.isMember("platform_name"))
    {
        dirtyFlag_[1] = true;
        if(!pJson["platform_name"].isNull())
        {
            platformName_=std::make_shared<std::string>(pJson["platform_name"].asString());
        }
    }
}

const int32_t &ThirdPartyPlatforms::getValueOfId() const noexcept
{
    static const int32_t defaultValue = int32_t();
    if(id_)
        return *id_;
    return defaultValue;
}
const std::shared_ptr<int32_t> &ThirdPartyPlatforms::getId() const noexcept
{
    return id_;
}
void ThirdPartyPlatforms::setId(const int32_t &pId) noexcept
{
    id_ = std::make_shared<int32_t>(pId);
    dirtyFlag_[0] = true;
}
const typename ThirdPartyPlatforms::PrimaryKeyType & ThirdPartyPlatforms::getPrimaryKey() const
{
    assert(id_);
    return *id_;
}

const std::string &ThirdPartyPlatforms::getValueOfPlatformName() const noexcept
{
    static const std::string defaultValue = std::string();
    if(platformName_)
        return *platformName_;
    return defaultValue;
}
const std::shared_ptr<std::string> &ThirdPartyPlatforms::getPlatformName() const noexcept
{
    return platformName_;
}
void ThirdPartyPlatforms::setPlatformName(const std::string &pPlatformName) noexcept
{
    platformName_ = std::make_shared<std::string>(pPlatformName);
    dirtyFlag_[1] = true;
}
void ThirdPartyPlatforms::setPlatformName(std::string &&pPlatformName) noexcept
{
    platformName_ = std::make_shared<std::string>(std::move(pPlatformName));
    dirtyFlag_[1] = true;
}

void ThirdPartyPlatforms::updateId(const uint64_t id)
{
}

const std::vector<std::string> &ThirdPartyPlatforms::insertColumns() noexcept
{
    static const std::vector<std::string> inCols={
        "platform_name"
    };
    return inCols;
}

void ThirdPartyPlatforms::outputArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[1])
    {
        if(getPlatformName())
        {
            binder << getValueOfPlatformName();
        }
        else
        {
            binder << nullptr;
        }
    }
}

const std::vector<std::string> ThirdPartyPlatforms::updateColumns() const
{
    std::vector<std::string> ret;
    if(dirtyFlag_[1])
    {
        ret.push_back(getColumnName(1));
    }
    return ret;
}

void ThirdPartyPlatforms::updateArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[1])
    {
        if(getPlatformName())
        {
            binder << getValueOfPlatformName();
        }
        else
        {
            binder << nullptr;
        }
    }
}
Json::Value ThirdPartyPlatforms::toJson() const
{
    Json::Value ret;
    if(getId())
    {
        ret["id"]=getValueOfId();
    }
    else
    {
        ret["id"]=Json::Value();
    }
    if(getPlatformName())
    {
        ret["platform_name"]=getValueOfPlatformName();
    }
    else
    {
        ret["platform_name"]=Json::Value();
    }
    return ret;
}

std::string ThirdPartyPlatforms::toString() const
{
    return toJson().toStyledString();
}

Json::Value ThirdPartyPlatforms::toMasqueradedJson(
    const std::vector<std::string> &pMasqueradingVector) const
{
    Json::Value ret;
    if(pMasqueradingVector.size() == 2)
    {
        if(!pMasqueradingVector[0].empty())
        {
            if(getId())
            {
                ret[pMasqueradingVector[0]]=getValueOfId();
            }
            else
            {
                ret[pMasqueradingVector[0]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[1].empty())
        {
            if(getPlatformName())
            {
                ret[pMasqueradingVector[1]]=getValueOfPlatformName();
            }
            else
            {
                ret[pMasqueradingVector[1]]=Json::Value();
            }
        }
        return ret;
    }
    LOG_ERROR << "Masquerade failed";
    if(getId())
    {
        ret["id"]=getValueOfId();
    }
    else
    {
        ret["id"]=Json::Value();
    }
    if(getPlatformName())
    {
        ret["platform_name"]=getValueOfPlatformName();
    }
    else
    {
        ret["platform_name"]=Json::Value();
    }
    return ret;
}

bool ThirdPartyPlatforms::validateJsonForCreation(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("id"))
    {
        if(!validJsonOfField(0, "id", pJson["id"], err, true))
            return false;
    }
    if(pJson.isMember("platform_name"))
    {
        if(!validJsonOfField(1, "platform_name", pJson["platform_name"], err, true))
            return false;
    }
    else
    {
        err="The platform_name column cannot be null";
        return false;
    }
    return true;
}
bool ThirdPartyPlatforms::validateMasqueradedJsonForCreation(const Json::Value &pJson,
                                                             const std::vector<std::string> &pMasqueradingVector,
                                                             std::string &err)
{
    if(pMasqueradingVector.size() != 2)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty())
      {
          if(pJson.isMember(pMasqueradingVector[0]))
          {
              if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[1].empty())
      {
          if(pJson.isMember(pMasqueradingVector[1]))
          {
              if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[1] + " column cannot be null";
            return false;
        }
      }
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool ThirdPartyPlatforms::validateJsonForUpdate(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("id"))
    {
        if(!validJsonOfField(0, "id", pJson["id"], err, false))
            return false;
    }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
    if(pJson.isMember("platform_name"))
    {
        if(!validJsonOfField(1, "platform_name", pJson["platform_name"], err, false))
            return false;
    }
    return true;
}
bool ThirdPartyPlatforms::validateMasqueradedJsonForUpdate(const Json::Value &pJson,
                                                           const std::vector<std::string> &pMasqueradingVector,
                                                           std::string &err)
{
    if(pMasqueradingVector.size() != 2)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
      {
          if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, false))
              return false;
      }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
      if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
      {
          if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, false))
              return false;
      }
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool ThirdPartyPlatforms::validJsonOfField(size_t index,
                                           const std::string &fieldName,
                                           const Json::Value &pJson,
                                           std::string &err,
                                           bool isForCreation)
{
    switch(index)
    {
        case 0:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(isForCreation)
            {
                err="The automatic primary key cannot be set";
                return false;
            }
            if(!pJson.isInt())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 1:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            if(pJson.isString() && std::wstring_convert<std::codecvt_utf8_utf16<wchar_t>, wchar_t>{}
                .from_bytes(pJson.asCString()).size() > 20)
            {
                err="String length exceeds limit for the " +
                    fieldName +
                    " field (the maximum value is 20)";
                return false;
            }
            break;
        default:
            err="Internal error in the server";
            return false;
    }
    return true;
}
std::vector<std::pair<User,UserThirdPartyInfo>> ThirdPartyPlatforms::getUser(const DbClientPtr &clientPtr) const {
    static const std::string sql = "select * from user,user_third_party_info where user_third_party_info.platform_id = $1 and user_third_party_info.user_id = user.Id";
    Result r(nullptr);
    {
        auto binder = *clientPtr << sql;
        binder << *id_ << Mode::Blocking >>
            [&r](const Result &result) { r = result; };
        binder.exec();
    }
    std::vector<std::pair<User,UserThirdPartyInfo>> ret;
    ret.reserve(r.size());
    for (auto const &row : r)
    {
        ret.emplace_back(std::pair<User,UserThirdPartyInfo>(
            User(row),UserThirdPartyInfo(row,User::getColumnNumber())));
    }
    return ret;
}

void ThirdPartyPlatforms::getUser(const DbClientPtr &clientPtr,
                                  const std::function<void(std::vector<std::pair<User,UserThirdPartyInfo>>)> &rcb,
                                  const ExceptionCallback &ecb) const
{
    static const std::string sql = "select * from user,user_third_party_info where user_third_party_info.platform_id = $1 and user_third_party_info.user_id = user.Id";
    *clientPtr << sql
               << *id_
               >> [rcb = std::move(rcb)](const Result &r){
                   std::vector<std::pair<User,UserThirdPartyInfo>> ret;
                   ret.reserve(r.size());
                   for (auto const &row : r)
                   {
                       ret.emplace_back(std::pair<User,UserThirdPartyInfo>(
                           User(row),UserThirdPartyInfo(row,User::getColumnNumber())));
                   }
                   rcb(ret);
               }
               >> ecb;
}
