/**
 *
 *  UserFlashtoken.cc
 *  DO NOT EDIT. This file is generated by drogon_ctl
 *
 */

#include "UserFlashtoken.h"
#include "User.h"
#include <drogon/utils/Utilities.h>
#include <string>

using namespace drogon;
using namespace drogon::orm;
using namespace drogon_model::UEAdminAPI;

const std::string UserFlashtoken::Cols::_user_id = "\"user_id\"";
const std::string UserFlashtoken::Cols::_flash_token = "\"flash_token\"";
const std::string UserFlashtoken::Cols::_token_desc = "\"token_desc\"";
const std::string UserFlashtoken::Cols::_expire_at = "\"expire_at\"";
const std::string UserFlashtoken::primaryKeyName = "user_id";
const bool UserFlashtoken::hasPrimaryKey = true;
const std::string UserFlashtoken::tableName = "\"user_flashtoken\"";

const std::vector<typename UserFlashtoken::MetaData> UserFlashtoken::metaData_={
{"user_id","int32_t","integer",4,0,1,1},
{"flash_token","std::string","character varying",300,0,0,1},
{"token_desc","std::string","character varying",500,0,0,1},
{"expire_at","::trantor::Date","timestamp with time zone",0,0,0,1}
};
const std::string &UserFlashtoken::getColumnName(size_t index) noexcept(false)
{
    assert(index < metaData_.size());
    return metaData_[index].colName_;
}
UserFlashtoken::UserFlashtoken(const Row &r, const ssize_t indexOffset) noexcept
{
    if(indexOffset < 0)
    {
        if(!r["user_id"].isNull())
        {
            userId_=std::make_shared<int32_t>(r["user_id"].as<int32_t>());
        }
        if(!r["flash_token"].isNull())
        {
            flashToken_=std::make_shared<std::string>(r["flash_token"].as<std::string>());
        }
        if(!r["token_desc"].isNull())
        {
            tokenDesc_=std::make_shared<std::string>(r["token_desc"].as<std::string>());
        }
        if(!r["expire_at"].isNull())
        {
            auto timeStr = r["expire_at"].as<std::string>();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                expireAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
    else
    {
        size_t offset = (size_t)indexOffset;
        if(offset + 4 > r.size())
        {
            LOG_FATAL << "Invalid SQL result for this model";
            return;
        }
        size_t index;
        index = offset + 0;
        if(!r[index].isNull())
        {
            userId_=std::make_shared<int32_t>(r[index].as<int32_t>());
        }
        index = offset + 1;
        if(!r[index].isNull())
        {
            flashToken_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 2;
        if(!r[index].isNull())
        {
            tokenDesc_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 3;
        if(!r[index].isNull())
        {
            auto timeStr = r[index].as<std::string>();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                expireAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }

}

UserFlashtoken::UserFlashtoken(const Json::Value &pJson, const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 4)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        dirtyFlag_[0] = true;
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            userId_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[0]].asInt64());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        dirtyFlag_[1] = true;
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            flashToken_=std::make_shared<std::string>(pJson[pMasqueradingVector[1]].asString());
        }
    }
    if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
    {
        dirtyFlag_[2] = true;
        if(!pJson[pMasqueradingVector[2]].isNull())
        {
            tokenDesc_=std::make_shared<std::string>(pJson[pMasqueradingVector[2]].asString());
        }
    }
    if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
    {
        dirtyFlag_[3] = true;
        if(!pJson[pMasqueradingVector[3]].isNull())
        {
            auto timeStr = pJson[pMasqueradingVector[3]].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                expireAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
}

UserFlashtoken::UserFlashtoken(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("user_id"))
    {
        dirtyFlag_[0]=true;
        if(!pJson["user_id"].isNull())
        {
            userId_=std::make_shared<int32_t>((int32_t)pJson["user_id"].asInt64());
        }
    }
    if(pJson.isMember("flash_token"))
    {
        dirtyFlag_[1]=true;
        if(!pJson["flash_token"].isNull())
        {
            flashToken_=std::make_shared<std::string>(pJson["flash_token"].asString());
        }
    }
    if(pJson.isMember("token_desc"))
    {
        dirtyFlag_[2]=true;
        if(!pJson["token_desc"].isNull())
        {
            tokenDesc_=std::make_shared<std::string>(pJson["token_desc"].asString());
        }
    }
    if(pJson.isMember("expire_at"))
    {
        dirtyFlag_[3]=true;
        if(!pJson["expire_at"].isNull())
        {
            auto timeStr = pJson["expire_at"].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                expireAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
}

void UserFlashtoken::updateByMasqueradedJson(const Json::Value &pJson,
                                            const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 4)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            userId_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[0]].asInt64());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        dirtyFlag_[1] = true;
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            flashToken_=std::make_shared<std::string>(pJson[pMasqueradingVector[1]].asString());
        }
    }
    if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
    {
        dirtyFlag_[2] = true;
        if(!pJson[pMasqueradingVector[2]].isNull())
        {
            tokenDesc_=std::make_shared<std::string>(pJson[pMasqueradingVector[2]].asString());
        }
    }
    if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
    {
        dirtyFlag_[3] = true;
        if(!pJson[pMasqueradingVector[3]].isNull())
        {
            auto timeStr = pJson[pMasqueradingVector[3]].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                expireAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
}

void UserFlashtoken::updateByJson(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("user_id"))
    {
        if(!pJson["user_id"].isNull())
        {
            userId_=std::make_shared<int32_t>((int32_t)pJson["user_id"].asInt64());
        }
    }
    if(pJson.isMember("flash_token"))
    {
        dirtyFlag_[1] = true;
        if(!pJson["flash_token"].isNull())
        {
            flashToken_=std::make_shared<std::string>(pJson["flash_token"].asString());
        }
    }
    if(pJson.isMember("token_desc"))
    {
        dirtyFlag_[2] = true;
        if(!pJson["token_desc"].isNull())
        {
            tokenDesc_=std::make_shared<std::string>(pJson["token_desc"].asString());
        }
    }
    if(pJson.isMember("expire_at"))
    {
        dirtyFlag_[3] = true;
        if(!pJson["expire_at"].isNull())
        {
            auto timeStr = pJson["expire_at"].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                expireAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
}

const int32_t &UserFlashtoken::getValueOfUserId() const noexcept
{
    static const int32_t defaultValue = int32_t();
    if(userId_)
        return *userId_;
    return defaultValue;
}
const std::shared_ptr<int32_t> &UserFlashtoken::getUserId() const noexcept
{
    return userId_;
}
void UserFlashtoken::setUserId(const int32_t &pUserId) noexcept
{
    userId_ = std::make_shared<int32_t>(pUserId);
    dirtyFlag_[0] = true;
}
const typename UserFlashtoken::PrimaryKeyType & UserFlashtoken::getPrimaryKey() const
{
    assert(userId_);
    return *userId_;
}

const std::string &UserFlashtoken::getValueOfFlashToken() const noexcept
{
    static const std::string defaultValue = std::string();
    if(flashToken_)
        return *flashToken_;
    return defaultValue;
}
const std::shared_ptr<std::string> &UserFlashtoken::getFlashToken() const noexcept
{
    return flashToken_;
}
void UserFlashtoken::setFlashToken(const std::string &pFlashToken) noexcept
{
    flashToken_ = std::make_shared<std::string>(pFlashToken);
    dirtyFlag_[1] = true;
}
void UserFlashtoken::setFlashToken(std::string &&pFlashToken) noexcept
{
    flashToken_ = std::make_shared<std::string>(std::move(pFlashToken));
    dirtyFlag_[1] = true;
}

const std::string &UserFlashtoken::getValueOfTokenDesc() const noexcept
{
    static const std::string defaultValue = std::string();
    if(tokenDesc_)
        return *tokenDesc_;
    return defaultValue;
}
const std::shared_ptr<std::string> &UserFlashtoken::getTokenDesc() const noexcept
{
    return tokenDesc_;
}
void UserFlashtoken::setTokenDesc(const std::string &pTokenDesc) noexcept
{
    tokenDesc_ = std::make_shared<std::string>(pTokenDesc);
    dirtyFlag_[2] = true;
}
void UserFlashtoken::setTokenDesc(std::string &&pTokenDesc) noexcept
{
    tokenDesc_ = std::make_shared<std::string>(std::move(pTokenDesc));
    dirtyFlag_[2] = true;
}

const ::trantor::Date &UserFlashtoken::getValueOfExpireAt() const noexcept
{
    static const ::trantor::Date defaultValue = ::trantor::Date();
    if(expireAt_)
        return *expireAt_;
    return defaultValue;
}
const std::shared_ptr<::trantor::Date> &UserFlashtoken::getExpireAt() const noexcept
{
    return expireAt_;
}
void UserFlashtoken::setExpireAt(const ::trantor::Date &pExpireAt) noexcept
{
    expireAt_ = std::make_shared<::trantor::Date>(pExpireAt);
    dirtyFlag_[3] = true;
}

void UserFlashtoken::updateId(const uint64_t id)
{
}

const std::vector<std::string> &UserFlashtoken::insertColumns() noexcept
{
    static const std::vector<std::string> inCols={
        "user_id",
        "flash_token",
        "token_desc",
        "expire_at"
    };
    return inCols;
}

void UserFlashtoken::outputArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[0])
    {
        if(getUserId())
        {
            binder << getValueOfUserId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[1])
    {
        if(getFlashToken())
        {
            binder << getValueOfFlashToken();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[2])
    {
        if(getTokenDesc())
        {
            binder << getValueOfTokenDesc();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[3])
    {
        if(getExpireAt())
        {
            binder << getValueOfExpireAt();
        }
        else
        {
            binder << nullptr;
        }
    }
}

const std::vector<std::string> UserFlashtoken::updateColumns() const
{
    std::vector<std::string> ret;
    if(dirtyFlag_[0])
    {
        ret.push_back(getColumnName(0));
    }
    if(dirtyFlag_[1])
    {
        ret.push_back(getColumnName(1));
    }
    if(dirtyFlag_[2])
    {
        ret.push_back(getColumnName(2));
    }
    if(dirtyFlag_[3])
    {
        ret.push_back(getColumnName(3));
    }
    return ret;
}

void UserFlashtoken::updateArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[0])
    {
        if(getUserId())
        {
            binder << getValueOfUserId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[1])
    {
        if(getFlashToken())
        {
            binder << getValueOfFlashToken();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[2])
    {
        if(getTokenDesc())
        {
            binder << getValueOfTokenDesc();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[3])
    {
        if(getExpireAt())
        {
            binder << getValueOfExpireAt();
        }
        else
        {
            binder << nullptr;
        }
    }
}
Json::Value UserFlashtoken::toJson() const
{
    Json::Value ret;
    if(getUserId())
    {
        ret["user_id"]=getValueOfUserId();
    }
    else
    {
        ret["user_id"]=Json::Value();
    }
    if(getFlashToken())
    {
        ret["flash_token"]=getValueOfFlashToken();
    }
    else
    {
        ret["flash_token"]=Json::Value();
    }
    if(getTokenDesc())
    {
        ret["token_desc"]=getValueOfTokenDesc();
    }
    else
    {
        ret["token_desc"]=Json::Value();
    }
    if(getExpireAt())
    {
        ret["expire_at"]=getExpireAt()->toDbStringLocal();
    }
    else
    {
        ret["expire_at"]=Json::Value();
    }
    return ret;
}

Json::Value UserFlashtoken::toMasqueradedJson(
    const std::vector<std::string> &pMasqueradingVector) const
{
    Json::Value ret;
    if(pMasqueradingVector.size() == 4)
    {
        if(!pMasqueradingVector[0].empty())
        {
            if(getUserId())
            {
                ret[pMasqueradingVector[0]]=getValueOfUserId();
            }
            else
            {
                ret[pMasqueradingVector[0]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[1].empty())
        {
            if(getFlashToken())
            {
                ret[pMasqueradingVector[1]]=getValueOfFlashToken();
            }
            else
            {
                ret[pMasqueradingVector[1]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[2].empty())
        {
            if(getTokenDesc())
            {
                ret[pMasqueradingVector[2]]=getValueOfTokenDesc();
            }
            else
            {
                ret[pMasqueradingVector[2]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[3].empty())
        {
            if(getExpireAt())
            {
                ret[pMasqueradingVector[3]]=getExpireAt()->toDbStringLocal();
            }
            else
            {
                ret[pMasqueradingVector[3]]=Json::Value();
            }
        }
        return ret;
    }
    LOG_ERROR << "Masquerade failed";
    if(getUserId())
    {
        ret["user_id"]=getValueOfUserId();
    }
    else
    {
        ret["user_id"]=Json::Value();
    }
    if(getFlashToken())
    {
        ret["flash_token"]=getValueOfFlashToken();
    }
    else
    {
        ret["flash_token"]=Json::Value();
    }
    if(getTokenDesc())
    {
        ret["token_desc"]=getValueOfTokenDesc();
    }
    else
    {
        ret["token_desc"]=Json::Value();
    }
    if(getExpireAt())
    {
        ret["expire_at"]=getExpireAt()->toDbStringLocal();
    }
    else
    {
        ret["expire_at"]=Json::Value();
    }
    return ret;
}

bool UserFlashtoken::validateJsonForCreation(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("user_id"))
    {
        if(!validJsonOfField(0, "user_id", pJson["user_id"], err, true))
            return false;
    }
    else
    {
        err="The user_id column cannot be null";
        return false;
    }
    if(pJson.isMember("flash_token"))
    {
        if(!validJsonOfField(1, "flash_token", pJson["flash_token"], err, true))
            return false;
    }
    else
    {
        err="The flash_token column cannot be null";
        return false;
    }
    if(pJson.isMember("token_desc"))
    {
        if(!validJsonOfField(2, "token_desc", pJson["token_desc"], err, true))
            return false;
    }
    else
    {
        err="The token_desc column cannot be null";
        return false;
    }
    if(pJson.isMember("expire_at"))
    {
        if(!validJsonOfField(3, "expire_at", pJson["expire_at"], err, true))
            return false;
    }
    else
    {
        err="The expire_at column cannot be null";
        return false;
    }
    return true;
}
bool UserFlashtoken::validateMasqueradedJsonForCreation(const Json::Value &pJson,
                                                        const std::vector<std::string> &pMasqueradingVector,
                                                        std::string &err)
{
    if(pMasqueradingVector.size() != 4)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty())
      {
          if(pJson.isMember(pMasqueradingVector[0]))
          {
              if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[0] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[1].empty())
      {
          if(pJson.isMember(pMasqueradingVector[1]))
          {
              if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[1] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[2].empty())
      {
          if(pJson.isMember(pMasqueradingVector[2]))
          {
              if(!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[2] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[3].empty())
      {
          if(pJson.isMember(pMasqueradingVector[3]))
          {
              if(!validJsonOfField(3, pMasqueradingVector[3], pJson[pMasqueradingVector[3]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[3] + " column cannot be null";
            return false;
        }
      }
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool UserFlashtoken::validateJsonForUpdate(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("user_id"))
    {
        if(!validJsonOfField(0, "user_id", pJson["user_id"], err, false))
            return false;
    }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
    if(pJson.isMember("flash_token"))
    {
        if(!validJsonOfField(1, "flash_token", pJson["flash_token"], err, false))
            return false;
    }
    if(pJson.isMember("token_desc"))
    {
        if(!validJsonOfField(2, "token_desc", pJson["token_desc"], err, false))
            return false;
    }
    if(pJson.isMember("expire_at"))
    {
        if(!validJsonOfField(3, "expire_at", pJson["expire_at"], err, false))
            return false;
    }
    return true;
}
bool UserFlashtoken::validateMasqueradedJsonForUpdate(const Json::Value &pJson,
                                                      const std::vector<std::string> &pMasqueradingVector,
                                                      std::string &err)
{
    if(pMasqueradingVector.size() != 4)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
      {
          if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, false))
              return false;
      }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
      if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
      {
          if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, false))
              return false;
      }
      if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
      {
          if(!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err, false))
              return false;
      }
      if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
      {
          if(!validJsonOfField(3, pMasqueradingVector[3], pJson[pMasqueradingVector[3]], err, false))
              return false;
      }
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool UserFlashtoken::validJsonOfField(size_t index,
                                      const std::string &fieldName,
                                      const Json::Value &pJson,
                                      std::string &err,
                                      bool isForCreation)
{
    switch(index)
    {
        case 0:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isInt())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 1:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            if(pJson.isString() && std::strlen(pJson.asCString()) > 300)
            {
                err="String length exceeds limit for the " +
                    fieldName +
                    " field (the maximum value is 300)";
                return false;
            }

            break;
        case 2:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            if(pJson.isString() && std::strlen(pJson.asCString()) > 500)
            {
                err="String length exceeds limit for the " +
                    fieldName +
                    " field (the maximum value is 500)";
                return false;
            }

            break;
        case 3:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        default:
            err="Internal error in the server";
            return false;
    }
    return true;
}
User UserFlashtoken::getUser(const DbClientPtr &clientPtr) const {
    static const std::string sql = "select * from user where Id = $1";
    Result r(nullptr);
    {
        auto binder = *clientPtr << sql;
        binder << *userId_ << Mode::Blocking >>
            [&r](const Result &result) { r = result; };
        binder.exec();
    }
    if (r.size() == 0)
    {
        throw UnexpectedRows("0 rows found");
    }
    else if (r.size() > 1)
    {
        throw UnexpectedRows("Found more than one row");
    }
    return User(r[0]);
}

void UserFlashtoken::getUser(const DbClientPtr &clientPtr,
                             const std::function<void(User)> &rcb,
                             const ExceptionCallback &ecb) const
{
    static const std::string sql = "select * from user where Id = $1";
    *clientPtr << sql
               << *userId_
               >> [rcb = std::move(rcb), ecb](const Result &r){
                    if (r.size() == 0)
                    {
                        ecb(UnexpectedRows("0 rows found"));
                    }
                    else if (r.size() > 1)
                    {
                        ecb(UnexpectedRows("Found more than one row"));
                    }
                    else
                    {
                        rcb(User(r[0]));
                    }
               }
               >> ecb;
}
