/**
 *
 *  UserGitlabInfo.cc
 *  DO NOT EDIT. This file is generated by drogon_ctl
 *
 */

#include "UserGitlabInfo.h"
#include "User.h"
#include <drogon/utils/Utilities.h>
#include <codecvt>
#include <string>

using namespace drogon;
using namespace drogon::orm;
using namespace drogon_model::UEAdminAPI;

const std::string UserGitlabInfo::Cols::_user_id = "\"user_id\"";
const std::string UserGitlabInfo::Cols::_git_id = "\"git_id\"";
const std::string UserGitlabInfo::Cols::_gitlab_impersonation_token_id = "\"gitlab_impersonation_token_id\"";
const std::string UserGitlabInfo::Cols::_gitlab_impersonation_token = "\"gitlab_impersonation_token\"";
const std::string UserGitlabInfo::primaryKeyName = "user_id";
const bool UserGitlabInfo::hasPrimaryKey = true;
const std::string UserGitlabInfo::tableName = "\"user_gitlab_info\"";

const std::vector<typename UserGitlabInfo::MetaData> UserGitlabInfo::metaData_={
{"user_id","int32_t","integer",4,0,1,1},
{"git_id","int32_t","integer",4,0,0,1},
{"gitlab_impersonation_token_id","int32_t","integer",4,0,0,1},
{"gitlab_impersonation_token","std::string","character varying",200,0,0,1}
};
const std::string &UserGitlabInfo::getColumnName(size_t index) noexcept(false)
{
    assert(index < metaData_.size());
    return metaData_[index].colName_;
}
UserGitlabInfo::UserGitlabInfo(const Row &r, const ssize_t indexOffset) noexcept
{
    if(indexOffset < 0)
    {
        if(!r["user_id"].isNull())
        {
            userId_=std::make_shared<int32_t>(r["user_id"].as<int32_t>());
        }
        if(!r["git_id"].isNull())
        {
            gitId_=std::make_shared<int32_t>(r["git_id"].as<int32_t>());
        }
        if(!r["gitlab_impersonation_token_id"].isNull())
        {
            gitlabImpersonationTokenId_=std::make_shared<int32_t>(r["gitlab_impersonation_token_id"].as<int32_t>());
        }
        if(!r["gitlab_impersonation_token"].isNull())
        {
            gitlabImpersonationToken_=std::make_shared<std::string>(r["gitlab_impersonation_token"].as<std::string>());
        }
    }
    else
    {
        size_t offset = (size_t)indexOffset;
        if(offset + 4 > r.size())
        {
            LOG_FATAL << "Invalid SQL result for this model";
            return;
        }
        size_t index;
        index = offset + 0;
        if(!r[index].isNull())
        {
            userId_=std::make_shared<int32_t>(r[index].as<int32_t>());
        }
        index = offset + 1;
        if(!r[index].isNull())
        {
            gitId_=std::make_shared<int32_t>(r[index].as<int32_t>());
        }
        index = offset + 2;
        if(!r[index].isNull())
        {
            gitlabImpersonationTokenId_=std::make_shared<int32_t>(r[index].as<int32_t>());
        }
        index = offset + 3;
        if(!r[index].isNull())
        {
            gitlabImpersonationToken_=std::make_shared<std::string>(r[index].as<std::string>());
        }
    }

}

UserGitlabInfo::UserGitlabInfo(const Json::Value &pJson, const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 4)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        dirtyFlag_[0] = true;
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            userId_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[0]].asInt64());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        dirtyFlag_[1] = true;
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            gitId_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[1]].asInt64());
        }
    }
    if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
    {
        dirtyFlag_[2] = true;
        if(!pJson[pMasqueradingVector[2]].isNull())
        {
            gitlabImpersonationTokenId_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[2]].asInt64());
        }
    }
    if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
    {
        dirtyFlag_[3] = true;
        if(!pJson[pMasqueradingVector[3]].isNull())
        {
            gitlabImpersonationToken_=std::make_shared<std::string>(pJson[pMasqueradingVector[3]].asString());
        }
    }
}

UserGitlabInfo::UserGitlabInfo(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("user_id"))
    {
        dirtyFlag_[0]=true;
        if(!pJson["user_id"].isNull())
        {
            userId_=std::make_shared<int32_t>((int32_t)pJson["user_id"].asInt64());
        }
    }
    if(pJson.isMember("git_id"))
    {
        dirtyFlag_[1]=true;
        if(!pJson["git_id"].isNull())
        {
            gitId_=std::make_shared<int32_t>((int32_t)pJson["git_id"].asInt64());
        }
    }
    if(pJson.isMember("gitlab_impersonation_token_id"))
    {
        dirtyFlag_[2]=true;
        if(!pJson["gitlab_impersonation_token_id"].isNull())
        {
            gitlabImpersonationTokenId_=std::make_shared<int32_t>((int32_t)pJson["gitlab_impersonation_token_id"].asInt64());
        }
    }
    if(pJson.isMember("gitlab_impersonation_token"))
    {
        dirtyFlag_[3]=true;
        if(!pJson["gitlab_impersonation_token"].isNull())
        {
            gitlabImpersonationToken_=std::make_shared<std::string>(pJson["gitlab_impersonation_token"].asString());
        }
    }
}

void UserGitlabInfo::updateByMasqueradedJson(const Json::Value &pJson,
                                            const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 4)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            userId_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[0]].asInt64());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        dirtyFlag_[1] = true;
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            gitId_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[1]].asInt64());
        }
    }
    if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
    {
        dirtyFlag_[2] = true;
        if(!pJson[pMasqueradingVector[2]].isNull())
        {
            gitlabImpersonationTokenId_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[2]].asInt64());
        }
    }
    if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
    {
        dirtyFlag_[3] = true;
        if(!pJson[pMasqueradingVector[3]].isNull())
        {
            gitlabImpersonationToken_=std::make_shared<std::string>(pJson[pMasqueradingVector[3]].asString());
        }
    }
}

void UserGitlabInfo::updateByJson(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("user_id"))
    {
        if(!pJson["user_id"].isNull())
        {
            userId_=std::make_shared<int32_t>((int32_t)pJson["user_id"].asInt64());
        }
    }
    if(pJson.isMember("git_id"))
    {
        dirtyFlag_[1] = true;
        if(!pJson["git_id"].isNull())
        {
            gitId_=std::make_shared<int32_t>((int32_t)pJson["git_id"].asInt64());
        }
    }
    if(pJson.isMember("gitlab_impersonation_token_id"))
    {
        dirtyFlag_[2] = true;
        if(!pJson["gitlab_impersonation_token_id"].isNull())
        {
            gitlabImpersonationTokenId_=std::make_shared<int32_t>((int32_t)pJson["gitlab_impersonation_token_id"].asInt64());
        }
    }
    if(pJson.isMember("gitlab_impersonation_token"))
    {
        dirtyFlag_[3] = true;
        if(!pJson["gitlab_impersonation_token"].isNull())
        {
            gitlabImpersonationToken_=std::make_shared<std::string>(pJson["gitlab_impersonation_token"].asString());
        }
    }
}

const int32_t &UserGitlabInfo::getValueOfUserId() const noexcept
{
    static const int32_t defaultValue = int32_t();
    if(userId_)
        return *userId_;
    return defaultValue;
}
const std::shared_ptr<int32_t> &UserGitlabInfo::getUserId() const noexcept
{
    return userId_;
}
void UserGitlabInfo::setUserId(const int32_t &pUserId) noexcept
{
    userId_ = std::make_shared<int32_t>(pUserId);
    dirtyFlag_[0] = true;
}
const typename UserGitlabInfo::PrimaryKeyType & UserGitlabInfo::getPrimaryKey() const
{
    assert(userId_);
    return *userId_;
}

const int32_t &UserGitlabInfo::getValueOfGitId() const noexcept
{
    static const int32_t defaultValue = int32_t();
    if(gitId_)
        return *gitId_;
    return defaultValue;
}
const std::shared_ptr<int32_t> &UserGitlabInfo::getGitId() const noexcept
{
    return gitId_;
}
void UserGitlabInfo::setGitId(const int32_t &pGitId) noexcept
{
    gitId_ = std::make_shared<int32_t>(pGitId);
    dirtyFlag_[1] = true;
}

const int32_t &UserGitlabInfo::getValueOfGitlabImpersonationTokenId() const noexcept
{
    static const int32_t defaultValue = int32_t();
    if(gitlabImpersonationTokenId_)
        return *gitlabImpersonationTokenId_;
    return defaultValue;
}
const std::shared_ptr<int32_t> &UserGitlabInfo::getGitlabImpersonationTokenId() const noexcept
{
    return gitlabImpersonationTokenId_;
}
void UserGitlabInfo::setGitlabImpersonationTokenId(const int32_t &pGitlabImpersonationTokenId) noexcept
{
    gitlabImpersonationTokenId_ = std::make_shared<int32_t>(pGitlabImpersonationTokenId);
    dirtyFlag_[2] = true;
}

const std::string &UserGitlabInfo::getValueOfGitlabImpersonationToken() const noexcept
{
    static const std::string defaultValue = std::string();
    if(gitlabImpersonationToken_)
        return *gitlabImpersonationToken_;
    return defaultValue;
}
const std::shared_ptr<std::string> &UserGitlabInfo::getGitlabImpersonationToken() const noexcept
{
    return gitlabImpersonationToken_;
}
void UserGitlabInfo::setGitlabImpersonationToken(const std::string &pGitlabImpersonationToken) noexcept
{
    gitlabImpersonationToken_ = std::make_shared<std::string>(pGitlabImpersonationToken);
    dirtyFlag_[3] = true;
}
void UserGitlabInfo::setGitlabImpersonationToken(std::string &&pGitlabImpersonationToken) noexcept
{
    gitlabImpersonationToken_ = std::make_shared<std::string>(std::move(pGitlabImpersonationToken));
    dirtyFlag_[3] = true;
}

void UserGitlabInfo::updateId(const uint64_t id)
{
}

const std::vector<std::string> &UserGitlabInfo::insertColumns() noexcept
{
    static const std::vector<std::string> inCols={
        "user_id",
        "git_id",
        "gitlab_impersonation_token_id",
        "gitlab_impersonation_token"
    };
    return inCols;
}

void UserGitlabInfo::outputArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[0])
    {
        if(getUserId())
        {
            binder << getValueOfUserId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[1])
    {
        if(getGitId())
        {
            binder << getValueOfGitId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[2])
    {
        if(getGitlabImpersonationTokenId())
        {
            binder << getValueOfGitlabImpersonationTokenId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[3])
    {
        if(getGitlabImpersonationToken())
        {
            binder << getValueOfGitlabImpersonationToken();
        }
        else
        {
            binder << nullptr;
        }
    }
}

const std::vector<std::string> UserGitlabInfo::updateColumns() const
{
    std::vector<std::string> ret;
    if(dirtyFlag_[0])
    {
        ret.push_back(getColumnName(0));
    }
    if(dirtyFlag_[1])
    {
        ret.push_back(getColumnName(1));
    }
    if(dirtyFlag_[2])
    {
        ret.push_back(getColumnName(2));
    }
    if(dirtyFlag_[3])
    {
        ret.push_back(getColumnName(3));
    }
    return ret;
}

void UserGitlabInfo::updateArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[0])
    {
        if(getUserId())
        {
            binder << getValueOfUserId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[1])
    {
        if(getGitId())
        {
            binder << getValueOfGitId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[2])
    {
        if(getGitlabImpersonationTokenId())
        {
            binder << getValueOfGitlabImpersonationTokenId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[3])
    {
        if(getGitlabImpersonationToken())
        {
            binder << getValueOfGitlabImpersonationToken();
        }
        else
        {
            binder << nullptr;
        }
    }
}
Json::Value UserGitlabInfo::toJson() const
{
    Json::Value ret;
    if(getUserId())
    {
        ret["user_id"]=getValueOfUserId();
    }
    else
    {
        ret["user_id"]=Json::Value();
    }
    if(getGitId())
    {
        ret["git_id"]=getValueOfGitId();
    }
    else
    {
        ret["git_id"]=Json::Value();
    }
    if(getGitlabImpersonationTokenId())
    {
        ret["gitlab_impersonation_token_id"]=getValueOfGitlabImpersonationTokenId();
    }
    else
    {
        ret["gitlab_impersonation_token_id"]=Json::Value();
    }
    if(getGitlabImpersonationToken())
    {
        ret["gitlab_impersonation_token"]=getValueOfGitlabImpersonationToken();
    }
    else
    {
        ret["gitlab_impersonation_token"]=Json::Value();
    }
    return ret;
}

std::string UserGitlabInfo::toString() const
{
    return toJson().toStyledString();
}

Json::Value UserGitlabInfo::toMasqueradedJson(
    const std::vector<std::string> &pMasqueradingVector) const
{
    Json::Value ret;
    if(pMasqueradingVector.size() == 4)
    {
        if(!pMasqueradingVector[0].empty())
        {
            if(getUserId())
            {
                ret[pMasqueradingVector[0]]=getValueOfUserId();
            }
            else
            {
                ret[pMasqueradingVector[0]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[1].empty())
        {
            if(getGitId())
            {
                ret[pMasqueradingVector[1]]=getValueOfGitId();
            }
            else
            {
                ret[pMasqueradingVector[1]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[2].empty())
        {
            if(getGitlabImpersonationTokenId())
            {
                ret[pMasqueradingVector[2]]=getValueOfGitlabImpersonationTokenId();
            }
            else
            {
                ret[pMasqueradingVector[2]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[3].empty())
        {
            if(getGitlabImpersonationToken())
            {
                ret[pMasqueradingVector[3]]=getValueOfGitlabImpersonationToken();
            }
            else
            {
                ret[pMasqueradingVector[3]]=Json::Value();
            }
        }
        return ret;
    }
    LOG_ERROR << "Masquerade failed";
    if(getUserId())
    {
        ret["user_id"]=getValueOfUserId();
    }
    else
    {
        ret["user_id"]=Json::Value();
    }
    if(getGitId())
    {
        ret["git_id"]=getValueOfGitId();
    }
    else
    {
        ret["git_id"]=Json::Value();
    }
    if(getGitlabImpersonationTokenId())
    {
        ret["gitlab_impersonation_token_id"]=getValueOfGitlabImpersonationTokenId();
    }
    else
    {
        ret["gitlab_impersonation_token_id"]=Json::Value();
    }
    if(getGitlabImpersonationToken())
    {
        ret["gitlab_impersonation_token"]=getValueOfGitlabImpersonationToken();
    }
    else
    {
        ret["gitlab_impersonation_token"]=Json::Value();
    }
    return ret;
}

bool UserGitlabInfo::validateJsonForCreation(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("user_id"))
    {
        if(!validJsonOfField(0, "user_id", pJson["user_id"], err, true))
            return false;
    }
    else
    {
        err="The user_id column cannot be null";
        return false;
    }
    if(pJson.isMember("git_id"))
    {
        if(!validJsonOfField(1, "git_id", pJson["git_id"], err, true))
            return false;
    }
    else
    {
        err="The git_id column cannot be null";
        return false;
    }
    if(pJson.isMember("gitlab_impersonation_token_id"))
    {
        if(!validJsonOfField(2, "gitlab_impersonation_token_id", pJson["gitlab_impersonation_token_id"], err, true))
            return false;
    }
    else
    {
        err="The gitlab_impersonation_token_id column cannot be null";
        return false;
    }
    if(pJson.isMember("gitlab_impersonation_token"))
    {
        if(!validJsonOfField(3, "gitlab_impersonation_token", pJson["gitlab_impersonation_token"], err, true))
            return false;
    }
    else
    {
        err="The gitlab_impersonation_token column cannot be null";
        return false;
    }
    return true;
}
bool UserGitlabInfo::validateMasqueradedJsonForCreation(const Json::Value &pJson,
                                                        const std::vector<std::string> &pMasqueradingVector,
                                                        std::string &err)
{
    if(pMasqueradingVector.size() != 4)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty())
      {
          if(pJson.isMember(pMasqueradingVector[0]))
          {
              if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[0] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[1].empty())
      {
          if(pJson.isMember(pMasqueradingVector[1]))
          {
              if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[1] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[2].empty())
      {
          if(pJson.isMember(pMasqueradingVector[2]))
          {
              if(!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[2] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[3].empty())
      {
          if(pJson.isMember(pMasqueradingVector[3]))
          {
              if(!validJsonOfField(3, pMasqueradingVector[3], pJson[pMasqueradingVector[3]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[3] + " column cannot be null";
            return false;
        }
      }
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool UserGitlabInfo::validateJsonForUpdate(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("user_id"))
    {
        if(!validJsonOfField(0, "user_id", pJson["user_id"], err, false))
            return false;
    }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
    if(pJson.isMember("git_id"))
    {
        if(!validJsonOfField(1, "git_id", pJson["git_id"], err, false))
            return false;
    }
    if(pJson.isMember("gitlab_impersonation_token_id"))
    {
        if(!validJsonOfField(2, "gitlab_impersonation_token_id", pJson["gitlab_impersonation_token_id"], err, false))
            return false;
    }
    if(pJson.isMember("gitlab_impersonation_token"))
    {
        if(!validJsonOfField(3, "gitlab_impersonation_token", pJson["gitlab_impersonation_token"], err, false))
            return false;
    }
    return true;
}
bool UserGitlabInfo::validateMasqueradedJsonForUpdate(const Json::Value &pJson,
                                                      const std::vector<std::string> &pMasqueradingVector,
                                                      std::string &err)
{
    if(pMasqueradingVector.size() != 4)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
      {
          if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, false))
              return false;
      }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
      if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
      {
          if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, false))
              return false;
      }
      if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
      {
          if(!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err, false))
              return false;
      }
      if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
      {
          if(!validJsonOfField(3, pMasqueradingVector[3], pJson[pMasqueradingVector[3]], err, false))
              return false;
      }
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool UserGitlabInfo::validJsonOfField(size_t index,
                                      const std::string &fieldName,
                                      const Json::Value &pJson,
                                      std::string &err,
                                      bool isForCreation)
{
    switch(index)
    {
        case 0:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isInt())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 1:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isInt())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 2:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isInt())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 3:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            if(pJson.isString() && std::wstring_convert<std::codecvt_utf8_utf16<wchar_t>, wchar_t>{}
                .from_bytes(pJson.asCString()).size() > 200)
            {
                err="String length exceeds limit for the " +
                    fieldName +
                    " field (the maximum value is 200)";
                return false;
            }
            break;
        default:
            err="Internal error in the server";
            return false;
    }
    return true;
}
User UserGitlabInfo::getUser(const DbClientPtr &clientPtr) const {
    static const std::string sql = "select * from user where id = $1";
    Result r(nullptr);
    {
        auto binder = *clientPtr << sql;
        binder << *userId_ << Mode::Blocking >>
            [&r](const Result &result) { r = result; };
        binder.exec();
    }
    if (r.size() == 0)
    {
        throw UnexpectedRows("0 rows found");
    }
    else if (r.size() > 1)
    {
        throw UnexpectedRows("Found more than one row");
    }
    return User(r[0]);
}

void UserGitlabInfo::getUser(const DbClientPtr &clientPtr,
                             const std::function<void(User)> &rcb,
                             const ExceptionCallback &ecb) const
{
    static const std::string sql = "select * from user where id = $1";
    *clientPtr << sql
               << *userId_
               >> [rcb = std::move(rcb), ecb](const Result &r){
                    if (r.size() == 0)
                    {
                        ecb(UnexpectedRows("0 rows found"));
                    }
                    else if (r.size() > 1)
                    {
                        ecb(UnexpectedRows("Found more than one row"));
                    }
                    else
                    {
                        rcb(User(r[0]));
                    }
               }
               >> ecb;
}
