/**
 *
 *  UserDeleted.cc
 *  DO NOT EDIT. This file is generated by drogon_ctl
 *
 */

#include "UserDeleted.h"
#include <drogon/utils/Utilities.h>
#include <codecvt>
#include <string>

using namespace drogon;
using namespace drogon::orm;
using namespace drogon_model::UEAdminAPI;

const std::string UserDeleted::Cols::_id = "\"id\"";
const std::string UserDeleted::Cols::_name = "\"name\"";
const std::string UserDeleted::Cols::_password_salt = "\"password_salt\"";
const std::string UserDeleted::Cols::_password_hash = "\"password_hash\"";
const std::string UserDeleted::Cols::_privilege = "\"privilege\"";
const std::string UserDeleted::Cols::_nickname = "\"nickname\"";
const std::string UserDeleted::Cols::_telephone_number = "\"telephone_number\"";
const std::string UserDeleted::Cols::_email = "\"email\"";
const std::string UserDeleted::Cols::_is_male = "\"is_male\"";
const std::string UserDeleted::Cols::_create_at = "\"create_at\"";
const std::string UserDeleted::Cols::_delete_at = "\"delete_at\"";
const std::string UserDeleted::primaryKeyName = "id";
const bool UserDeleted::hasPrimaryKey = true;
const std::string UserDeleted::tableName = "\"user_deleted\"";

const std::vector<typename UserDeleted::MetaData> UserDeleted::metaData_={
{"id","int32_t","integer",4,0,1,1},
{"name","std::string","character varying",30,0,0,1},
{"password_salt","std::vector<char>","bytea",0,0,0,1},
{"password_hash","std::vector<char>","bytea",0,0,0,1},
{"privilege","int32_t","integer",4,0,0,1},
{"nickname","std::string","character varying",30,0,0,1},
{"telephone_number","std::string","character varying",15,0,0,0},
{"email","std::string","character varying",100,0,0,0},
{"is_male","bool","boolean",1,0,0,1},
{"create_at","::trantor::Date","timestamp with time zone",0,0,0,1},
{"delete_at","::trantor::Date","timestamp with time zone",0,0,0,1}
};
const std::string &UserDeleted::getColumnName(size_t index) noexcept(false)
{
    assert(index < metaData_.size());
    return metaData_[index].colName_;
}
UserDeleted::UserDeleted(const Row &r, const ssize_t indexOffset) noexcept
{
    if(indexOffset < 0)
    {
        if(!r["id"].isNull())
        {
            id_=std::make_shared<int32_t>(r["id"].as<int32_t>());
        }
        if(!r["name"].isNull())
        {
            name_=std::make_shared<std::string>(r["name"].as<std::string>());
        }
        if(!r["password_salt"].isNull())
        {
            auto str = r["password_salt"].as<std::string_view>();
            if(str.length()>=2&&
                str[0]=='\\'&&str[1]=='x')
            {
                passwordSalt_=std::make_shared<std::vector<char>>(drogon::utils::hexToBinaryVector(str.data()+2,str.length()-2));
            }
        }
        if(!r["password_hash"].isNull())
        {
            auto str = r["password_hash"].as<std::string_view>();
            if(str.length()>=2&&
                str[0]=='\\'&&str[1]=='x')
            {
                passwordHash_=std::make_shared<std::vector<char>>(drogon::utils::hexToBinaryVector(str.data()+2,str.length()-2));
            }
        }
        if(!r["privilege"].isNull())
        {
            privilege_=std::make_shared<int32_t>(r["privilege"].as<int32_t>());
        }
        if(!r["nickname"].isNull())
        {
            nickname_=std::make_shared<std::string>(r["nickname"].as<std::string>());
        }
        if(!r["telephone_number"].isNull())
        {
            telephoneNumber_=std::make_shared<std::string>(r["telephone_number"].as<std::string>());
        }
        if(!r["email"].isNull())
        {
            email_=std::make_shared<std::string>(r["email"].as<std::string>());
        }
        if(!r["is_male"].isNull())
        {
            isMale_=std::make_shared<bool>(r["is_male"].as<bool>());
        }
        if(!r["create_at"].isNull())
        {
            auto timeStr = r["create_at"].as<std::string>();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                createAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
        if(!r["delete_at"].isNull())
        {
            auto timeStr = r["delete_at"].as<std::string>();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                deleteAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
    else
    {
        size_t offset = (size_t)indexOffset;
        if(offset + 11 > r.size())
        {
            LOG_FATAL << "Invalid SQL result for this model";
            return;
        }
        size_t index;
        index = offset + 0;
        if(!r[index].isNull())
        {
            id_=std::make_shared<int32_t>(r[index].as<int32_t>());
        }
        index = offset + 1;
        if(!r[index].isNull())
        {
            name_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 2;
        if(!r[index].isNull())
        {
            auto str = r[index].as<std::string_view>();
            if(str.length()>=2&&
                str[0]=='\\'&&str[1]=='x')
            {
                passwordSalt_=std::make_shared<std::vector<char>>(drogon::utils::hexToBinaryVector(str.data()+2,str.length()-2));
            }
        }
        index = offset + 3;
        if(!r[index].isNull())
        {
            auto str = r[index].as<std::string_view>();
            if(str.length()>=2&&
                str[0]=='\\'&&str[1]=='x')
            {
                passwordHash_=std::make_shared<std::vector<char>>(drogon::utils::hexToBinaryVector(str.data()+2,str.length()-2));
            }
        }
        index = offset + 4;
        if(!r[index].isNull())
        {
            privilege_=std::make_shared<int32_t>(r[index].as<int32_t>());
        }
        index = offset + 5;
        if(!r[index].isNull())
        {
            nickname_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 6;
        if(!r[index].isNull())
        {
            telephoneNumber_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 7;
        if(!r[index].isNull())
        {
            email_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 8;
        if(!r[index].isNull())
        {
            isMale_=std::make_shared<bool>(r[index].as<bool>());
        }
        index = offset + 9;
        if(!r[index].isNull())
        {
            auto timeStr = r[index].as<std::string>();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                createAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
        index = offset + 10;
        if(!r[index].isNull())
        {
            auto timeStr = r[index].as<std::string>();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                deleteAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }

}

UserDeleted::UserDeleted(const Json::Value &pJson, const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 11)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        dirtyFlag_[0] = true;
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            id_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[0]].asInt64());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        dirtyFlag_[1] = true;
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            name_=std::make_shared<std::string>(pJson[pMasqueradingVector[1]].asString());
        }
    }
    if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
    {
        dirtyFlag_[2] = true;
        if(!pJson[pMasqueradingVector[2]].isNull())
        {
            auto str = pJson[pMasqueradingVector[2]].asString();
            passwordSalt_=std::make_shared<std::vector<char>>(drogon::utils::base64DecodeToVector(str));
        }
    }
    if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
    {
        dirtyFlag_[3] = true;
        if(!pJson[pMasqueradingVector[3]].isNull())
        {
            auto str = pJson[pMasqueradingVector[3]].asString();
            passwordHash_=std::make_shared<std::vector<char>>(drogon::utils::base64DecodeToVector(str));
        }
    }
    if(!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
    {
        dirtyFlag_[4] = true;
        if(!pJson[pMasqueradingVector[4]].isNull())
        {
            privilege_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[4]].asInt64());
        }
    }
    if(!pMasqueradingVector[5].empty() && pJson.isMember(pMasqueradingVector[5]))
    {
        dirtyFlag_[5] = true;
        if(!pJson[pMasqueradingVector[5]].isNull())
        {
            nickname_=std::make_shared<std::string>(pJson[pMasqueradingVector[5]].asString());
        }
    }
    if(!pMasqueradingVector[6].empty() && pJson.isMember(pMasqueradingVector[6]))
    {
        dirtyFlag_[6] = true;
        if(!pJson[pMasqueradingVector[6]].isNull())
        {
            telephoneNumber_=std::make_shared<std::string>(pJson[pMasqueradingVector[6]].asString());
        }
    }
    if(!pMasqueradingVector[7].empty() && pJson.isMember(pMasqueradingVector[7]))
    {
        dirtyFlag_[7] = true;
        if(!pJson[pMasqueradingVector[7]].isNull())
        {
            email_=std::make_shared<std::string>(pJson[pMasqueradingVector[7]].asString());
        }
    }
    if(!pMasqueradingVector[8].empty() && pJson.isMember(pMasqueradingVector[8]))
    {
        dirtyFlag_[8] = true;
        if(!pJson[pMasqueradingVector[8]].isNull())
        {
            isMale_=std::make_shared<bool>(pJson[pMasqueradingVector[8]].asBool());
        }
    }
    if(!pMasqueradingVector[9].empty() && pJson.isMember(pMasqueradingVector[9]))
    {
        dirtyFlag_[9] = true;
        if(!pJson[pMasqueradingVector[9]].isNull())
        {
            auto timeStr = pJson[pMasqueradingVector[9]].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                createAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
    if(!pMasqueradingVector[10].empty() && pJson.isMember(pMasqueradingVector[10]))
    {
        dirtyFlag_[10] = true;
        if(!pJson[pMasqueradingVector[10]].isNull())
        {
            auto timeStr = pJson[pMasqueradingVector[10]].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                deleteAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
}

UserDeleted::UserDeleted(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("id"))
    {
        dirtyFlag_[0]=true;
        if(!pJson["id"].isNull())
        {
            id_=std::make_shared<int32_t>((int32_t)pJson["id"].asInt64());
        }
    }
    if(pJson.isMember("name"))
    {
        dirtyFlag_[1]=true;
        if(!pJson["name"].isNull())
        {
            name_=std::make_shared<std::string>(pJson["name"].asString());
        }
    }
    if(pJson.isMember("password_salt"))
    {
        dirtyFlag_[2]=true;
        if(!pJson["password_salt"].isNull())
        {
            auto str = pJson["password_salt"].asString();
            passwordSalt_=std::make_shared<std::vector<char>>(drogon::utils::base64DecodeToVector(str));
        }
    }
    if(pJson.isMember("password_hash"))
    {
        dirtyFlag_[3]=true;
        if(!pJson["password_hash"].isNull())
        {
            auto str = pJson["password_hash"].asString();
            passwordHash_=std::make_shared<std::vector<char>>(drogon::utils::base64DecodeToVector(str));
        }
    }
    if(pJson.isMember("privilege"))
    {
        dirtyFlag_[4]=true;
        if(!pJson["privilege"].isNull())
        {
            privilege_=std::make_shared<int32_t>((int32_t)pJson["privilege"].asInt64());
        }
    }
    if(pJson.isMember("nickname"))
    {
        dirtyFlag_[5]=true;
        if(!pJson["nickname"].isNull())
        {
            nickname_=std::make_shared<std::string>(pJson["nickname"].asString());
        }
    }
    if(pJson.isMember("telephone_number"))
    {
        dirtyFlag_[6]=true;
        if(!pJson["telephone_number"].isNull())
        {
            telephoneNumber_=std::make_shared<std::string>(pJson["telephone_number"].asString());
        }
    }
    if(pJson.isMember("email"))
    {
        dirtyFlag_[7]=true;
        if(!pJson["email"].isNull())
        {
            email_=std::make_shared<std::string>(pJson["email"].asString());
        }
    }
    if(pJson.isMember("is_male"))
    {
        dirtyFlag_[8]=true;
        if(!pJson["is_male"].isNull())
        {
            isMale_=std::make_shared<bool>(pJson["is_male"].asBool());
        }
    }
    if(pJson.isMember("create_at"))
    {
        dirtyFlag_[9]=true;
        if(!pJson["create_at"].isNull())
        {
            auto timeStr = pJson["create_at"].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                createAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
    if(pJson.isMember("delete_at"))
    {
        dirtyFlag_[10]=true;
        if(!pJson["delete_at"].isNull())
        {
            auto timeStr = pJson["delete_at"].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                deleteAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
}

void UserDeleted::updateByMasqueradedJson(const Json::Value &pJson,
                                            const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 11)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            id_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[0]].asInt64());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        dirtyFlag_[1] = true;
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            name_=std::make_shared<std::string>(pJson[pMasqueradingVector[1]].asString());
        }
    }
    if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
    {
        dirtyFlag_[2] = true;
        if(!pJson[pMasqueradingVector[2]].isNull())
        {
            auto str = pJson[pMasqueradingVector[2]].asString();
            passwordSalt_=std::make_shared<std::vector<char>>(drogon::utils::base64DecodeToVector(str));
        }
    }
    if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
    {
        dirtyFlag_[3] = true;
        if(!pJson[pMasqueradingVector[3]].isNull())
        {
            auto str = pJson[pMasqueradingVector[3]].asString();
            passwordHash_=std::make_shared<std::vector<char>>(drogon::utils::base64DecodeToVector(str));
        }
    }
    if(!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
    {
        dirtyFlag_[4] = true;
        if(!pJson[pMasqueradingVector[4]].isNull())
        {
            privilege_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[4]].asInt64());
        }
    }
    if(!pMasqueradingVector[5].empty() && pJson.isMember(pMasqueradingVector[5]))
    {
        dirtyFlag_[5] = true;
        if(!pJson[pMasqueradingVector[5]].isNull())
        {
            nickname_=std::make_shared<std::string>(pJson[pMasqueradingVector[5]].asString());
        }
    }
    if(!pMasqueradingVector[6].empty() && pJson.isMember(pMasqueradingVector[6]))
    {
        dirtyFlag_[6] = true;
        if(!pJson[pMasqueradingVector[6]].isNull())
        {
            telephoneNumber_=std::make_shared<std::string>(pJson[pMasqueradingVector[6]].asString());
        }
    }
    if(!pMasqueradingVector[7].empty() && pJson.isMember(pMasqueradingVector[7]))
    {
        dirtyFlag_[7] = true;
        if(!pJson[pMasqueradingVector[7]].isNull())
        {
            email_=std::make_shared<std::string>(pJson[pMasqueradingVector[7]].asString());
        }
    }
    if(!pMasqueradingVector[8].empty() && pJson.isMember(pMasqueradingVector[8]))
    {
        dirtyFlag_[8] = true;
        if(!pJson[pMasqueradingVector[8]].isNull())
        {
            isMale_=std::make_shared<bool>(pJson[pMasqueradingVector[8]].asBool());
        }
    }
    if(!pMasqueradingVector[9].empty() && pJson.isMember(pMasqueradingVector[9]))
    {
        dirtyFlag_[9] = true;
        if(!pJson[pMasqueradingVector[9]].isNull())
        {
            auto timeStr = pJson[pMasqueradingVector[9]].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                createAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
    if(!pMasqueradingVector[10].empty() && pJson.isMember(pMasqueradingVector[10]))
    {
        dirtyFlag_[10] = true;
        if(!pJson[pMasqueradingVector[10]].isNull())
        {
            auto timeStr = pJson[pMasqueradingVector[10]].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                deleteAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
}

void UserDeleted::updateByJson(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("id"))
    {
        if(!pJson["id"].isNull())
        {
            id_=std::make_shared<int32_t>((int32_t)pJson["id"].asInt64());
        }
    }
    if(pJson.isMember("name"))
    {
        dirtyFlag_[1] = true;
        if(!pJson["name"].isNull())
        {
            name_=std::make_shared<std::string>(pJson["name"].asString());
        }
    }
    if(pJson.isMember("password_salt"))
    {
        dirtyFlag_[2] = true;
        if(!pJson["password_salt"].isNull())
        {
            auto str = pJson["password_salt"].asString();
            passwordSalt_=std::make_shared<std::vector<char>>(drogon::utils::base64DecodeToVector(str));
        }
    }
    if(pJson.isMember("password_hash"))
    {
        dirtyFlag_[3] = true;
        if(!pJson["password_hash"].isNull())
        {
            auto str = pJson["password_hash"].asString();
            passwordHash_=std::make_shared<std::vector<char>>(drogon::utils::base64DecodeToVector(str));
        }
    }
    if(pJson.isMember("privilege"))
    {
        dirtyFlag_[4] = true;
        if(!pJson["privilege"].isNull())
        {
            privilege_=std::make_shared<int32_t>((int32_t)pJson["privilege"].asInt64());
        }
    }
    if(pJson.isMember("nickname"))
    {
        dirtyFlag_[5] = true;
        if(!pJson["nickname"].isNull())
        {
            nickname_=std::make_shared<std::string>(pJson["nickname"].asString());
        }
    }
    if(pJson.isMember("telephone_number"))
    {
        dirtyFlag_[6] = true;
        if(!pJson["telephone_number"].isNull())
        {
            telephoneNumber_=std::make_shared<std::string>(pJson["telephone_number"].asString());
        }
    }
    if(pJson.isMember("email"))
    {
        dirtyFlag_[7] = true;
        if(!pJson["email"].isNull())
        {
            email_=std::make_shared<std::string>(pJson["email"].asString());
        }
    }
    if(pJson.isMember("is_male"))
    {
        dirtyFlag_[8] = true;
        if(!pJson["is_male"].isNull())
        {
            isMale_=std::make_shared<bool>(pJson["is_male"].asBool());
        }
    }
    if(pJson.isMember("create_at"))
    {
        dirtyFlag_[9] = true;
        if(!pJson["create_at"].isNull())
        {
            auto timeStr = pJson["create_at"].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                createAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
    if(pJson.isMember("delete_at"))
    {
        dirtyFlag_[10] = true;
        if(!pJson["delete_at"].isNull())
        {
            auto timeStr = pJson["delete_at"].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                deleteAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
}

const int32_t &UserDeleted::getValueOfId() const noexcept
{
    static const int32_t defaultValue = int32_t();
    if(id_)
        return *id_;
    return defaultValue;
}
const std::shared_ptr<int32_t> &UserDeleted::getId() const noexcept
{
    return id_;
}
void UserDeleted::setId(const int32_t &pId) noexcept
{
    id_ = std::make_shared<int32_t>(pId);
    dirtyFlag_[0] = true;
}
const typename UserDeleted::PrimaryKeyType & UserDeleted::getPrimaryKey() const
{
    assert(id_);
    return *id_;
}

const std::string &UserDeleted::getValueOfName() const noexcept
{
    static const std::string defaultValue = std::string();
    if(name_)
        return *name_;
    return defaultValue;
}
const std::shared_ptr<std::string> &UserDeleted::getName() const noexcept
{
    return name_;
}
void UserDeleted::setName(const std::string &pName) noexcept
{
    name_ = std::make_shared<std::string>(pName);
    dirtyFlag_[1] = true;
}
void UserDeleted::setName(std::string &&pName) noexcept
{
    name_ = std::make_shared<std::string>(std::move(pName));
    dirtyFlag_[1] = true;
}

const std::vector<char> &UserDeleted::getValueOfPasswordSalt() const noexcept
{
    static const std::vector<char> defaultValue = std::vector<char>();
    if(passwordSalt_)
        return *passwordSalt_;
    return defaultValue;
}
std::string UserDeleted::getValueOfPasswordSaltAsString() const noexcept
{
    static const std::string defaultValue = std::string();
    if(passwordSalt_)
        return std::string(passwordSalt_->data(),passwordSalt_->size());
    return defaultValue;
}
const std::shared_ptr<std::vector<char>> &UserDeleted::getPasswordSalt() const noexcept
{
    return passwordSalt_;
}
void UserDeleted::setPasswordSalt(const std::vector<char> &pPasswordSalt) noexcept
{
    passwordSalt_ = std::make_shared<std::vector<char>>(pPasswordSalt);
    dirtyFlag_[2] = true;
}
void UserDeleted::setPasswordSalt(const std::string &pPasswordSalt) noexcept
{
    passwordSalt_ = std::make_shared<std::vector<char>>(pPasswordSalt.c_str(),pPasswordSalt.c_str()+pPasswordSalt.length());
    dirtyFlag_[2] = true;
}

const std::vector<char> &UserDeleted::getValueOfPasswordHash() const noexcept
{
    static const std::vector<char> defaultValue = std::vector<char>();
    if(passwordHash_)
        return *passwordHash_;
    return defaultValue;
}
std::string UserDeleted::getValueOfPasswordHashAsString() const noexcept
{
    static const std::string defaultValue = std::string();
    if(passwordHash_)
        return std::string(passwordHash_->data(),passwordHash_->size());
    return defaultValue;
}
const std::shared_ptr<std::vector<char>> &UserDeleted::getPasswordHash() const noexcept
{
    return passwordHash_;
}
void UserDeleted::setPasswordHash(const std::vector<char> &pPasswordHash) noexcept
{
    passwordHash_ = std::make_shared<std::vector<char>>(pPasswordHash);
    dirtyFlag_[3] = true;
}
void UserDeleted::setPasswordHash(const std::string &pPasswordHash) noexcept
{
    passwordHash_ = std::make_shared<std::vector<char>>(pPasswordHash.c_str(),pPasswordHash.c_str()+pPasswordHash.length());
    dirtyFlag_[3] = true;
}

const int32_t &UserDeleted::getValueOfPrivilege() const noexcept
{
    static const int32_t defaultValue = int32_t();
    if(privilege_)
        return *privilege_;
    return defaultValue;
}
const std::shared_ptr<int32_t> &UserDeleted::getPrivilege() const noexcept
{
    return privilege_;
}
void UserDeleted::setPrivilege(const int32_t &pPrivilege) noexcept
{
    privilege_ = std::make_shared<int32_t>(pPrivilege);
    dirtyFlag_[4] = true;
}

const std::string &UserDeleted::getValueOfNickname() const noexcept
{
    static const std::string defaultValue = std::string();
    if(nickname_)
        return *nickname_;
    return defaultValue;
}
const std::shared_ptr<std::string> &UserDeleted::getNickname() const noexcept
{
    return nickname_;
}
void UserDeleted::setNickname(const std::string &pNickname) noexcept
{
    nickname_ = std::make_shared<std::string>(pNickname);
    dirtyFlag_[5] = true;
}
void UserDeleted::setNickname(std::string &&pNickname) noexcept
{
    nickname_ = std::make_shared<std::string>(std::move(pNickname));
    dirtyFlag_[5] = true;
}

const std::string &UserDeleted::getValueOfTelephoneNumber() const noexcept
{
    static const std::string defaultValue = std::string();
    if(telephoneNumber_)
        return *telephoneNumber_;
    return defaultValue;
}
const std::shared_ptr<std::string> &UserDeleted::getTelephoneNumber() const noexcept
{
    return telephoneNumber_;
}
void UserDeleted::setTelephoneNumber(const std::string &pTelephoneNumber) noexcept
{
    telephoneNumber_ = std::make_shared<std::string>(pTelephoneNumber);
    dirtyFlag_[6] = true;
}
void UserDeleted::setTelephoneNumber(std::string &&pTelephoneNumber) noexcept
{
    telephoneNumber_ = std::make_shared<std::string>(std::move(pTelephoneNumber));
    dirtyFlag_[6] = true;
}
void UserDeleted::setTelephoneNumberToNull() noexcept
{
    telephoneNumber_.reset();
    dirtyFlag_[6] = true;
}

const std::string &UserDeleted::getValueOfEmail() const noexcept
{
    static const std::string defaultValue = std::string();
    if(email_)
        return *email_;
    return defaultValue;
}
const std::shared_ptr<std::string> &UserDeleted::getEmail() const noexcept
{
    return email_;
}
void UserDeleted::setEmail(const std::string &pEmail) noexcept
{
    email_ = std::make_shared<std::string>(pEmail);
    dirtyFlag_[7] = true;
}
void UserDeleted::setEmail(std::string &&pEmail) noexcept
{
    email_ = std::make_shared<std::string>(std::move(pEmail));
    dirtyFlag_[7] = true;
}
void UserDeleted::setEmailToNull() noexcept
{
    email_.reset();
    dirtyFlag_[7] = true;
}

const bool &UserDeleted::getValueOfIsMale() const noexcept
{
    static const bool defaultValue = bool();
    if(isMale_)
        return *isMale_;
    return defaultValue;
}
const std::shared_ptr<bool> &UserDeleted::getIsMale() const noexcept
{
    return isMale_;
}
void UserDeleted::setIsMale(const bool &pIsMale) noexcept
{
    isMale_ = std::make_shared<bool>(pIsMale);
    dirtyFlag_[8] = true;
}

const ::trantor::Date &UserDeleted::getValueOfCreateAt() const noexcept
{
    static const ::trantor::Date defaultValue = ::trantor::Date();
    if(createAt_)
        return *createAt_;
    return defaultValue;
}
const std::shared_ptr<::trantor::Date> &UserDeleted::getCreateAt() const noexcept
{
    return createAt_;
}
void UserDeleted::setCreateAt(const ::trantor::Date &pCreateAt) noexcept
{
    createAt_ = std::make_shared<::trantor::Date>(pCreateAt);
    dirtyFlag_[9] = true;
}

const ::trantor::Date &UserDeleted::getValueOfDeleteAt() const noexcept
{
    static const ::trantor::Date defaultValue = ::trantor::Date();
    if(deleteAt_)
        return *deleteAt_;
    return defaultValue;
}
const std::shared_ptr<::trantor::Date> &UserDeleted::getDeleteAt() const noexcept
{
    return deleteAt_;
}
void UserDeleted::setDeleteAt(const ::trantor::Date &pDeleteAt) noexcept
{
    deleteAt_ = std::make_shared<::trantor::Date>(pDeleteAt);
    dirtyFlag_[10] = true;
}

void UserDeleted::updateId(const uint64_t id)
{
}

const std::vector<std::string> &UserDeleted::insertColumns() noexcept
{
    static const std::vector<std::string> inCols={
        "id",
        "name",
        "password_salt",
        "password_hash",
        "privilege",
        "nickname",
        "telephone_number",
        "email",
        "is_male",
        "create_at",
        "delete_at"
    };
    return inCols;
}

void UserDeleted::outputArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[0])
    {
        if(getId())
        {
            binder << getValueOfId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[1])
    {
        if(getName())
        {
            binder << getValueOfName();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[2])
    {
        if(getPasswordSalt())
        {
            binder << getValueOfPasswordSalt();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[3])
    {
        if(getPasswordHash())
        {
            binder << getValueOfPasswordHash();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[4])
    {
        if(getPrivilege())
        {
            binder << getValueOfPrivilege();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[5])
    {
        if(getNickname())
        {
            binder << getValueOfNickname();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[6])
    {
        if(getTelephoneNumber())
        {
            binder << getValueOfTelephoneNumber();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[7])
    {
        if(getEmail())
        {
            binder << getValueOfEmail();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[8])
    {
        if(getIsMale())
        {
            binder << getValueOfIsMale();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[9])
    {
        if(getCreateAt())
        {
            binder << getValueOfCreateAt();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[10])
    {
        if(getDeleteAt())
        {
            binder << getValueOfDeleteAt();
        }
        else
        {
            binder << nullptr;
        }
    }
}

const std::vector<std::string> UserDeleted::updateColumns() const
{
    std::vector<std::string> ret;
    if(dirtyFlag_[0])
    {
        ret.push_back(getColumnName(0));
    }
    if(dirtyFlag_[1])
    {
        ret.push_back(getColumnName(1));
    }
    if(dirtyFlag_[2])
    {
        ret.push_back(getColumnName(2));
    }
    if(dirtyFlag_[3])
    {
        ret.push_back(getColumnName(3));
    }
    if(dirtyFlag_[4])
    {
        ret.push_back(getColumnName(4));
    }
    if(dirtyFlag_[5])
    {
        ret.push_back(getColumnName(5));
    }
    if(dirtyFlag_[6])
    {
        ret.push_back(getColumnName(6));
    }
    if(dirtyFlag_[7])
    {
        ret.push_back(getColumnName(7));
    }
    if(dirtyFlag_[8])
    {
        ret.push_back(getColumnName(8));
    }
    if(dirtyFlag_[9])
    {
        ret.push_back(getColumnName(9));
    }
    if(dirtyFlag_[10])
    {
        ret.push_back(getColumnName(10));
    }
    return ret;
}

void UserDeleted::updateArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[0])
    {
        if(getId())
        {
            binder << getValueOfId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[1])
    {
        if(getName())
        {
            binder << getValueOfName();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[2])
    {
        if(getPasswordSalt())
        {
            binder << getValueOfPasswordSalt();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[3])
    {
        if(getPasswordHash())
        {
            binder << getValueOfPasswordHash();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[4])
    {
        if(getPrivilege())
        {
            binder << getValueOfPrivilege();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[5])
    {
        if(getNickname())
        {
            binder << getValueOfNickname();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[6])
    {
        if(getTelephoneNumber())
        {
            binder << getValueOfTelephoneNumber();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[7])
    {
        if(getEmail())
        {
            binder << getValueOfEmail();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[8])
    {
        if(getIsMale())
        {
            binder << getValueOfIsMale();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[9])
    {
        if(getCreateAt())
        {
            binder << getValueOfCreateAt();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[10])
    {
        if(getDeleteAt())
        {
            binder << getValueOfDeleteAt();
        }
        else
        {
            binder << nullptr;
        }
    }
}
Json::Value UserDeleted::toJson() const
{
    Json::Value ret;
    if(getId())
    {
        ret["id"]=getValueOfId();
    }
    else
    {
        ret["id"]=Json::Value();
    }
    if(getName())
    {
        ret["name"]=getValueOfName();
    }
    else
    {
        ret["name"]=Json::Value();
    }
    if(getPasswordSalt())
    {
        ret["password_salt"]=drogon::utils::base64Encode((const unsigned char *)getPasswordSalt()->data(),getPasswordSalt()->size());
    }
    else
    {
        ret["password_salt"]=Json::Value();
    }
    if(getPasswordHash())
    {
        ret["password_hash"]=drogon::utils::base64Encode((const unsigned char *)getPasswordHash()->data(),getPasswordHash()->size());
    }
    else
    {
        ret["password_hash"]=Json::Value();
    }
    if(getPrivilege())
    {
        ret["privilege"]=getValueOfPrivilege();
    }
    else
    {
        ret["privilege"]=Json::Value();
    }
    if(getNickname())
    {
        ret["nickname"]=getValueOfNickname();
    }
    else
    {
        ret["nickname"]=Json::Value();
    }
    if(getTelephoneNumber())
    {
        ret["telephone_number"]=getValueOfTelephoneNumber();
    }
    else
    {
        ret["telephone_number"]=Json::Value();
    }
    if(getEmail())
    {
        ret["email"]=getValueOfEmail();
    }
    else
    {
        ret["email"]=Json::Value();
    }
    if(getIsMale())
    {
        ret["is_male"]=getValueOfIsMale();
    }
    else
    {
        ret["is_male"]=Json::Value();
    }
    if(getCreateAt())
    {
        ret["create_at"]=getCreateAt()->toDbStringLocal();
    }
    else
    {
        ret["create_at"]=Json::Value();
    }
    if(getDeleteAt())
    {
        ret["delete_at"]=getDeleteAt()->toDbStringLocal();
    }
    else
    {
        ret["delete_at"]=Json::Value();
    }
    return ret;
}

std::string UserDeleted::toString() const
{
    return toJson().toStyledString();
}

Json::Value UserDeleted::toMasqueradedJson(
    const std::vector<std::string> &pMasqueradingVector) const
{
    Json::Value ret;
    if(pMasqueradingVector.size() == 11)
    {
        if(!pMasqueradingVector[0].empty())
        {
            if(getId())
            {
                ret[pMasqueradingVector[0]]=getValueOfId();
            }
            else
            {
                ret[pMasqueradingVector[0]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[1].empty())
        {
            if(getName())
            {
                ret[pMasqueradingVector[1]]=getValueOfName();
            }
            else
            {
                ret[pMasqueradingVector[1]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[2].empty())
        {
            if(getPasswordSalt())
            {
                ret[pMasqueradingVector[2]]=drogon::utils::base64Encode((const unsigned char *)getPasswordSalt()->data(),getPasswordSalt()->size());
            }
            else
            {
                ret[pMasqueradingVector[2]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[3].empty())
        {
            if(getPasswordHash())
            {
                ret[pMasqueradingVector[3]]=drogon::utils::base64Encode((const unsigned char *)getPasswordHash()->data(),getPasswordHash()->size());
            }
            else
            {
                ret[pMasqueradingVector[3]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[4].empty())
        {
            if(getPrivilege())
            {
                ret[pMasqueradingVector[4]]=getValueOfPrivilege();
            }
            else
            {
                ret[pMasqueradingVector[4]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[5].empty())
        {
            if(getNickname())
            {
                ret[pMasqueradingVector[5]]=getValueOfNickname();
            }
            else
            {
                ret[pMasqueradingVector[5]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[6].empty())
        {
            if(getTelephoneNumber())
            {
                ret[pMasqueradingVector[6]]=getValueOfTelephoneNumber();
            }
            else
            {
                ret[pMasqueradingVector[6]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[7].empty())
        {
            if(getEmail())
            {
                ret[pMasqueradingVector[7]]=getValueOfEmail();
            }
            else
            {
                ret[pMasqueradingVector[7]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[8].empty())
        {
            if(getIsMale())
            {
                ret[pMasqueradingVector[8]]=getValueOfIsMale();
            }
            else
            {
                ret[pMasqueradingVector[8]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[9].empty())
        {
            if(getCreateAt())
            {
                ret[pMasqueradingVector[9]]=getCreateAt()->toDbStringLocal();
            }
            else
            {
                ret[pMasqueradingVector[9]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[10].empty())
        {
            if(getDeleteAt())
            {
                ret[pMasqueradingVector[10]]=getDeleteAt()->toDbStringLocal();
            }
            else
            {
                ret[pMasqueradingVector[10]]=Json::Value();
            }
        }
        return ret;
    }
    LOG_ERROR << "Masquerade failed";
    if(getId())
    {
        ret["id"]=getValueOfId();
    }
    else
    {
        ret["id"]=Json::Value();
    }
    if(getName())
    {
        ret["name"]=getValueOfName();
    }
    else
    {
        ret["name"]=Json::Value();
    }
    if(getPasswordSalt())
    {
        ret["password_salt"]=drogon::utils::base64Encode((const unsigned char *)getPasswordSalt()->data(),getPasswordSalt()->size());
    }
    else
    {
        ret["password_salt"]=Json::Value();
    }
    if(getPasswordHash())
    {
        ret["password_hash"]=drogon::utils::base64Encode((const unsigned char *)getPasswordHash()->data(),getPasswordHash()->size());
    }
    else
    {
        ret["password_hash"]=Json::Value();
    }
    if(getPrivilege())
    {
        ret["privilege"]=getValueOfPrivilege();
    }
    else
    {
        ret["privilege"]=Json::Value();
    }
    if(getNickname())
    {
        ret["nickname"]=getValueOfNickname();
    }
    else
    {
        ret["nickname"]=Json::Value();
    }
    if(getTelephoneNumber())
    {
        ret["telephone_number"]=getValueOfTelephoneNumber();
    }
    else
    {
        ret["telephone_number"]=Json::Value();
    }
    if(getEmail())
    {
        ret["email"]=getValueOfEmail();
    }
    else
    {
        ret["email"]=Json::Value();
    }
    if(getIsMale())
    {
        ret["is_male"]=getValueOfIsMale();
    }
    else
    {
        ret["is_male"]=Json::Value();
    }
    if(getCreateAt())
    {
        ret["create_at"]=getCreateAt()->toDbStringLocal();
    }
    else
    {
        ret["create_at"]=Json::Value();
    }
    if(getDeleteAt())
    {
        ret["delete_at"]=getDeleteAt()->toDbStringLocal();
    }
    else
    {
        ret["delete_at"]=Json::Value();
    }
    return ret;
}

bool UserDeleted::validateJsonForCreation(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("id"))
    {
        if(!validJsonOfField(0, "id", pJson["id"], err, true))
            return false;
    }
    else
    {
        err="The id column cannot be null";
        return false;
    }
    if(pJson.isMember("name"))
    {
        if(!validJsonOfField(1, "name", pJson["name"], err, true))
            return false;
    }
    else
    {
        err="The name column cannot be null";
        return false;
    }
    if(pJson.isMember("password_salt"))
    {
        if(!validJsonOfField(2, "password_salt", pJson["password_salt"], err, true))
            return false;
    }
    else
    {
        err="The password_salt column cannot be null";
        return false;
    }
    if(pJson.isMember("password_hash"))
    {
        if(!validJsonOfField(3, "password_hash", pJson["password_hash"], err, true))
            return false;
    }
    else
    {
        err="The password_hash column cannot be null";
        return false;
    }
    if(pJson.isMember("privilege"))
    {
        if(!validJsonOfField(4, "privilege", pJson["privilege"], err, true))
            return false;
    }
    else
    {
        err="The privilege column cannot be null";
        return false;
    }
    if(pJson.isMember("nickname"))
    {
        if(!validJsonOfField(5, "nickname", pJson["nickname"], err, true))
            return false;
    }
    else
    {
        err="The nickname column cannot be null";
        return false;
    }
    if(pJson.isMember("telephone_number"))
    {
        if(!validJsonOfField(6, "telephone_number", pJson["telephone_number"], err, true))
            return false;
    }
    if(pJson.isMember("email"))
    {
        if(!validJsonOfField(7, "email", pJson["email"], err, true))
            return false;
    }
    if(pJson.isMember("is_male"))
    {
        if(!validJsonOfField(8, "is_male", pJson["is_male"], err, true))
            return false;
    }
    else
    {
        err="The is_male column cannot be null";
        return false;
    }
    if(pJson.isMember("create_at"))
    {
        if(!validJsonOfField(9, "create_at", pJson["create_at"], err, true))
            return false;
    }
    else
    {
        err="The create_at column cannot be null";
        return false;
    }
    if(pJson.isMember("delete_at"))
    {
        if(!validJsonOfField(10, "delete_at", pJson["delete_at"], err, true))
            return false;
    }
    else
    {
        err="The delete_at column cannot be null";
        return false;
    }
    return true;
}
bool UserDeleted::validateMasqueradedJsonForCreation(const Json::Value &pJson,
                                                     const std::vector<std::string> &pMasqueradingVector,
                                                     std::string &err)
{
    if(pMasqueradingVector.size() != 11)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty())
      {
          if(pJson.isMember(pMasqueradingVector[0]))
          {
              if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[0] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[1].empty())
      {
          if(pJson.isMember(pMasqueradingVector[1]))
          {
              if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[1] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[2].empty())
      {
          if(pJson.isMember(pMasqueradingVector[2]))
          {
              if(!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[2] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[3].empty())
      {
          if(pJson.isMember(pMasqueradingVector[3]))
          {
              if(!validJsonOfField(3, pMasqueradingVector[3], pJson[pMasqueradingVector[3]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[3] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[4].empty())
      {
          if(pJson.isMember(pMasqueradingVector[4]))
          {
              if(!validJsonOfField(4, pMasqueradingVector[4], pJson[pMasqueradingVector[4]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[4] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[5].empty())
      {
          if(pJson.isMember(pMasqueradingVector[5]))
          {
              if(!validJsonOfField(5, pMasqueradingVector[5], pJson[pMasqueradingVector[5]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[5] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[6].empty())
      {
          if(pJson.isMember(pMasqueradingVector[6]))
          {
              if(!validJsonOfField(6, pMasqueradingVector[6], pJson[pMasqueradingVector[6]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[7].empty())
      {
          if(pJson.isMember(pMasqueradingVector[7]))
          {
              if(!validJsonOfField(7, pMasqueradingVector[7], pJson[pMasqueradingVector[7]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[8].empty())
      {
          if(pJson.isMember(pMasqueradingVector[8]))
          {
              if(!validJsonOfField(8, pMasqueradingVector[8], pJson[pMasqueradingVector[8]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[8] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[9].empty())
      {
          if(pJson.isMember(pMasqueradingVector[9]))
          {
              if(!validJsonOfField(9, pMasqueradingVector[9], pJson[pMasqueradingVector[9]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[9] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[10].empty())
      {
          if(pJson.isMember(pMasqueradingVector[10]))
          {
              if(!validJsonOfField(10, pMasqueradingVector[10], pJson[pMasqueradingVector[10]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[10] + " column cannot be null";
            return false;
        }
      }
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool UserDeleted::validateJsonForUpdate(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("id"))
    {
        if(!validJsonOfField(0, "id", pJson["id"], err, false))
            return false;
    }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
    if(pJson.isMember("name"))
    {
        if(!validJsonOfField(1, "name", pJson["name"], err, false))
            return false;
    }
    if(pJson.isMember("password_salt"))
    {
        if(!validJsonOfField(2, "password_salt", pJson["password_salt"], err, false))
            return false;
    }
    if(pJson.isMember("password_hash"))
    {
        if(!validJsonOfField(3, "password_hash", pJson["password_hash"], err, false))
            return false;
    }
    if(pJson.isMember("privilege"))
    {
        if(!validJsonOfField(4, "privilege", pJson["privilege"], err, false))
            return false;
    }
    if(pJson.isMember("nickname"))
    {
        if(!validJsonOfField(5, "nickname", pJson["nickname"], err, false))
            return false;
    }
    if(pJson.isMember("telephone_number"))
    {
        if(!validJsonOfField(6, "telephone_number", pJson["telephone_number"], err, false))
            return false;
    }
    if(pJson.isMember("email"))
    {
        if(!validJsonOfField(7, "email", pJson["email"], err, false))
            return false;
    }
    if(pJson.isMember("is_male"))
    {
        if(!validJsonOfField(8, "is_male", pJson["is_male"], err, false))
            return false;
    }
    if(pJson.isMember("create_at"))
    {
        if(!validJsonOfField(9, "create_at", pJson["create_at"], err, false))
            return false;
    }
    if(pJson.isMember("delete_at"))
    {
        if(!validJsonOfField(10, "delete_at", pJson["delete_at"], err, false))
            return false;
    }
    return true;
}
bool UserDeleted::validateMasqueradedJsonForUpdate(const Json::Value &pJson,
                                                   const std::vector<std::string> &pMasqueradingVector,
                                                   std::string &err)
{
    if(pMasqueradingVector.size() != 11)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
      {
          if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, false))
              return false;
      }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
      if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
      {
          if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, false))
              return false;
      }
      if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
      {
          if(!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err, false))
              return false;
      }
      if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
      {
          if(!validJsonOfField(3, pMasqueradingVector[3], pJson[pMasqueradingVector[3]], err, false))
              return false;
      }
      if(!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
      {
          if(!validJsonOfField(4, pMasqueradingVector[4], pJson[pMasqueradingVector[4]], err, false))
              return false;
      }
      if(!pMasqueradingVector[5].empty() && pJson.isMember(pMasqueradingVector[5]))
      {
          if(!validJsonOfField(5, pMasqueradingVector[5], pJson[pMasqueradingVector[5]], err, false))
              return false;
      }
      if(!pMasqueradingVector[6].empty() && pJson.isMember(pMasqueradingVector[6]))
      {
          if(!validJsonOfField(6, pMasqueradingVector[6], pJson[pMasqueradingVector[6]], err, false))
              return false;
      }
      if(!pMasqueradingVector[7].empty() && pJson.isMember(pMasqueradingVector[7]))
      {
          if(!validJsonOfField(7, pMasqueradingVector[7], pJson[pMasqueradingVector[7]], err, false))
              return false;
      }
      if(!pMasqueradingVector[8].empty() && pJson.isMember(pMasqueradingVector[8]))
      {
          if(!validJsonOfField(8, pMasqueradingVector[8], pJson[pMasqueradingVector[8]], err, false))
              return false;
      }
      if(!pMasqueradingVector[9].empty() && pJson.isMember(pMasqueradingVector[9]))
      {
          if(!validJsonOfField(9, pMasqueradingVector[9], pJson[pMasqueradingVector[9]], err, false))
              return false;
      }
      if(!pMasqueradingVector[10].empty() && pJson.isMember(pMasqueradingVector[10]))
      {
          if(!validJsonOfField(10, pMasqueradingVector[10], pJson[pMasqueradingVector[10]], err, false))
              return false;
      }
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool UserDeleted::validJsonOfField(size_t index,
                                   const std::string &fieldName,
                                   const Json::Value &pJson,
                                   std::string &err,
                                   bool isForCreation)
{
    switch(index)
    {
        case 0:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isInt())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 1:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            if(pJson.isString() && std::wstring_convert<std::codecvt_utf8_utf16<wchar_t>, wchar_t>{}
                .from_bytes(pJson.asCString()).size() > 30)
            {
                err="String length exceeds limit for the " +
                    fieldName +
                    " field (the maximum value is 30)";
                return false;
            }
            break;
        case 2:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 3:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 4:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isInt())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 5:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            if(pJson.isString() && std::wstring_convert<std::codecvt_utf8_utf16<wchar_t>, wchar_t>{}
                .from_bytes(pJson.asCString()).size() > 30)
            {
                err="String length exceeds limit for the " +
                    fieldName +
                    " field (the maximum value is 30)";
                return false;
            }
            break;
        case 6:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            if(pJson.isString() && std::wstring_convert<std::codecvt_utf8_utf16<wchar_t>, wchar_t>{}
                .from_bytes(pJson.asCString()).size() > 15)
            {
                err="String length exceeds limit for the " +
                    fieldName +
                    " field (the maximum value is 15)";
                return false;
            }
            break;
        case 7:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            if(pJson.isString() && std::wstring_convert<std::codecvt_utf8_utf16<wchar_t>, wchar_t>{}
                .from_bytes(pJson.asCString()).size() > 100)
            {
                err="String length exceeds limit for the " +
                    fieldName +
                    " field (the maximum value is 100)";
                return false;
            }
            break;
        case 8:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isBool())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 9:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 10:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        default:
            err="Internal error in the server";
            return false;
    }
    return true;
}
